"""Batch K: cinema actors (17 x 10 = 170)."""
import json

CAT = "cinema"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"

AUTHORS = {
"brando": ("Marlon Brando", "Actor · Godfather", "Attore · Il Padrino", "1924–2004",
 "Omaha brute who mumbled acting into truth.",
 "Forza di Omaha che borbottò la recitazione in verità."),
"deniro": ("Robert De Niro", "Actor · Raging Bull", "Attore · Toro scatenato", "1943–",
 "Greenwich Village chameleon of rage and silence.",
 "Camaleonte del Village di rabbia e silenzio."),
"pacino": ("Al Pacino", "Actor · Scarface", "Attore · Scarface", "1940–",
 "Bronx volcano shouting from courtrooms and stages.",
 "Vulcano del Bronx che grida da aule e palchi."),
"nicholson": ("Jack Nicholson", "Actor · Shining", "Attore · Shining", "1937–",
 "Neptune grin behind an axe and sunglasses.",
 "Sorriso di Neptune dietro scure e occhiali."),
"streep": ("Meryl Streep", "Actress · Sophie's Choice", "Attrice · La scelta di Sophie", "1949–",
 "Summit chameleon collecting accents and Oscars.",
 "Camaleonte di Summit che colleziona accenti e Oscar."),
"hepburn": ("Audrey Hepburn", "Actress · Roman Holiday", "Attrice · Vacanze romane", "1929–1993",
 "Brussels gamine feeding children as ambassador.",
 "Monella di Bruxelles che nutrì bambini come ambasciatrice."),
"bogart": ("Humphrey Bogart", "Actor · Casablanca", "Attore · Casablanca", "1899–1957",
 "New York cynic toasting foggy runways.",
 "Cinico newyorkese che brinda su piste nebbiose."),
"monroe": ("Marilyn Monroe", "Actress · Gentlemen", "Attrice · Gli uomini preferiscono le bionde", "1926–1962",
 "Blonde myth smarter than the studios.",
 "Mito biondo più intelligente degli studio."),
"eastwood": ("Clint Eastwood", "Actor, Director · Unforgiven", "Attore, Regista · Gli spietati", "1930–",
 "San Francisco squinter directing justice.",
 "Strizzatore d'occhi di San Francisco che dirige giustizia."),
"newman": ("Paul Newman", "Actor · Cool Hand Luke", "Attore · Nick mano fredda", "1925–2008",
 "Blue-eyed rebel bottling salad truth.",
 "Ribelle dagli occhi blu che imbottigliò verità in insalata."),
"mastroianni": ("Marcello Mastroianni", "Actor · 8½, Dolce Vita", "Attore · 8½, Dolce Vita", "1924–1996",
 "Ciociaro Latin lover of sweet idleness.",
 "Latin lover ciociaro di dolce ozio."),
"loren": ("Sophia Loren", "Actress · Two Women", "Attrice · La ciociara", "1934–",
 "Pozzuoli goddess who conquered Hollywood hungry.",
 "Dea di Pozzuoli che conquistò Hollywood affamata."),
"sordi": ("Alberto Sordi", "Actor · American in Rome", "Attore · Un americano a Roma", "1920–2003",
 "Roman everyman maccheroni-ing the nation.",
 "Romano qualunque che ammaccheronò la nazione."),
"gassman": ("Vittorio Gassman", "Actor · Big Deal", "Attore · I soliti ignoti", "1922–2000",
 "Genoese mattatore roaring Dante and farce.",
 "Mattatore genovese che ruggì Dante e farsa."),
"magnani": ("Anna Magnani", "Actress · Rome Open City", "Attrice · Roma città aperta", "1908–1973",
 "Roman lioness howling through ruins.",
 "Leonessa romana che ululò tra le rovine."),
"moreau": ("Jeanne Moreau", "Actress · Jules et Jim", "Attrice · Jules e Jim", "1928–2017",
 "Paris voice of ambiguous desire.",
 "Voce parigina di desiderio ambiguo."),
"bardot": ("Brigitte Bardot", "Actress · And God Created", "Attrice · E Dio creò la donna", "1934–",
 "Saint-Tropez bombshell turned animal guardian.",
 "Bomba di Saint-Tropez diventata guardiana di animali."),
}

Q = [
("brando-01","brando","I coulda been a contender.","Potevo essere un campione.",A,AI),
("brando-02","brando","Acting is the expression of neurosis.","Recitare è espressione di nevrosi.",A,AI),
("brando-03","brando","Make him an offer of silence.","Fagli un'offerta di silenzio.",A,AI),
("brando-04","brando","Omaha streets taught swagger.","Le strade di Omaha insegnarono spavalderia.",A,AI),
("brando-05","brando","Stellaaaa echoes forever.","Stellaaaa echeggia per sempre.",A,AI),
("brando-06","brando","Islands forgive Hollywood.","Le isole perdonano Hollywood.",A,AI),
("brando-07","brando","Mumble the truth loudly.","Borbottia la verità forte.",A,AI),
("brando-08","brando","Bounty mutinies boredom.","Il Bounty ammutina la noia.",A,AI),
("brando-09","brando","Apocalypse needs method.","L'apocalisse ha bisogno di metodo.",A,AI),
("brando-10","brando","Horror has a bald head.","L'orrore ha testa calva.",A,AI),
("deniro-01","deniro","Are you talkin' to me?","Dici a me?",A,AI),
("deniro-02","deniro","Raging bulls bleed method.","I tori scatenati sanguinano metodo.",A,AI),
("deniro-03","deniro","Tribeca rebuilds downtown.","Tribeca ricostruisce downtown.",S,SI),
("deniro-04","deniro","Taxi nights never sleep.","Le notti dei taxi non dormono mai.",A,AI),
("deniro-05","deniro","Goodfellas laugh last.","I bravi ragazzi ridono ultimi.",A,AI),
("deniro-06","deniro","Deer hunters aim inward.","I cacciatori di cervi mirano dentro.",A,AI),
("deniro-07","deniro","Little Italy seasons roles.","Little Italy condisce ruoli.",S,SI),
("deniro-08","deniro","Fockers forgive fathers.","I Focker perdonano padri.",A,AI),
("deniro-09","deniro","Silence acting speaks.","Recitare silenzio parla.",S,SI),
("deniro-10","deniro","Irishmen confess long.","Gli irlandesi confessano lungo.",A,AI),
("pacino-01","pacino","Say hello to intensity.","Saluta l'intensità.",A,AI),
("pacino-02","pacino","Hoo-ah echoes boardrooms.","Hoo-ah echeggia consigli.",A,AI),
("pacino-03","pacino","Bronx stages breed volcanoes.","I palchi del Bronx allevano vulcani.",S,SI),
("pacino-04","pacino","Godfather whispers power.","Il Padrino sussurra potere.",A,AI),
("pacino-05","pacino","Scarface snorts ambition.","Scarface sniffa ambizione.",A,AI),
("pacino-06","pacino","Dog days bark truth.","Quei pomeriggi da cani abbaiano verità.",A,AI),
("pacino-07","pacino","Shakespeare needs shouting.","Shakespeare ha bisogno di grida.",S,SI),
("pacino-08","pacino","Scent women wisely.","Annusa donne con saggezza.",A,AI),
("pacino-09","pacino","Heat chases thieves.","Heat insegue ladri.",A,AI),
("pacino-10","pacino","Lawyers devilishly defend.","Gli avvocati difendono diabolici.",A,AI),
("nicholson-01","nicholson","Here's Johnny grinning.","Ecco Johnny sorridente.",A,AI),
("nicholson-02","nicholson","Cuckoos fly over wards.","I cucù volano sui reparti.",A,AI),
("nicholson-03","nicholson","Neptune boys smirk.","I ragazzi di Neptune sogghignano.",A,AI),
("nicholson-04","nicholson","Chinatown forgets nothing.","Chinatown non dimentica nulla.",A,AI),
("nicholson-05","nicholson","Lakers courtside critiques.","Critiche a bordocampo dei Lakers.",A,AI),
("nicholson-06","nicholson","Easy riders ride eternal.","Gli easy rider cavalcano eterni.",A,AI),
("nicholson-07","nicholson","Sunglasses hide mischief.","Gli occhiali nascondono birichinate.",A,AI),
("nicholson-08","nicholson","Mars attacks egos.","Marte attacca gli ego.",A,AI),
("nicholson-09","nicholson","Batmen need jokers.","I Batman hanno bisogno di Joker.",A,AI),
("nicholson-10","nicholson","Bucket lists beat clocks.","Le liste dei desideri battono orologi.",A,AI),
("streep-01","streep","Accents unlock souls.","Gli accenti sbloccano anime.",S,SI),
("streep-02","streep","Sophie's choice haunts.","La scelta di Sophie ossessiona.",A,AI),
("streep-03","streep","Summit girls study hard.","Le ragazze di Summit studiano sodo.",S,SI),
("streep-04","streep","Devils wear nuance.","I diavoli vestono sfumature.",A,AI),
("streep-05","streep","Iron ladies rust never.","Le lady di ferro non arrugginiscono mai.",A,AI),
("streep-06","streep","Mamma mia sings twice.","Mamma mia canta due volte.",A,AI),
("streep-07","streep","Yale trains chameleons.","Yale allena camaleonti.",S,SI),
("streep-08","streep","Kramers fight fairly.","I Kramer lottano leale.",A,AI),
("streep-09","streep","Doubt whispers loudest.","Il dubbio sussurra più forte.",A,AI),
("streep-10","streep","Suffragettes vote forever.","Le suffragette votano per sempre.",A,AI),
("hepburn-01","hepburn","Breakfast at Tiffany's dreams.","Colazione da Tiffany sogna.",A,AI),
("hepburn-02","hepburn","Roman holidays end, grace stays.","Le vacanze romane finiscono, la grazia resta.",A,AI),
("hepburn-03","hepburn","Little black dresses endure.","I tubini neri durano.",A,AI),
("hepburn-04","hepburn","UNICEF needs gamines.","L'UNICEF ha bisogno di monelle.",S,SI),
("hepburn-05","hepburn","Brussels hunger feeds compassion.","La fame di Bruxelles nutre compassione.",S,SI),
("hepburn-06","hepburn","My Fair Lady learns kindness.","My Fair Lady impara gentilezza.",A,AI),
("hepburn-07","hepburn","Charade charms Paris.","Sciarada incanta Parigi.",A,AI),
("hepburn-08","hepburn","Elegance is refusal plus smile.","L'eleganza è rifiuto più sorriso.",A,AI),
("hepburn-09","hepburn","Nun's stories heal.","Le storie della suora guariscono.",A,AI),
("hepburn-10","hepburn","Children first, always.","Prima i bambini, sempre.",S,SI),
("bogart-01","bogart","Here's looking at you, kid.","Ti guardo, ragazzo.",A,AI),
("bogart-02","bogart","Foggy runways bid farewell.","Piste nebbiose dicono addio.",A,AI),
("bogart-03","bogart","Falcons outlast studios.","I falchi durano più degli studio.",A,AI),
("bogart-04","bogart","New York cynics toast.","I cinici newyorkesi brindano.",A,AI),
("bogart-05","bogart","Casablanca never closes.","Casablanca non chiude mai.",A,AI),
("bogart-06","bogart","Lisping gangsters growl.","I gangster con lisca ringhiano.",A,AI),
("bogart-07","bogart","Sahara tests thirst.","Il Sahara mette alla prova la sete.",A,AI),
("bogart-08","bogart","Queens mutiny boredom.","Gli ammutinati del Caine annoiano.",A,AI),
("bogart-09","bogart","Key Largos lock storms.","Key Largo chiude tempeste.",A,AI),
("bogart-10","bogart","Play it again, soulfully.","Suonala ancora, con anima.",A,AI),
("monroe-01","monroe","Diamonds console blondes.","I diamanti consolano le bionde.",A,AI),
("monroe-02","monroe","Seven-year itches scratch fame.","Il prurito dei sette anni gratta fama.",A,AI),
("monroe-03","monroe","Subways blow skirts skyward.","Le metropolitane soffiano gonne al cielo.",A,AI),
("monroe-04","monroe","Breathless songs seduce.","Canzoni senza fiato seducono.",A,AI),
("monroe-05","monroe","Orphanages forge myths.","Gli orfanotrofi forgiano miti.",A,AI),
("monroe-06","monroe","Smarter than the studio.","Più intelligente dello studio.",S,SI),
("monroe-07","monroe","Misfits mustang freedom.","I disadattati mustang libertà.",A,AI),
("monroe-08","monroe","Chekhov read in trailers.","Cechov letto nei caravan.",A,AI),
("monroe-09","monroe","Happy birthday, Mr. President.","Buon compleanno, signor Presidente.",A,AI),
("monroe-10","monroe","Candle in studio wind.","Candela nel vento dello studio.",A,AI),
("eastwood-01","eastwood","Go ahead, make my film.","Forza, fammi il film.",A,AI),
("eastwood-02","eastwood","Unforgiven forgives slowly.","Gli spietati perdonano piano.",S,SI),
("eastwood-03","eastwood","San Francisco squints justice.","San Francisco strizza giustizia.",A,AI),
("eastwood-04","eastwood","Spaghetti westerns sauce truth.","I western all'italiana condiscono verità.",S,SI),
("eastwood-05","eastwood","Bridges of silence ache.","I ponti del silenzio dolgono.",A,AI),
("eastwood-06","eastwood","Million-dollar restraint lands.","La moderazione da un milione arriva.",A,AI),
("eastwood-07","eastwood","Gran Torinos growl grace.","I Gran Torino ringhiano grazia.",A,AI),
("eastwood-08","eastwood","Direct quietly, shoot fast.","Dirigi piano, gira veloce.",S,SI),
("eastwood-09","eastwood","Carmel mayors govern calm.","I sindaci di Carmel governano calmi.",A,AI),
("eastwood-10","eastwood","Whistling scores sunsets.","Fischi musicano tramonti.",A,AI),
("newman-01","newman","Blue eyes, cool hands.","Occhi blu, mani fredde.",A,AI),
("newman-02","newman","Fifty eggs test stubbornness.","Cinquanta uova testano testardaggine.",A,AI),
("newman-03","newman","Hustlers chalk cues.","I imbroglioni gessano stecche.",A,AI),
("newman-04","newman","Salad dressing funds camps.","I condimenti finanziano campeggi.",S,SI),
("newman-05","newman","Racers brake for kids.","I piloti frenano per i bambini.",S,SI),
("newman-06","newman","Shaker Heights humbles stars.","Shaker Heights umilia dive.",A,AI),
("newman-07","newman","Butch jumps with Sundance.","Butch salta con Sundance.",A,AI),
("newman-08","newman","Nobody's fool forever.","Nessuno è stupido per sempre.",A,AI),
("newman-09","newman","Charity seasons fame.","La carità condisce fama.",S,SI),
("newman-10","newman","Verbal sparring wins.","Lo sparring verbale vince.",A,AI),
("mastroianni-01","mastroianni","Sweet idleness, bitter mornings.","Dolce ozio, mattine amare.",A,AI),
("mastroianni-02","mastroianni","Via Veneto strolls vanity.","Via Veneto passeggia vanità.",A,AI),
("mastroianni-03","mastroianni","8½ dreams director's block.","8½ sogna il blocco del regista.",A,AI),
("mastroianni-04","mastroianni","Ciociaro charm conquers.","Il fascino ciociaro conquista.",A,AI),
("mastroianni-05","mastroianni","Divorce Italian style laughs.","Divorzio all'italiana ride.",A,AI),
("mastroianni-06","mastroianni","Fellini's alter ego smokes.","L'alter ego di Fellini fuma.",S,SI),
("mastroianni-07","mastroianni","Night fountains baptize.","Le fontane notturne battezzano.",A,AI),
("mastroianni-08","mastroianni","Dark eyes, light touch.","Occhi scuri, tocco leggero.",A,AI),
("mastroianni-09","mastroianni","Sunflowers face war.","I girasoli guardano la guerra.",A,AI),
("mastroianni-10","mastroianni","Loren pairs perfectly.","La Loren si abbina perfetta.",A,AI),
("loren-01","loren","Pozzuoli hunger feeds glory.","La fame di Pozzuoli nutre gloria.",S,SI),
("loren-02","loren","Two women weep history.","Due donne piangono storia.",A,AI),
("loren-03","loren","Hollywood kneels to Naples.","Hollywood si inginocchia a Napoli.",A,AI),
("loren-04","loren","Mastroianni dances best.","Mastroianni danza meglio.",S,SI),
("loren-05","loren","Spaghetti arms embrace.","Braccia di spaghetti abbracciano.",A,AI),
("loren-06","loren","Oscar thanks Ciociaria.","L'Oscar ringrazia la Ciociaria.",S,SI),
("loren-07","loren","Yesterday's bread, today's crown.","Il pane di ieri, la corona di oggi.",A,AI),
("loren-08","loren","Neapolitan eyes ignite.","Gli occhi napoletani accendono.",A,AI),
("loren-09","loren","Marriage outlasts premieres.","Il matrimonio dura più delle prime.",S,SI),
("loren-10","loren","Beauty ages into legend.","La bellezza invecchia in leggenda.",S,SI),
("sordi-01","sordi","Maccheroni, you provoked me.","Maccheroni, m'hai provocato.",A,AI),
("sordi-02","sordi","Romans laugh at themselves.","I romani ridono di sé.",S,SI),
("sordi-03","sordi","An American in Rome dreams.","Un americano a Roma sogna.",A,AI),
("sordi-04","sordi","Traffic cops direct chaos.","I vigili dirigono caos.",A,AI),
("sordi-05","sordi","Trastevere voices echo.","Le voci di Trastevere echeggiano.",A,AI),
("sordi-06","sordi","War heroes bumble kindly.","Gli eroi di guerra inciampano gentili.",A,AI),
("sordi-07","sordi","Doctors prescribe laughter.","I dottori prescrivono risate.",A,AI),
("sordi-08","sordi","Marchese del Grillo reigns.","Il Marchese del Grillo regna.",A,AI),
("sordi-09","sordi","Everymen outlive regimes.","I qualunque sopravvivono ai regimi.",S,SI),
("sordi-10","sordi","Fiasco with a smile.","Fiasco con sorriso.",A,AI),
("gassman-01","gassman","Mattatore roars rounds.","Il mattatore ruggisce turni.",A,AI),
("gassman-02","gassman","Dante declaimed at stadiums.","Dante declamato negli stadi.",S,SI),
("gassman-03","gassman","Genoa storms the stage.","Genova assalta il palco.",A,AI),
("gassman-04","gassman","Unknown soldiers laugh.","I soliti ignoti ridono.",A,AI),
("gassman-05","gassman","Scent adapts blindly.","Profumo si adatta cieco.",A,AI),
("gassman-06","gassman","Hamlet in rugby socks.","Amleto in calzini da rugby.",A,AI),
("gassman-07","gassman","Theater schools the screen.","Il teatro istruisce lo schermo.",S,SI),
("gassman-08","gassman","Brancaleone armies stumble.","Le armate Brancaleone inciampano.",A,AI),
("gassman-09","gassman","Shouting teaches whispering.","Gridare insegna a sussurrare.",S,SI),
("gassman-10","gassman","Farewell tours thunder.","Le tournée d'addio tuonano.",A,AI),
("magnani-01","magnani","Rome howls through ruins.","Roma ulula tra le rovine.",A,AI),
("magnani-02","magnani","Pina falls, legend rises.","Pina cade, la leggenda sorge.",A,AI),
("magnani-03","magnani","Lionesses need no makeup.","Le leonesse non hanno bisogno di trucco.",S,SI),
("magnani-04","magnani","Tattoos mark passion.","I tatuaggi marchiano passione.",A,AI),
("magnani-05","magnani","Hollywood bows to grit.","Hollywood si inchina alla grinta.",S,SI),
("magnani-06","magnani","Mamma Roma mothers all.","Mamma Roma è madre di tutti.",A,AI),
("magnani-07","magnani","Trastevere blood boils.","Il sangue di Trastevere bolle.",A,AI),
("magnani-08","magnani","Oscar thanks the streets.","L'Oscar ringrazia le strade.",S,SI),
("magnani-09","magnani","Acting is bleeding.","Recitare è sanguinare.",A,AI),
("magnani-10","magnani","Eternity wears black shawls.","L'eternità veste scialli neri.",A,AI),
("moreau-01","moreau","Jules loves, Jim loses.","Jules ama, Jim perde.",A,AI),
("moreau-02","moreau","Paris voices veil desire.","Le voci di Parigi velano desiderio.",A,AI),
("moreau-03","moreau","Elevators hang suspense.","Gli ascensori pendono suspense.",A,AI),
("moreau-04","moreau","Night Miles trumpet.","La notte tromba Miles.",A,AI),
("moreau-05","moreau","Ambiguity seduces most.","L'ambiguità seduce di più.",A,AI),
("moreau-06","moreau","New Wave needs muses.","La Nouvelle Vague ha bisogno di muse.",S,SI),
("moreau-07","moreau","Sing melancholy softly.","Canta malinconia piano.",A,AI),
("moreau-08","moreau","Lovers leap bridges.","Gli amanti saltano ponti.",A,AI),
("moreau-09","moreau","Age deepens voice.","L'età approfondisce la voce.",S,SI),
("moreau-10","moreau","Direct at seventy, dare.","Dirigi a settanta, osa.",S,SI),
("bardot-01","bardot","Saint-Tropez invented summer.","Saint-Tropez inventò l'estate.",A,AI),
("bardot-02","bardot","And God created scandal.","E Dio creò scandalo.",A,AI),
("bardot-03","bardot","Bikinis liberate beaches.","I bikini liberano spiagge.",A,AI),
("bardot-04","bardot","Animals need Brigitte.","Gli animali hanno bisogno di Brigitte.",S,SI),
("bardot-05","bardot","Quit fame, keep fur seals.","Lascia la fama, conserva le foche.",S,SI),
("bardot-06","bardot","Contempt critiques stardom.","Il disprezzo critica il divismo.",A,AI),
("bardot-07","bardot","Gingham dances freedom.","Il vichy danza libertà.",A,AI),
("bardot-08","bardot","Vadim framed myth.","Vadim inquadrò mito.",A,AI),
("bardot-09","bardot","Initials B.B. endure.","Le iniziali B.B. durano.",A,AI),
("bardot-10","bardot","Farm sanctuaries heal.","I santuari fattoria guariscono.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchK added={added} total_en={len(en)} total_it={len(it)}")
