"""Batch F: culture (17 authors x 10 = 170 quotes)."""
import json

CAT = "culture"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"

AUTHORS = {
"dante": ("Dante Alighieri", "Poet · Divine Comedy", "Poeta · Divina Commedia", "1265–1321",
 "Florentine exile who mapped Hell, Purgatory and Paradise.",
 "Esule fiorentino che mappò Inferno, Purgatorio e Paradiso."),
"leonardo": ("Leonardo da Vinci", "Artist, Inventor", "Artista, Inventore", "1452–1519",
 "Vinci genius painting smiles and designing flying machines.",
 "Genio di Vinci che dipinse sorrisi e progettò macchine volanti."),
"seneca": ("Seneca", "Philosopher · Letters", "Filosofo · Lettere", "4 BCE–65",
 "Roman Stoic teaching time as the only true wealth.",
 "Stoico romano che insegnò il tempo come unica vera ricchezza."),
"aurelius": ("Marcus Aurelius", "Emperor, Philosopher", "Imperatore, Filosofo", "121–180",
 "Emperor who journaled Meditations on duty and calm.",
 "Imperatore che annotò nei Ricordi dovere e calma."),
"machiavelli": ("Niccolò Machiavelli", "Writer · The Prince", "Scrittore · Il Principe", "1469–1527",
 "Florentine secretary dissecting power without illusions.",
 "Segretario fiorentino che sezionò il potere senza illusioni."),
"galileo": ("Galileo Galilei", "Scientist · Dialogue", "Scienziato · Dialogo", "1564–1642",
 "Pisan who pointed the telescope at the heavens and truth.",
 "Pisano che puntò il telescopio verso cieli e verità."),
"leopardi": ("Giacomo Leopardi", "Poet · Canti", "Poeta · Canti", "1798–1837",
 "Recanati poet singing infinity from a hill.",
 "Poeta recanatese che cantò l'infinito da un colle."),
"manzoni": ("Alessandro Manzoni", "Writer · The Betrothed", "Scrittore · I promessi sposi", "1785–1873",
 "Milan novelist who gave Italy its language and conscience.",
 "Romanziere milanese che diede all'Italia lingua e coscienza."),
"gramsci": ("Antonio Gramsci", "Thinker · Prison Notebooks", "Pensatore · Quaderni del carcere", "1891–1937",
 "Sardinian thinker writing freedom from a fascist cell.",
 "Pensatore sardo che scrisse libertà da una cella fascista."),
"borges": ("Jorge Luis Borges", "Writer · Fictions", "Scrittore · Finzioni", "1899–1986",
 "Blind librarian of infinite labyrinths and tigers.",
 "Bibliotecario cieco di labirinti infiniti e tigri."),
"neruda": ("Pablo Neruda", "Poet · Twenty Poems", "Poeta · Venti poesie", "1904–1973",
 "Chilean singer of love, salt and numbered things.",
 "Cantore cileno dell'amore, del sale e delle cose numerate."),
"woolf": ("Virginia Woolf", "Writer · Mrs Dalloway", "Scrittrice · Mrs Dalloway", "1882–1941",
 "London explorer of consciousness and rooms of one's own.",
 "Esploratrice londinese di coscienza e stanze proprie."),
"orwell": ("George Orwell", "Writer · 1984", "Scrittore · 1984", "1903–1950",
 "Plainspoken sentinel against lies and Big Brother.",
 "Sentinella schietta contro menzogne e Grande Fratello."),
"sartre": ("Jean-Paul Sartre", "Philosopher · Being", "Filosofo · L'essere", "1905–1980",
 "Paris existentialist condemned to be free.",
 "Esistenzialista parigino condannato a essere libero."),
"beauvoir": ("Simone de Beauvoir", "Philosopher · Second Sex", "Filosofa · Secondo sesso", "1908–1986",
 "Paris thinker who made womanhood a project of freedom.",
 "Pensatrice parigina che fece della femminilità un progetto di libertà."),
"gandhi": ("Mahatma Gandhi", "Leader · Nonviolence", "Guida · Nonviolenza", "1869–1948",
 "Lawyer of peace who spun independence from a wheel.",
 "Avvocato di pace che filò l'indipendenza da un arcolaio."),
"mandela": ("Nelson Mandela", "Leader · Long Walk", "Guida · Lungo cammino", "1918–2013",
 "Prisoner of 27 years who freed a nation with forgiveness.",
 "Prigioniero per 27 anni che liberò una nazione col perdono."),
}

Q = [
("dante-01","dante","Abandon all hope, you who enter.","Lasciate ogni speranza, voi ch'entrate.",A,AI),
("dante-02","dante","Love, that moves the sun and stars.","L'amor che move il sole e l'altre stelle.",A,AI),
("dante-03","dante","In the middle of our life's journey.","Nel mezzo del cammin di nostra vita.",A,AI),
("dante-04","dante","Follow your star and you shall not fail.","Segui la tua stella e non fallirai.",A,AI),
("dante-05","dante","The hottest hell for the neutral.","Il più rovente inferno per i neutrali.",A,AI),
("dante-06","dante","No greater pain than happy memory in grief.","Nessun maggior dolore che ricordar del tempo felice.",A,AI),
("dante-07","dante","Consider your origin: made to follow virtue.","Considerate la vostra semenza: fatti per seguir virtute.",A,AI),
("dante-08","dante","Purgatory climbs toward light.","Il Purgatorio sale verso la luce.",A,AI),
("dante-09","dante","Beatrice guides beyond reason.","Beatrice guida oltre la ragione.",A,AI),
("dante-10","dante","Florence exiles, eternity welcomes.","Firenze esilia, l'eternità accoglie.",A,AI),
("leonardo-01","leonardo","Simplicity is the ultimate sophistication.","La semplicità è l'ultima sofisticazione.",A,AI),
("leonardo-02","leonardo","Learning never exhausts the mind.","Lo studio non esaurisce mai la mente.",A,AI),
("leonardo-03","leonardo","The smile hides a thousand studies.","Il sorriso nasconde mille studi.",A,AI),
("leonardo-04","leonardo","Water is the driving force of nature.","L'acqua è la forza motrice della natura.",A,AI),
("leonardo-05","leonardo","Sketch daily; genius compounds.","Disegna ogni giorno; il genio si accumula.",A,AI),
("leonardo-06","leonardo","Wings test the dreams of men.","Le ali mettono alla prova i sogni degli uomini.",A,AI),
("leonardo-07","leonardo","Anatomy reveals the soul's machinery.","L'anatomia rivela la macchina dell'anima.",A,AI),
("leonardo-08","leonardo","Patience serves the perfect sfumato.","La pazienza serve il perfetto sfumato.",A,AI),
("leonardo-09","leonardo","Left hand writes, right hand imagines.","La sinistra scrive, la destra immagina.",A,AI),
("leonardo-10","leonardo","Vinci's hills taught perspective.","Le colline di Vinci insegnarono prospettiva.",A,AI),
("seneca-01","seneca","It is not that we have little time, but waste much.","Non è che abbiamo poco tempo, ma ne sprechiamo molto.",A,AI),
("seneca-02","seneca","Luck is preparation meeting opportunity.","La fortuna è preparazione che incontra occasione.",A,AI),
("seneca-03","seneca","Difficulties strengthen the mind.","Le difficoltà fortificano la mente.",A,AI),
("seneca-04","seneca","Begin at once to live.","Comincia subito a vivere.",A,AI),
("seneca-05","seneca","Anger is brief madness.","L'ira è breve follia.",A,AI),
("seneca-06","seneca","We suffer more in imagination than reality.","Soffriamo più nell'immaginazione che nella realtà.",A,AI),
("seneca-07","seneca","Every new beginning comes from an end.","Ogni nuovo inizio nasce da una fine.",A,AI),
("seneca-08","seneca","Associate with those who improve you.","Frequenta chi ti migliora.",A,AI),
("seneca-09","seneca","The wise lack nothing yet need little.","Il saggio non manca di nulla e ha bisogno di poco.",A,AI),
("seneca-10","seneca","Letters bridge absent friends.","Le lettere uniscono amici lontani.",A,AI),
("aurelius-01","aurelius","The impediment to action advances action.","L'ostacolo all'azione fa avanzare l'azione.",A,AI),
("aurelius-02","aurelius","Waste no more time arguing what a good man is. Be one.","Non perdere tempo a discutere cos'è un uomo buono. Sii uno.",A,AI),
("aurelius-03","aurelius","The soul becomes dyed with its thoughts.","L'anima si tinge dei suoi pensieri.",A,AI),
("aurelius-04","aurelius","Dwell on beauty, not injury.","Dimora sulla bellezza, non sull'offesa.",A,AI),
("aurelius-05","aurelius","Morning: rise to the work of a human.","Mattino: alzati per l'opera di un uomo.",A,AI),
("aurelius-06","aurelius","Accept what fate binds.","Accetta ciò che il fato lega.",A,AI),
("aurelius-07","aurelius","The universe is change.","L'universo è cambiamento.",A,AI),
("aurelius-08","aurelius","Command the camp within.","Comanda l'accampamento interiore.",A,AI),
("aurelius-09","aurelius","Kindness is invincible.","La gentilezza è invincibile.",A,AI),
("aurelius-10","aurelius","Danube nights teach duty.","Le notti del Danubio insegnano il dovere.",A,AI),
("machiavelli-01","machiavelli","It is better to act than to hesitate.","Meglio agire che esitare.",A,AI),
("machiavelli-02","machiavelli","Fortune favors the bold beginner.","La fortuna aiuta gli audaci principianti.",A,AI),
("machiavelli-03","machiavelli","Study the past to govern the future.","Studia il passato per governare il futuro.",A,AI),
("machiavelli-04","machiavelli","Appearances rule the many.","Le apparenze governano i molti.",A,AI),
("machiavelli-05","machiavelli","Prepare for war in peace.","Preparati alla guerra in pace.",A,AI),
("machiavelli-06","machiavelli","A prince must learn not to be good.","Un principe deve imparare a non esser buono.",A,AI),
("machiavelli-07","machiavelli","Florence punishes the naive.","Firenze punisce gli ingenui.",A,AI),
("machiavelli-08","machiavelli","Necessity mothers invention.","La necessità è madre dell'invenzione.",A,AI),
("machiavelli-09","machiavelli","Divide to understand power.","Dividi per capire il potere.",A,AI),
("machiavelli-10","machiavelli","Write truth, risk exile.","Scrivi verità, rischia l'esilio.",A,AI),
("galileo-01","galileo","And yet it moves.","Eppur si muove.",A,AI),
("galileo-02","galileo","Measure what can be measured.","Misura ciò che si può misurare.",A,AI),
("galileo-03","galileo","The telescope humbles dogma.","Il telescopio umilia il dogma.",A,AI),
("galileo-04","galileo","Doubt the textbook, trust the sky.","Dubita del manuale, fidati del cielo.",A,AI),
("galileo-05","galileo","Moons orbit Jupiter, minds must follow.","Le lune orbitano Giove, le menti devono seguire.",A,AI),
("galileo-06","galileo","Mathematics is nature's alphabet.","La matematica è l'alfabeto della natura.",A,AI),
("galileo-07","galileo","Pisa's tower dropped old errors.","La torre di Pisa fece cadere vecchi errori.",A,AI),
("galileo-08","galileo","Inquisition fears the lens.","L'Inquisizione teme la lente.",A,AI),
("galileo-09","galileo","Dialogue teaches better than decree.","Il dialogo insegna meglio del decreto.",A,AI),
("galileo-10","galileo","Stars reply to patience.","Le stelle rispondono alla pazienza.",A,AI),
("leopardi-01","leopardi","Infinity sings beyond the hedge.","L'infinito canta oltre la siepe.",A,AI),
("leopardi-02","leopardi","Sweet shipwreck in this sea.","Dolce naufragar in questo mare.",A,AI),
("leopardi-03","leopardi","Nature is beautiful and indifferent.","La natura è bella e indifferente.",A,AI),
("leopardi-04","leopardi","Recanati walls hold the universe.","Le mura di Recanati trattengono l'universo.",A,AI),
("leopardi-05","leopardi","Hope deceives, yet sustains.","La speranza inganna, eppure sostiene.",A,AI),
("leopardi-06","leopardi","The moon converses with shepherds.","La luna conversa con i pastori.",A,AI),
("leopardi-07","leopardi","Boredom is the noblest passion.","La noia è la più nobile passione.",A,AI),
("leopardi-08","leopardi","Youth remembers Saturday's eve.","La gioventù ricorda il sabato del villaggio.",A,AI),
("leopardi-09","leopardi","Illusions console the wise.","Le illusioni consolano i saggi.",A,AI),
("leopardi-10","leopardi","Broom flowers resist the lava.","Le ginestre resistono alla lava.",A,AI),
("manzoni-01","manzoni","Providence disrupts and redeems.","La Provvidenza scompiglia e redime.",A,AI),
("manzoni-02","manzoni","The powerful need humble witnesses.","I potenti hanno bisogno di umili testimoni.",A,AI),
("manzoni-03","manzoni","Renzo and Lucia walk through history.","Renzo e Lucia camminano nella storia.",A,AI),
("manzoni-04","manzoni","Plague reveals every heart.","La peste rivela ogni cuore.",A,AI),
("manzoni-05","manzoni","Language unites the peninsula.","La lingua unisce la penisola.",A,AI),
("manzoni-06","manzoni","Wash history in the Arno of truth.","Lava la storia nell'Arno della verità.",A,AI),
("manzoni-07","manzoni","The inn of wrongs becomes justice.","L'osteria dei torti diventa giustizia.",A,AI),
("manzoni-08","manzoni","Milan forgives the repentant.","Milano perdona i pentiti.",A,AI),
("manzoni-09","manzoni","Faith steadies the betrothed.","La fede rassicura i promessi.",A,AI),
("manzoni-10","manzoni","Goodness persists quietly.","La bontà persiste in silenzio.",A,AI),
("gramsci-01","gramsci","Pessimism of intellect, optimism of will.","Pessimismo dell'intelligenza, ottimismo della volontà.",A,AI),
("gramsci-02","gramsci","Culture organizes humanity.","La cultura organizza l'umanità.",A,AI),
("gramsci-03","gramsci","Every teacher is a politician.","Ogni insegnante è un politico.",A,AI),
("gramsci-04","gramsci","Prison bars sharpen thought.","Le sbarre affinano il pensiero.",A,AI),
("gramsci-05","gramsci","Hegemony is consent armored.","L'egemonia è consenso corazzato.",A,AI),
("gramsci-06","gramsci","Sardinia forged my questions.","La Sardegna forgiò le mie domande.",A,AI),
("gramsci-07","gramsci","Study, study to resist.","Studia, studia per resistere.",A,AI),
("gramsci-08","gramsci","The old dies, the new struggles.","Il vecchio muore, il nuovo fatica a nascere.",A,AI),
("gramsci-09","gramsci","Notebooks outlive cells.","I quaderni sopravvivono alle celle.",A,AI),
("gramsci-10","gramsci","Truth is revolutionary.","La verità è rivoluzionaria.",A,AI),
("borges-01","borges","I always imagined Paradise as a library.","Ho sempre immaginato il Paradiso come una biblioteca.",A,AI),
("borges-02","borges","Time forks in every garden.","Il tempo si biforca in ogni giardino.",A,AI),
("borges-03","borges","Mirrors and copulation multiply men.","Gli specchi e la copula moltiplicano gli uomini.",A,AI),
("borges-04","borges","Tigers burn in my blindness.","Le tigri ardono nella mia cecità.",A,AI),
("borges-05","borges","A book is an axe for the frozen sea.","Un libro è un'ascia per il mare ghiacciato.",A,AI),
("borges-06","borges","Buenos Aires dreams my verses.","Buenos Aires sogna i miei versi.",A,AI),
("borges-07","borges","Labyrinths console infinity.","I labirinti consolano l'infinito.",A,AI),
("borges-08","borges","Forgetfulness is the only vengeance.","L'oblio è l'unica vendetta.",A,AI),
("borges-09","borges","Poetry remembers what history forgets.","La poesia ricorda ciò che la storia dimentica.",A,AI),
("borges-10","borges","The Aleph holds all points.","L'Aleph contiene tutti i punti.",A,AI),
("neruda-01","neruda","I love you without knowing how.","Ti amo senza sapere come.",A,AI),
("neruda-02","neruda","Arise to be born with me, brother.","Sorgi a nascere con me, fratello.",A,AI),
("neruda-03","neruda","Salt of my endless sea.","Sale del mio mare infinito.",A,AI),
("neruda-04","neruda","Isla Negra keeps my shells.","Isla Negra custodisce le mie conchiglie.",A,AI),
("neruda-05","neruda","Odes praise socks and spoons.","Le odi lodano calzini e cucchiai.",A,AI),
("neruda-06","neruda","Love is so short, forgetting so long.","L'amore è così breve, l'oblio così lungo.",A,AI),
("neruda-07","neruda","Machu Picchu speaks through stone.","Machu Picchu parla attraverso la pietra.",A,AI),
("neruda-08","neruda","Confess that I have lived.","Confesso che ho vissuto.",A,AI),
("neruda-09","neruda","Numbers deserve verses too.","Anche i numeri meritano versi.",A,AI),
("neruda-10","neruda","The sea teaches syntax.","Il mare insegna sintassi.",A,AI),
("woolf-01","woolf","A woman must have a room of her own.","Una donna deve avere una stanza tutta per sé.",A,AI),
("woolf-02","woolf","Moments of being pierce the cotton wool.","Gli attimi d'essere trafiggono l'ovatta.",A,AI),
("woolf-03","woolf","Dalloway buys flowers for the day.","Dalloway compra fiori per la giornata.",A,AI),
("woolf-04","woolf","Lighthouse beams guide memory.","I fasci del faro guidano la memoria.",A,AI),
("woolf-05","woolf","Thinking is my fighting.","Pensare è il mio combattere.",A,AI),
("woolf-06","woolf","Bloomsbury debates at tea.","Bloomsbury dibatte al tè.",A,AI),
("woolf-07","woolf","Waves rhythm the mind.","Le onde ritmano la mente.",A,AI),
("woolf-08","woolf","Anon was often a woman.","Anon era spesso una donna.",A,AI),
("woolf-09","woolf","Orlando sleeps through centuries.","Orlando dorme attraverso i secoli.",A,AI),
("woolf-10","woolf","Life is a luminous halo.","La vita è un alone luminoso.",A,AI),
("orwell-01","orwell","Big Brother is watching you.","Il Grande Fratello ti guarda.",A,AI),
("orwell-02","orwell","All animals are equal, some more so.","Tutti gli animali sono uguali, alcuni più degli altri.",A,AI),
("orwell-03","orwell","Who controls the past controls the future.","Chi controlla il passato controlla il futuro.",A,AI),
("orwell-04","orwell","Plain words beat pretty lies.","Le parole semplici battono le belle bugie.",A,AI),
("orwell-05","orwell","Catalonia taught me truth.","La Catalogna mi insegnò la verità.",A,AI),
("orwell-06","orwell","Jura winds write plainly.","I venti di Jura scrivono schietti.",A,AI),
("orwell-07","orwell","Two plus two makes four.","Due più due fa quattro.",A,AI),
("orwell-08","orwell","Journalism prints what hides.","Il giornalismo stampa ciò che si nasconde.",A,AI),
("orwell-09","orwell","Boots stamping forever warn.","Gli stivali che pestano per sempre avvertono.",A,AI),
("orwell-10","orwell","Freedom is saying two plus two.","La libertà è dire due più due.",A,AI),
("sartre-01","sartre","Man is condemned to be free.","L'uomo è condannato a essere libero.",A,AI),
("sartre-02","sartre","Hell is other people.","L'inferno sono gli altri.",A,AI),
("sartre-03","sartre","Existence precedes essence.","L'esistenza precede l'essenza.",A,AI),
("sartre-04","sartre","Nausea reveals the absurd.","La nausea rivela l'assurdo.",A,AI),
("sartre-05","sartre","Cafés philosophize best.","I caffè filosofeggiano meglio.",A,AI),
("sartre-06","sartre","Choose, and choose yourself.","Scegli, e scegli te stesso.",A,AI),
("sartre-07","sartre","Bad faith lies to itself.","La malafede mente a sé stessa.",A,AI),
("sartre-08","sartre","Engage, then write.","Impegnati, poi scrivi.",A,AI),
("sartre-09","sartre","Freedom weighs like stone.","La libertà pesa come pietra.",A,AI),
("sartre-10","sartre","Refuse the prize, keep the thought.","Rifiuta il premio, conserva il pensiero.",A,AI),
("beauvoir-01","beauvoir","One is not born, but becomes a woman.","Donna non si nasce, si diventa.",A,AI),
("beauvoir-02","beauvoir","Change your life today.","Cambia la tua vita oggi.",A,AI),
("beauvoir-03","beauvoir","Freedom needs projects.","La libertà ha bisogno di progetti.",A,AI),
("beauvoir-04","beauvoir","Mandarins debate liberation.","I mandarini dibattono liberazione.",A,AI),
("beauvoir-05","beauvoir","Old age exposes society.","La vecchiaia smaschera la società.",A,AI),
("beauvoir-06","beauvoir","Love must be reciprocal.","L'amore deve essere reciproco.",A,AI),
("beauvoir-07","beauvoir","Write to exist twice.","Scrivi per esistere due volte.",A,AI),
("beauvoir-08","beauvoir","America surprises the philosopher.","L'America sorprende la filosofa.",A,AI),
("beauvoir-09","beauvoir","Ethics precede etiquette.","L'etica precede l'etichetta.",A,AI),
("beauvoir-10","beauvoir","Adieux keep the flame.","Gli addii custodiscono la fiamma.",A,AI),
("gandhi-01","gandhi","Be the change you wish to see.","Sii il cambiamento che vuoi vedere.",A,AI),
("gandhi-02","gandhi","Nonviolence is the greatest force.","La nonviolenza è la forza più grande.",A,AI),
("gandhi-03","gandhi","An eye for an eye blinds the world.","Occhio per occhio acceca il mondo.",A,AI),
("gandhi-04","gandhi","Spin independence daily.","Fila l'indipendenza ogni giorno.",A,AI),
("gandhi-05","gandhi","Truth never damages a just cause.","La verità non danneggia mai una giusta causa.",A,AI),
("gandhi-06","gandhi","Salt marches farther than armies.","La marcia del sale arriva più lontano degli eserciti.",A,AI),
("gandhi-07","gandhi","Live simply, think loftily.","Vivi semplice, pensa in alto.",A,AI),
("gandhi-08","gandhi","Ahimsa begins at the table.","L'ahimsa comincia a tavola.",A,AI),
("gandhi-09","gandhi","Prayer steadies action.","La preghiera rassicura l'azione.",A,AI),
("gandhi-10","gandhi","Satyagraha holds to truth.","Il satyagraha si attiene alla verità.",A,AI),
("mandela-01","mandela","It always seems impossible until done.","Sembra sempre impossibile finché non è fatto.",A,AI),
("mandela-02","mandela","Courage is not absence of fear.","Il coraggio non è assenza di paura.",A,AI),
("mandela-03","mandela","Resentment drinks your own poison.","Il risentimento beve il tuo stesso veleno.",A,AI),
("mandela-04","mandela","Robben Island schooled freedom.","Robben Island istruì la libertà.",A,AI),
("mandela-05","mandela","Forgiveness frees the forgiver.","Il perdono libera chi perdona.",A,AI),
("mandela-06","mandela","Sport unites nations.","Lo sport unisce le nazioni.",A,AI),
("mandela-07","mandela","Education is the great engine.","L'istruzione è il grande motore.",A,AI),
("mandela-08","mandela","Lead from behind, guide forward.","Guida da dietro, conduci avanti.",A,AI),
("mandela-09","mandela","Freedom tastes of responsibility.","La libertà sa di responsabilità.",A,AI),
("mandela-10","mandela","Long walk, steady heart.","Lungo cammino, cuore saldo.",A,AI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchF added={added} total_en={len(en)} total_it={len(it)}")
