"""Batch B: Italian entrepreneurs 2 (15 authors x 10 = 150 quotes)."""
import json

CAT = "italian_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"pirelli": ("Giovanni Battista Pirelli", "Founder · Pirelli", "Fondatore · Pirelli", "1848–1932",
 "Milan engineer who wrapped the world in rubber and speed.",
 "Ingegnere milanese che avvolse il mondo in gomma e velocità."),
"bianchi": ("Edoardo Bianchi", "Founder · Bianchi", "Fondatore · Bianchi", "1865–1946",
 "Milan bicycle maker whose celeste green raced into legend.",
 "Costruttore milanese di biciclette il cui verde celeste corse nella leggenda."),
"pferrero": ("Pietro Ferrero", "Founder · Ferrero", "Fondatore · Ferrero", "1898–1949",
 "Alba pastry chef who invented Giandujot, ancestor of Nutella.",
 "Pasticciere di Alba che inventò il Giandujot, antenato della Nutella."),
"bugatti": ("Ettore Bugatti", "Founder · Bugatti", "Fondatore · Bugatti", "1881–1947",
 "Milan-born creator of the most beautiful racing machines ever built.",
 "Creatore milanese delle più belle macchine da corsa mai costruite."),
"pagani": ("Horacio Pagani", "Founder · Pagani", "Fondatore · Pagani", "1955–",
 "Argentine-Italian sculptor of carbon-fiber hypercars in Modena.",
 "Scultore argentino-italiano di hypercar in fibra di carbonio a Modena."),
"farinetti": ("Oscar Farinetti", "Founder · Eataly", "Fondatore · Eataly", "1954–",
 "Piedmont merchant who turned Italian food into a world market.",
 "Mercante piemontese che trasformò il cibo italiano in mercato mondiale."),
"wferragamo": ("Wanda Ferragamo", "Leader · Ferragamo", "Guida · Ferragamo", "1921–2018",
 "Matriarch who grew a shoe atelier into a global maison.",
 "Matriarca che fece crescere un atelier di scarpe fino a maison globale."),
"biagiotti": ("Laura Biagiotti", "Designer · Biagiotti", "Stilista · Biagiotti", "1943–2017",
 "Queen of cashmere who dressed Rome in softness.",
 "Regina del cashmere che vestì Roma di morbidezza."),
"missoni": ("Ottavio Missoni", "Co-founder · Missoni", "Co-fondatore · Missoni", "1921–2013",
 "Athlete turned knitter whose zigzags colored the world.",
 "Atleta diventato magliaio i cui zigzag colorarono il mondo."),
"pucci": ("Emilio Pucci", "Founder · Pucci", "Fondatore · Pucci", "1914–1992",
 "Florentine prince of prints who dressed the jet set.",
 "Principe fiorentino delle stampe che vestì il jet set."),
"cavalli": ("Roberto Cavalli", "Founder · Cavalli", "Fondatore · Cavalli", "1940–2024",
 "Florentine animalier who printed the wild on silk.",
 "Animalier fiorentino che stampò il selvaggio sulla seta."),
"ferre": ("Gianfranco Ferré", "Designer · Ferré", "Stilista · Ferré", "1944–2007",
 "Architect of fashion who built shirts like monuments.",
 "Architetto della moda che costruiva camicie come monumenti."),
"gaggia": ("Achille Gaggia", "Inventor · Espresso", "Inventore · Espresso", "1895–1961",
 "Milan café owner whose lever gave espresso its crema.",
 "Caffettiere milanese la cui leva diede all'espresso la sua crema."),
"eilly": ("Ernesto Illy", "Scientist · illycaffè", "Scienziato · illycaffè", "1925–2008",
 "Trieste chemist who made espresso a science of quality.",
 "Chimico triestino che fece dell'espresso una scienza della qualità."),
"marotta": ("Enrico Piaggio", "Industrialist · Vespa", "Industriale · Vespa", "1905–1965",
 "Industrialist who put Italy on two wheels with the Vespa.",
 "Industriale che mise l'Italia su due ruote con la Vespa."),
}
Q = [
("pirelli-01","pirelli","Durability wins every race.","La durata vince ogni gara.",C,CI),
("pirelli-02","pirelli","Grip the road, respect the curve.","Afferra la strada, rispetta la curva.",C,CI),
("pirelli-03","pirelli","Power is nothing without control.","La potenza è nulla senza controllo.",C,CI),
("pirelli-04","pirelli","Engineer with passion, test with courage.","Progetta con passione, testa con coraggio.",S,SI),
("pirelli-05","pirelli","Milan works, the world rolls.","Milano lavora, il mondo rotola.",A,AI),
("pirelli-06","pirelli","Innovation must survive the road.","L'innovazione deve sopravvivere alla strada.",C,CI),
("pirelli-07","pirelli","Long races reward patience.","Le lunghe gare premiano la pazienza.",S,SI),
("pirelli-08","pirelli","Rubber, steel, and obstinacy.","Gomma, acciaio e ostinazione.",A,AI),
("pirelli-09","pirelli","Invest in research, harvest in decades.","Investi in ricerca, raccogli in decenni.",S,SI),
("pirelli-10","pirelli","Speed means nothing without safety.","La velocità non significa nulla senza sicurezza.",C,CI),
("bianchi-01","bianchi","Two wheels, infinite freedom.","Due ruote, libertà infinita.",A,AI),
("bianchi-02","bianchi","Celeste is not a color. It is a promise.","Il celeste non è un colore. È una promessa.",A,AI),
("bianchi-03","bianchi","Build frames light, build riders strong.","Costruisci telai leggeri, corridori forti.",C,CI),
("bianchi-04","bianchi","Every climb teaches humility.","Ogni salita insegna umiltà.",S,SI),
("bianchi-05","bianchi","The workshop is a temple of precision.","L'officina è un tempio di precisione.",C,CI),
("bianchi-06","bianchi","Race on Sunday, improve on Monday.","Corri la domenica, migliora il lunedì.",S,SI),
("bianchi-07","bianchi","Steel sings when welded with care.","L'acciaio canta quando saldato con cura.",A,AI),
("bianchi-08","bianchi","Tradition pedals forward.","La tradizione pedala in avanti.",S,SI),
("bianchi-09","bianchi","Victories are built in winter.","Le vittorie si costruiscono d'inverno.",A,AI),
("bianchi-10","bianchi","A bicycle is freedom with gears.","La bicicletta è libertà con il cambio.",A,AI),
("pferrero-01","pferrero","Sweeten hard times.","Addolcisci i tempi duri.",A,AI),
("pferrero-02","pferrero","Hazelnuts and courage built us.","Nocciole e coraggio ci hanno costruito.",S,SI),
("pferrero-03","pferrero","Invent with what the land gives.","Inventa con ciò che la terra dona.",A,AI),
("pferrero-04","pferrero","A small pastry shop can dream big.","Una piccola pasticceria può sognare in grande.",S,SI),
("pferrero-05","pferrero","War taught us to create with less.","La guerra ci insegnò a creare con meno.",S,SI),
("pferrero-06","pferrero","Taste is truth.","Il gusto è verità.",A,AI),
("pferrero-07","pferrero","Work beside your family, sweeten the town.","Lavora accanto alla famiglia, addolcisci il paese.",S,SI),
("pferrero-08","pferrero","Every jar holds Alba's hills.","Ogni vasetto custodisce le colline di Alba.",A,AI),
("pferrero-09","pferrero","Frugality feeds imagination.","La frugalità nutre l'immaginazione.",A,AI),
("pferrero-10","pferrero","Begin sweet, stay honest.","Comincia dolce, resta onesto.",A,AI),
("bugatti-01","bugatti","If it is beautiful, it will go fast.","Se è bella, andrà veloce.",A,AI),
("bugatti-02","bugatti","Nothing is too beautiful, nothing too expensive.","Niente è troppo bello, niente troppo costoso.",A,AI),
("bugatti-03","bugatti","Engineering is art with pistons.","L'ingegneria è arte con i pistoni.",S,SI),
("bugatti-04","bugatti","Weight is the enemy, grace the ally.","Il peso è nemico, la grazia alleata.",A,AI),
("bugatti-05","bugatti","Build few, build unforgettable.","Costruisci poche, indimenticabili.",S,SI),
("bugatti-06","bugatti","The engine must sing.","Il motore deve cantare.",A,AI),
("bugatti-07","bugatti","Perfection has a red horseshoe.","La perfezione ha un ferro rosso.",A,AI),
("bugatti-08","bugatti","Race to prove beauty.","Corri per dimostrare la bellezza.",S,SI),
("bugatti-09","bugatti","Details at 300 an hour.","Dettagli a 300 all'ora.",A,AI),
("bugatti-10","bugatti","A car should thrill standing still.","Un'auto deve emozionare anche da ferma.",A,AI),
("pagani-01","pagani","A car must be art in motion.","Un'auto deve essere arte in movimento.",S,SI),
("pagani-02","pagani","Carbon fiber has a soul if shaped with love.","La fibra di carbonio ha un'anima se plasmata con amore.",S,SI),
("pagani-03","pagani","Obsess over the invisible bolt.","Ossessionati per il bullone invisibile.",C,CI),
("pagani-04","pagani","Modena taught me beauty is engineering.","Modena mi ha insegnato che la bellezza è ingegneria.",S,SI),
("pagani-05","pagani","Build slow, deliver eternity.","Costruisci piano, consegna eternità.",C,CI),
("pagani-06","pagani","Wind is a co-designer.","Il vento è un co-designer.",S,SI),
("pagani-07","pagani","Every gram must earn its place.","Ogni grammo deve meritarsi il suo posto.",C,CI),
("pagani-08","pagani","Dreamed in Argentina, built in Italy.","Sognata in Argentina, costruita in Italia.",S,SI),
("pagani-09","pagani","Exclusivity serves obsession.","L'esclusività serve l'ossessione.",A,AI),
("pagani-10","pagani","The atelier beats the assembly line.","L'atelier batte la catena di montaggio.",C,CI),
("farinetti-01","farinetti","Eat well, live better.","Mangia bene, vivi meglio.",C,CI),
("farinetti-02","farinetti","Tell the story behind every product.","Racconta la storia dietro ogni prodotto.",S,SI),
("farinetti-03","farinetti","Biodiversity is delicious.","La biodiversità è deliziosa.",S,SI),
("farinetti-04","farinetti","Pay producers right, eat like kings.","Paga bene i produttori, mangia da re.",C,CI),
("farinetti-05","farinetti","A market can be a museum of taste.","Un mercato può essere un museo del gusto.",S,SI),
("farinetti-06","farinetti","Optimism is seasoned daily.","L'ottimismo si condisce ogni giorno.",A,AI),
("farinetti-07","farinetti","Slow food, fast smiles.","Cibo lento, sorrisi veloci.",A,AI),
("farinetti-08","farinetti","Italy on a plate, world at the table.","L'Italia nel piatto, il mondo a tavola.",S,SI),
("farinetti-09","farinetti","Study, taste, repeat.","Studia, assaggia, ripeti.",C,CI),
("farinetti-10","farinetti","Memory is the best ingredient.","La memoria è il miglior ingrediente.",S,SI),
("wferragamo-01","wferragamo","Grow gently, grow strong.","Cresci con garbo, cresci forte.",S,SI),
("wferragamo-02","wferragamo","Family holds the maison together.","La famiglia tiene insieme la maison.",S,SI),
("wferragamo-03","wferragamo","Prudence is also courage.","Anche la prudenza è coraggio.",A,AI),
("wferragamo-04","wferragamo","Florence rewards patience.","Firenze premia la pazienza.",S,SI),
("wferragamo-05","wferragamo","Protect the name, share the work.","Proteggi il nome, condividi il lavoro.",C,CI),
("wferragamo-06","wferragamo","Elegance needs steady hands.","L'eleganza ha bisogno di mani salde.",A,AI),
("wferragamo-07","wferragamo","Listen to artisans first.","Ascolta prima gli artigiani.",C,CI),
("wferragamo-08","wferragamo","Legacy is daily care.","L'eredità è cura quotidiana.",S,SI),
("wferragamo-09","wferragamo","Kindness scales.","La gentilezza fa scala.",A,AI),
("wferragamo-10","wferragamo","Walk far, step soft.","Cammina lontano, passo morbido.",A,AI),
("biagiotti-01","biagiotti","Cashmere is a caress you wear.","Il cashmere è una carezza che indossi.",S,SI),
("biagiotti-02","biagiotti","Softness is strength.","La morbidezza è forza.",A,AI),
("biagiotti-03","biagiotti","Rome dresses in white and dreams.","Roma si veste di bianco e sogna.",S,SI),
("biagiotti-04","biagiotti","Knit patience into every thread.","Intreccia pazienza in ogni filo.",C,CI),
("biagiotti-05","biagiotti","Femininity without fragility.","Femminilità senza fragilità.",A,AI),
("biagiotti-06","biagiotti","White means courage.","Il bianco significa coraggio.",S,SI),
("biagiotti-07","biagiotti","Comfort dignifies women.","La comodità dà dignità alle donne.",S,SI),
("biagiotti-08","biagiotti","Family ateliers last.","Gli atelier di famiglia durano.",C,CI),
("biagiotti-09","biagiotti","Never shout in cashmere.","Mai gridare in cashmere.",A,AI),
("biagiotti-10","biagiotti","Tenderness tailors well.","La tenerezza cuce bene.",A,AI),
("missoni-01","missoni","Color is joy made wearable.","Il colore è gioia da indossare.",S,SI),
("missoni-02","missoni","Zigzag forward, never straight back.","Zigzag in avanti, mai dritti indietro.",A,AI),
("missoni-03","missoni","Knit optimism daily.","Lavora a maglia ottimismo ogni giorno.",S,SI),
("missoni-04","missoni","Sport taught me rhythm and stripes.","Lo sport mi insegnò ritmo e righe.",S,SI),
("missoni-05","missoni","Put poetry on shoulders.","Metti poesia sulle spalle.",A,AI),
("missoni-06","missoni","Mistakes in yarn become patterns.","Gli errori nel filo diventano motivi.",A,AI),
("missoni-07","missoni","Family looms weave futures.","I telai di famiglia tessono futuri.",C,CI),
("missoni-08","missoni","Brighten grey days.","Illumina i giorni grigi.",S,SI),
("missoni-09","missoni","Craft is marathon, not sprint.","L'artigianato è maratona, non sprint.",A,AI),
("missoni-10","missoni","Wear happiness.","Indossa la felicità.",A,AI),
("pucci-01","pucci","Prints are sunshine you can fold.","Le stampe sono sole che puoi piegare.",S,SI),
("pucci-02","pucci","Dress movement, not stiffness.","Vesti il movimento, non la rigidità.",S,SI),
("pucci-03","pucci","Capri taught me freedom in color.","Capri mi insegnò libertà nel colore.",S,SI),
("pucci-04","pucci","Light fabrics, light spirit.","Tessuti leggeri, spirito leggero.",C,CI),
("pucci-05","pucci","Travel elegantly.","Viaggia con eleganza.",A,AI),
("pucci-06","pucci","A scarf can change a destiny.","Un foulard può cambiare un destino.",A,AI),
("pucci-07","pucci","Geometry dances.","La geometria danza.",A,AI),
("pucci-08","pucci","Jet set with a smile.","Jet set con il sorriso.",S,SI),
("pucci-09","pucci","Color cures grey.","Il colore cura il grigio.",A,AI),
("pucci-10","pucci","Palazzo style, seaside soul.","Stile da palazzo, anima di mare.",A,AI),
("cavalli-01","cavalli","The wild belongs on silk.","Il selvaggio appartiene alla seta.",S,SI),
("cavalli-02","cavalli","Dare, print, roar.","Osa, stampa, ruggisci.",A,AI),
("cavalli-03","cavalli","Sensuality is confidence.","La sensualità è sicurezza.",S,SI),
("cavalli-04","cavalli","Florence dares brightest.","Firenze osa più luminosa.",A,AI),
("cavalli-05","cavalli","Denim can be couture.","Il denim può essere couture.",S,SI),
("cavalli-06","cavalli","Excess, tailored.","Eccesso, su misura.",A,AI),
("cavalli-07","cavalli","Night deserves drama.","La notte merita dramma.",A,AI),
("cavalli-08","cavalli","Animal soul, artisan hands.","Anima animale, mani artigiane.",S,SI),
("cavalli-09","cavalli","Seduce with joy.","Seduci con gioia.",A,AI),
("cavalli-10","cavalli","Never beige.","Mai beige.",A,AI),
("ferre-01","ferre","A shirt is architecture.","Una camicia è architettura.",S,SI),
("ferre-02","ferre","Structure liberates.","La struttura libera.",A,AI),
("ferre-03","ferre","White shirt, strong mind.","Camicia bianca, mente forte.",S,SI),
("ferre-04","ferre","Precision is passion.","La precisione è passione.",C,CI),
("ferre-05","ferre","Build volumes, honor bodies.","Costruisci volumi, onora i corpi.",S,SI),
("ferre-06","ferre","Rigor can be romantic.","Il rigore può essere romantico.",A,AI),
("ferre-07","ferre","Draw first, cut later.","Disegna prima, taglia dopo.",C,CI),
("ferre-08","ferre","Milano rewards the prepared.","Milano premia i preparati.",S,SI),
("ferre-09","ferre","Geometry flatters.","La geometria dona.",A,AI),
("ferre-10","ferre","An architect never stops building.","Un architetto non smette mai di costruire.",S,SI),
("gaggia-01","gaggia","Crema crowns patience.","La crema corona la pazienza.",C,CI),
("gaggia-02","gaggia","Pressure reveals character.","La pressione rivela il carattere.",A,AI),
("gaggia-03","gaggia","A lever changed mornings forever.","Una leva cambiò per sempre le mattine.",S,SI),
("gaggia-04","gaggia","Espresso in seconds, ritual for life.","Espresso in secondi, rito per la vita.",C,CI),
("gaggia-05","gaggia","Invent for the bar, serve the piazza.","Inventa per il bar, servi la piazza.",S,SI),
("gaggia-06","gaggia","Small cup, big engineering.","Tazzina piccola, grande ingegneria.",A,AI),
("gaggia-07","gaggia","Foam is the signature.","La schiuma è la firma.",C,CI),
("gaggia-08","gaggia","Speed without losing soul.","Velocità senza perdere l'anima.",S,SI),
("gaggia-09","gaggia","Every bar deserves excellence.","Ogni bar merita eccellenza.",C,CI),
("gaggia-10","gaggia","Morning starts at the lever.","Il mattino parte dalla leva.",A,AI),
("eilly-01","eilly","Measure everything, taste always.","Misura tutto, assaggia sempre.",C,CI),
("eilly-02","eilly","Chemistry serves pleasure.","La chimica serve il piacere.",S,SI),
("eilly-03","eilly","Pressurize with precision.","Pressurizza con precisione.",C,CI),
("eilly-04","eilly","Science guards aroma.","La scienza custodisce l'aroma.",C,CI),
("eilly-05","eilly","Teach coffee, learn humility.","Insegna il caffè, impara l'umiltà.",S,SI),
("eilly-06","eilly","Laboratories brew dreams.","I laboratori preparano sogni.",A,AI),
("eilly-07","eilly","Quality can be quantified.","La qualità si può misurare.",C,CI),
("eilly-08","eilly","Share knowledge with growers.","Condividi sapere con i coltivatori.",S,SI),
("eilly-09","eilly","Curiosity percolates.","La curiosità percola.",A,AI),
("eilly-10","eilly","Research never sleeps.","La ricerca non dorme mai.",S,SI),
]

# fix last author: Enrico Piaggio (Vespa)
AUTHORS["marotta"] = ("Enrico Piaggio", "Industrialist · Vespa", "Industriale · Vespa", "1905–1965",
 "Industrialist who put Italy on two wheels with the Vespa.",
 "Industriale che mise l'Italia su due ruote con la Vespa.")
Q.extend([
("marotta-01","marotta","Put Italy on two wheels.","Metti l'Italia su due ruote.",S,SI),
("marotta-02","marotta","Freedom has a wasp's buzz.","La libertà ha il ronzio di una vespa.",A,AI),
("marotta-03","marotta","Rebuild with lightness.","Ricostruisci con leggerezza.",S,SI),
("marotta-04","marotta","A scooter carries a generation.","Uno scooter porta una generazione.",A,AI),
("marotta-05","marotta","Utility can be beautiful.","L'utile può essere bello.",C,CI),
("marotta-06","marotta","Youth moves first.","I giovani si muovono per primi.",A,AI),
("marotta-07","marotta","Design for the piazza.","Disegna per la piazza.",C,CI),
("marotta-08","marotta","Small engine, big dream.","Piccolo motore, grande sogno.",A,AI),
("marotta-09","marotta","Mobility is democracy.","La mobilità è democrazia.",S,SI),
("marotta-10","marotta","Buzz far, buzz free.","Ronza lontano, ronza libero.",A,AI),
])

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchB added={added} total_en={len(en)} total_it={len(it)}")
