"""Batch C: international entrepreneurs 1 (17 authors x 10 = 170 quotes)."""
import json

CAT = "international_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"ford": ("Henry Ford", "Founder · Ford", "Fondatore · Ford", "1863–1947",
 "Detroit maker who put the world on wheels with the Model T.",
 "Costruttore di Detroit che mise il mondo su ruote con il Modello T."),
"edison": ("Thomas Edison", "Inventor · Menlo Park", "Inventore · Menlo Park", "1847–1931",
 "Prolific inventor of the light bulb, phonograph and research lab.",
 "Prolifico inventore di lampadina, fonografo e laboratorio di ricerca."),
"carnegie": ("Andrew Carnegie", "Industrialist · Steel", "Industriale · Acciaio", "1835–1919",
 "Steel magnate turned libraries-and-peace philanthropist.",
 "Magnate dell'acciaio diventato filantropo di biblioteche e pace."),
"lauder": ("Estée Lauder", "Founder · Estée Lauder", "Fondatrice · Estée Lauder", "1908–2004",
 "Cream seller who built a beauty empire on touch and promise.",
 "Venditrice di creme che costruì un impero di bellezza su tatto e promessa."),
"walton": ("Sam Walton", "Founder · Walmart", "Fondatore · Walmart", "1918–1992",
 "Arkansas retailer who made everyday low prices a creed.",
 "Commerciante dell'Arkansas che fece dei prezzi bassi un credo."),
"kroc": ("Ray Kroc", "Builder · McDonald's", "Costruttore · McDonald's", "1902–1984",
 "Milkshake-mixer salesman who franchised speed and consistency.",
 "Venditore di frullatori che rese in franchising velocità e costanza."),
"gates": ("Bill Gates", "Co-founder · Microsoft", "Co-fondatore · Microsoft", "1955–",
 "Software pioneer turned global health philanthropist.",
 "Pioniere del software diventato filantropo della salute globale."),
"buffett": ("Warren Buffett", "Investor · Berkshire", "Investitore · Berkshire", "1930–",
 "Omaha oracle of patience, value and cherry Coke.",
 "Oracolo di Omaha di pazienza, valore e cherry Coke."),
"bezos": ("Jeff Bezos", "Founder · Amazon", "Fondatore · Amazon", "1964–",
 "Bookseller turned cloud-and-space builder, obsessed with customers.",
 "Libraio diventato costruttore di cloud e spazio, ossessionato dai clienti."),
"musk": ("Elon Musk", "Founder · SpaceX, Tesla", "Fondatore · SpaceX, Tesla", "1971–",
 "Engineer of rockets and electric roads, betting on Mars.",
 "Ingegnere di razzi e strade elettriche, scommette su Marte."),
"oprah": ("Oprah Winfrey", "Founder · OWN", "Fondatrice · OWN", "1954–",
 "Talk host who turned empathy into a media empire.",
 "Conduttrice che trasformò l'empatia in impero mediatico."),
"branson": ("Richard Branson", "Founder · Virgin", "Fondatore · Virgin", "1950–",
 "British adventurer branding records, planes and space.",
 "Avventuriero britannico di dischi, aerei e spazio."),
"dell": ("Michael Dell", "Founder · Dell", "Fondatore · Dell", "1965–",
 "Dorm-room assembler who sold computers direct to the world.",
 "Assemblatore da dormitorio che vendette computer diretti al mondo."),
"knight": ("Phil Knight", "Co-founder · Nike", "Co-fondatore · Nike", "1938–",
 "Runner who sold shoes from a trunk and built Just Do It.",
 "Corridore che vendeva scarpe dal bagagliaio e costruì Just Do It."),
"schultz": ("Howard Schultz", "Builder · Starbucks", "Costruttore · Starbucks", "1953–",
 "Brooklyn dreamer who made espresso a third place.",
 "Sognatore di Brooklyn che fece dell'espresso un terzo luogo."),
"blakely": ("Sara Blakely", "Founder · Spanx", "Fondatrice · Spanx", "1971–",
 "Fax seller who cut the feet off pantyhose and built billions.",
 "Venditrice di fax che tagliò i piedi ai collant e costruì miliardi."),
"jackma": ("Jack Ma", "Co-founder · Alibaba", "Co-fondatore · Alibaba", "1964–",
 "English teacher who built China's e-commerce giant.",
 "Insegnante d'inglese che costruì il gigante cinese dell'e-commerce."),
}

Q = [
("ford-01","ford","Whether you think you can or you can't, you're right.","Che tu creda di poterlo fare o no, avrai ragione.",A,AI),
("ford-02","ford","Failure is the chance to begin again more intelligently.","Il fallimento è l'occasione per ricominciare con più intelligenza.",A,AI),
("ford-03","ford","Coming together is a beginning; keeping together is progress.","Mettersi insieme è un inizio; restare insieme è progresso.",A,AI),
("ford-04","ford","Quality means doing it right when no one is looking.","La qualità è fare bene anche quando nessuno guarda.",A,AI),
("ford-05","ford","Pay workers well and they become customers.","Paga bene gli operai e diventeranno clienti.",S,SI),
("ford-06","ford","Obstacles are frightful things seen sideways.","Gli ostacoli sono cose spaventose viste di lato.",A,AI),
("ford-07","ford","Thinking is the hardest work there is.","Pensare è il lavoro più difficile che ci sia.",A,AI),
("ford-08","ford","Make the car affordable, and freedom follows.","Rendi l'auto accessibile e la libertà segue.",S,SI),
("ford-09","ford","Enthusiasm is the yeast that raises the dough.","L'entusiasmo è il lievito che fa lievitare.",A,AI),
("ford-10","ford","The machine must serve the many, not the few.","La macchina deve servire i molti, non i pochi.",S,SI),
("edison-01","edison","Genius is one percent inspiration, ninety-nine perspiration.","Il genio è 1% ispirazione e 99% sudore.",A,AI),
("edison-02","edison","I have not failed. I found ten thousand ways that won't work.","Non ho fallito. Ho trovato diecimila modi che non funzionano.",A,AI),
("edison-03","edison","Opportunity is missed because it wears overalls.","Le occasioni si perdono perché vestono da lavoro.",A,AI),
("edison-04","edison","Our greatest weakness lies in giving up.","La nostra più grande debolezza è arrenderci.",A,AI),
("edison-05","edison","To invent, you need a good imagination and junk.","Per inventare servono immaginazione e cianfrusaglie.",A,AI),
("edison-06","edison","Restlessness is discontent, the first necessity of progress.","L'inquietudine è la prima necessità del progresso.",A,AI),
("edison-07","edison","The lab never sleeps when curiosity is awake.","Il laboratorio non dorme quando la curiosità è sveglia.",A,AI),
("edison-08","edison","Show me results, not excuses.","Mostrami risultati, non scuse.",A,AI),
("edison-09","edison","Ideas without execution are hallucinations.","Le idee senza esecuzione sono allucinazioni.",A,AI),
("edison-10","edison","Work keeps genius honest.","Il lavoro tiene onesto il genio.",A,AI),
("carnegie-01","carnegie","Do your duty and a little more.","Fai il tuo dovere e qualcosa in più.",A,AI),
("carnegie-02","carnegie","No man becomes rich unless he enriches others.","Nessuno si arricchisce senza arricchire gli altri.",A,AI),
("carnegie-03","carnegie","Teamwork divides the task and multiplies success.","Il lavoro di squadra divide il compito e moltiplica il successo.",A,AI),
("carnegie-04","carnegie","Aim for the highest.","Punta al massimo.",A,AI),
("carnegie-05","carnegie","Surplus wealth is a trust for the public.","La ricchezza in eccedenza è un mandato per il pubblico.",A,AI),
("carnegie-06","carnegie","Libraries outlast steel.","Le biblioteche durano più dell'acciaio.",A,AI),
("carnegie-07","carnegie","Concentration is the secret of strength.","La concentrazione è il segreto della forza.",A,AI),
("carnegie-08","carnegie","Put all good eggs in one basket, then watch it.","Metti tutte le buone uova in un cesto, poi sorveglialo.",A,AI),
("carnegie-09","carnegie","The man who dies rich dies disgraced.","Chi muore ricco muore disonorato.",A,AI),
("carnegie-10","carnegie","Success comes from honest labor.","Il successo nasce dal lavoro onesto.",A,AI),
("lauder-01","lauder","Touch the customer and teach her gently.","Tocca la cliente e insegnale con garbo.",S,SI),
("lauder-02","lauder","I never dreamed about success. I worked for it.","Non ho mai sognato il successo. Ci ho lavorato.",A,AI),
("lauder-03","lauder","Give every woman a free gift of hope.","Regala a ogni donna un omaggio di speranza.",S,SI),
("lauder-04","lauder","Quality creams sell themselves.","Le creme di qualità si vendono da sole.",C,CI),
("lauder-05","lauder","Telephone, telegraph, tell a woman.","Telefono, telegrafo, dillo a una donna.",A,AI),
("lauder-06","lauder","Listen, then formulate.","Ascolta, poi formula.",C,CI),
("lauder-07","lauder","Prestige is consistency in a jar.","Il prestigio è costanza in un vasetto.",C,CI),
("lauder-08","lauder","Never stop sampling.","Non smettere mai di far provare.",S,SI),
("lauder-09","lauder","Beauty is an attitude of care.","La bellezza è un atteggiamento di cura.",A,AI),
("lauder-10","lauder","Dream creams, deliver results.","Sogna creme, consegna risultati.",A,AI),
("walton-01","walton","Appreciate your people and they will soar.","Apprezza la tua gente e volerà.",A,AI),
("walton-02","walton","Listen to front-line workers.","Ascolta chi lavora in prima linea.",S,SI),
("walton-03","walton","High expectations are the key to everything.","Le grandi aspettative sono la chiave di tutto.",A,AI),
("walton-04","walton","Save the customer money every day.","Fai risparmiare il cliente ogni giorno.",C,CI),
("walton-05","walton","Swim upstream against convention.","Nuota controcorrente rispetto alle convenzioni.",S,SI),
("walton-06","walton","Exceed expectations, one cart at a time.","Supera le aspettative, un carrello alla volta.",C,CI),
("walton-07","walton","Share profits with partners.","Condividi i profitti con i soci.",S,SI),
("walton-08","walton","Stay humble in Bentonville.","Resta umile a Bentonville.",A,AI),
("walton-09","walton","Small towns deserve low prices.","Le piccole città meritano prezzi bassi.",S,SI),
("walton-10","walton","Work harder than competitors, grin wider.","Lavora più dei concorrenti, sorridi di più.",A,AI),
("kroc-01","kroc","Luck favors the persistent french-fryer.","La fortuna aiuta il friggitore tenace.",A,AI),
("kroc-02","kroc","Quality, service, cleanliness, value.","Qualità, servizio, pulizia, valore.",C,CI),
("kroc-03","kroc","No buyer is too small for attention.","Nessun cliente è troppo piccolo per l'attenzione.",S,SI),
("kroc-04","kroc","Press on; nothing beats persistence.","Insisti; niente batte la tenacia.",A,AI),
("kroc-05","kroc","The fries must be identical in Tokyo and Ohio.","Le patatine devono essere identiche a Tokyo e in Ohio.",C,CI),
("kroc-06","kroc","Hire the smile, train the skill.","Assumi il sorriso, allena la capacità.",A,AI),
("kroc-07","kroc","Speed with a smile.","Velocità con il sorriso.",C,CI),
("kroc-08","kroc","Foundations first, arches later.","Prima le fondamenta, poi gli archi.",S,SI),
("kroc-09","kroc","Take calculated bites.","Mordi con calcolo.",A,AI),
("kroc-10","kroc","Green lights mean go worldwide.","Il verde significa via in tutto il mondo.",A,AI),
("gates-01","gates","Your most unhappy customers are your greatest teachers.","I clienti più scontenti sono i tuoi migliori maestri.",A,AI),
("gates-02","gates","Success is a lousy teacher.","Il successo è un pessimo maestro.",A,AI),
("gates-03","gates","Patience with people, impatience with problems.","Pazienza con le persone, impazienza con i problemi.",S,SI),
("gates-04","gates","Software magnifies human will.","Il software amplifica la volontà umana.",S,SI),
("gates-05","gates","Measure malaria, then beat it.","Misura la malaria, poi sconfiggila.",S,SI),
("gates-06","gates","Read widely, think deeply.","Leggi molto, pensa in profondità.",S,SI),
("gates-07","gates","A PC on every desk was only the start.","Un PC su ogni scrivania era solo l'inizio.",S,SI),
("gates-08","gates","Optimism needs a plan.","L'ottimismo ha bisogno di un piano.",S,SI),
("gates-09","gates","Give smart, give big.","Dona con intelligenza, dona in grande.",S,SI),
("gates-10","gates","Curiosity compounds like interest.","La curiosità rende come l'interesse composto.",A,AI),
("buffett-01","buffett","Price is what you pay. Value is what you get.","Il prezzo è ciò che paghi. Il valore è ciò che ottieni.",A,AI),
("buffett-02","buffett","Be fearful when others are greedy.","Abbi paura quando gli altri sono avidi.",A,AI),
("buffett-03","buffett","Our favorite holding period is forever.","Il nostro periodo preferito di detenzione è per sempre.",A,AI),
("buffett-04","buffett","Risk comes from not knowing.","Il rischio nasce dal non sapere.",A,AI),
("buffett-05","buffett","Someone sits in shade because someone planted.","Qualcuno siede all'ombra perché qualcuno ha piantato.",A,AI),
("buffett-06","buffett","Reputation takes twenty years to build.","La reputazione richiede vent'anni per costruirsi.",A,AI),
("buffett-07","buffett","Never invest in what you don't understand.","Non investire mai in ciò che non capisci.",A,AI),
("buffett-08","buffett","Patience beats prediction.","La pazienza batte la previsione.",A,AI),
("buffett-09","buffett","Honesty is a very expensive gift.","L'onestà è un dono costosissimo.",A,AI),
("buffett-10","buffett","Eat like a six-year-old, invest like a sage.","Mangia come un bambino, investi come un saggio.",A,AI),
("bezos-01","bezos","Start with the customer and work backwards.","Parti dal cliente e procedi a ritroso.",S,SI),
("bezos-02","bezos","Day 1 energy, every day.","Energia da primo giorno, ogni giorno.",S,SI),
("bezos-03","bezos","Invention requires wandering.","L'invenzione richiede vagabondaggio.",S,SI),
("bezos-04","bezos","Long-term thinking beats quarterly panic.","Il pensiero di lungo periodo batte il panico trimestrale.",S,SI),
("bezos-05","bezos","Work hard, have fun, make history.","Lavora sodo, divertiti, fai la storia.",C,CI),
("bezos-06","bezos","If you're not stubborn, you'll give up too soon.","Se non sei testardo, mollerai troppo presto.",S,SI),
("bezos-07","bezos","High standards are teachable.","Gli standard alti si insegnano.",S,SI),
("bezos-08","bezos","Boring logistics enable magic.","La logistica noiosa rende possibile la magia.",C,CI),
("bezos-09","bezos","Regret minimalization guides big bets.","La minimizzazione del rimpianto guida le grandi scommesse.",S,SI),
("bezos-10","bezos","Build the road to space.","Costruisci la strada per lo spazio.",S,SI),
("musk-01","musk","When something matters, do it anyway.","Quando qualcosa conta, falla comunque.",S,SI),
("musk-02","musk","Failure is an option here.","Qui il fallimento è contemplato.",S,SI),
("musk-03","musk","Question every requirement, delete fearlessly.","Metti in dubbio ogni requisito, elimina senza paura.",S,SI),
("musk-04","musk","Physics first, opinions later.","Prima la fisica, poi le opinioni.",S,SI),
("musk-05","musk","Burnout? Work on what electrifies you.","Burnout? Lavora su ciò che ti elettrizza.",A,AI),
("musk-06","musk","Make life multiplanetary.","Rendi la vita multiplanetaria.",S,SI),
("musk-07","musk","Cost is a design flaw.","Il costo è un difetto di progettazione.",S,SI),
("musk-08","musk","Prototype fast, iterate faster.","Prototipa in fretta, itera più in fretta.",S,SI),
("musk-09","musk","Talent stacks beat solo genius.","Le squadre di talenti battono il genio solitario.",A,AI),
("musk-10","musk","Sustainable energy is non-negotiable.","L'energia sostenibile non è negoziabile.",S,SI),
("oprah-01","oprah","Turn your wounds into wisdom.","Trasforma le ferite in saggezza.",S,SI),
("oprah-02","oprah","You get in life what you have the courage to ask for.","Ottieni ciò che hai il coraggio di chiedere.",S,SI),
("oprah-03","oprah","Gratitude unlocks abundance.","La gratitudine sblocca l'abbondanza.",S,SI),
("oprah-04","oprah","Listen with the heart first.","Ascolta prima con il cuore.",S,SI),
("oprah-05","oprah","Purpose turns pain into power.","Lo scopo trasforma il dolore in potere.",S,SI),
("oprah-06","oprah","Do the next right thing.","Fai la prossima cosa giusta.",S,SI),
("oprah-07","oprah","Surround yourself with risers.","Circondati di chi ti solleva.",S,SI),
("oprah-08","oprah","Own your story.","Possiedi la tua storia.",S,SI),
("oprah-09","oprah","Generosity returns with interest.","La generosità ritorna con gli interessi.",A,AI),
("oprah-10","oprah","Breathe, begin, become.","Respira, comincia, diventa.",S,SI),
("branson-01","branson","Screw it, let's do it.","Al diavolo, facciamolo.",A,AI),
("branson-02","branson","Business is about people first.","Il business riguarda prima le persone.",S,SI),
("branson-03","branson","Have fun or don't do it.","Divertiti o non farlo.",A,AI),
("branson-04","branson","Train people to leave, treat them to stay.","Forma le persone per partire, trattale per restare.",A,AI),
("branson-05","branson","Brave brands listen.","I marchi coraggiosi ascoltano.",S,SI),
("branson-06","branson","Adventure is good business.","L'avventura è buon business.",S,SI),
("branson-07","branson","Protect reefs and rockets alike.","Proteggi barriere coralline e razzi allo stesso modo.",S,SI),
("branson-08","branson","Delegate and trust.","Delega e fidati.",S,SI),
("branson-09","branson","Say yes, learn fast.","Dì sì, impara in fretta.",A,AI),
("branson-10","branson","Balloon over obstacles.","In mongolfiera sopra gli ostacoli.",A,AI),
("dell-01","dell","Sell direct, listen direct.","Vendi diretto, ascolta diretto.",S,SI),
("dell-02","dell","Ignore the crowd, serve the user.","Ignora la folla, servi l'utente.",S,SI),
("dell-03","dell","Inventory is waste in disguise.","Il magazzino è spreco travestito.",C,CI),
("dell-04","dell","Start in a dorm, think worldwide.","Comincia in un dormitorio, pensa mondiale.",S,SI),
("dell-05","dell","Speed of learning beats size.","La velocità di apprendimento batte la taglia.",A,AI),
("dell-06","dell","Customers configure, we deliver.","I clienti configurano, noi consegniamo.",C,CI),
("dell-07","dell","Frugality funds growth.","La frugalità finanzia la crescita.",S,SI),
("dell-08","dell","Never outsource the customer.","Non esternalizzare mai il cliente.",C,CI),
("dell-09","dell","Data decides, ego steps aside.","I dati decidono, l'ego si fa da parte.",S,SI),
("dell-10","dell","Go private to think long.","Torna privato per pensare lungo.",S,SI),
("knight-01","knight","Just do it, then keep doing it.","Fallo e basta, poi continua a farlo.",C,CI),
("knight-02","knight","Play by the rules, but be ferocious.","Gioca secondo le regole, ma sii feroce.",A,AI),
("knight-03","knight","Fail fast, run farther.","Fallisci in fretta, corri più lontano.",A,AI),
("knight-04","knight","Shoes carry stories.","Le scarpe portano storie.",S,SI),
("knight-05","knight","Bet on athletes' dreams.","Scommetti sui sogni degli atleti.",C,CI),
("knight-06","knight","Marketing is emotion at speed.","Il marketing è emozione a velocità.",S,SI),
("knight-07","knight","Keep the trunk mentality.","Conserva la mentalità del bagagliaio.",A,AI),
("knight-08","knight","Winning takes care of everything.","Vincere sistema tutto.",A,AI),
("knight-09","knight","Design for the finish line.","Disegna per il traguardo.",C,CI),
("knight-10","knight","Run the first mile yourself.","Corri tu stesso il primo miglio.",S,SI),
("schultz-01","schultz","A third place between home and work.","Un terzo luogo tra casa e lavoro.",S,SI),
("schultz-02","schultz","Treat baristas like partners.","Tratta i baristi come soci.",C,CI),
("schultz-03","schultz","Romance the bean, respect the farmer.","Romantica il chicco, rispetta il coltivatore.",C,CI),
("schultz-04","schultz","Grow with discipline, pour with love.","Cresci con disciplina, versa con amore.",S,SI),
("schultz-05","schultz","Milan taught me the ritual.","Milano mi insegnò il rito.",S,SI),
("schultz-06","schultz","Benefits brew loyalty.","I benefit preparano fedeltà.",C,CI),
("schultz-07","schultz","Every store is a stage.","Ogni negozio è un palcoscenico.",S,SI),
("schultz-08","schultz","Listen to the regulars.","Ascolta gli abituali.",S,SI),
("schultz-09","schultz","Values in every cup.","Valori in ogni tazzina.",C,CI),
("schultz-10","schultz","Dream Brooklyn, brew global.","Sogna Brooklyn, prepara globale.",A,AI),
("blakely-01","blakely","Cut the feet off fear.","Taglia i piedi alla paura.",S,SI),
("blakely-02","blakely","Differentiate with a wink.","Differenziati con un occhiolino.",S,SI),
("blakely-03","blakely","Sell the solution, not the shapewear.","Vendi la soluzione, non la guaina.",C,CI),
("blakely-04","blakely","Failure school beats business school.","La scuola del fallimento batte la business school.",S,SI),
("blakely-05","blakely","Bootstrap with belly laughs.","Autofinanziati con risate di pancia.",A,AI),
("blakely-06","blakely","Name it funny, make it serious.","Chiamalo buffo, fallo sul serio.",S,SI),
("blakely-07","blakely","Prototype in your own mirror.","Prototipa nel tuo specchio.",S,SI),
("blakely-08","blakely","Cold-call with warmth.","Chiamate a freddo con calore.",S,SI),
("blakely-09","blakely","Empower women, fit everyone.","Dai potere alle donne, vesti tutte.",C,CI),
("blakely-10","blakely","Billion with a smile.","Miliardo con il sorriso.",A,AI),
("jackma-01","jackma","Today is hard, tomorrow will be worse, the day after will be sunshine.","Oggi è dura, domani peggio, dopodomani sole.",S,SI),
("jackma-02","jackma","If you don't give up, you still have a chance.","Se non molli, hai ancora una chance.",S,SI),
("jackma-03","jackma","Help small businesses dream big.","Aiuta le piccole imprese a sognare in grande.",C,CI),
("jackma-04","jackma","Customers first, employees second, shareholders third.","Prima i clienti, poi i dipendenti, poi gli azionisti.",S,SI),
("jackma-05","jackma","Never give up is my middle name.","Non mollare mai è il mio secondo nome.",A,AI),
("jackma-06","jackma","Opportunity hides in complaints.","L'opportunità si nasconde nei reclami.",S,SI),
("jackma-07","jackma","Work happily, live seriously.","Lavora felice, vivi sul serio.",A,AI),
("jackma-08","jackma","A teacher never stops learning.","Un insegnante non smette mai di imparare.",S,SI),
("jackma-09","jackma","Globalize with a local heart.","Globalizza con cuore locale.",C,CI),
("jackma-10","jackma","Embrace change, dance with it.","Abbraccia il cambiamento, danzaci.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchC added={added} total_en={len(en)} total_it={len(it)}")
