"""Batch L: culture 2, classics & moderns (17 x 10 = 170)."""
import json

CAT = "culture"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"

AUTHORS = {
"socrates": ("Socrates", "Philosopher · Athens", "Filosofo · Atene", "470–399 BCE",
 "Athenian gadfly who knew only ignorance.",
 "Tafano ateniese che sapeva solo di non sapere."),
"plato": ("Plato", "Philosopher · Republic", "Filosofo · Repubblica", "428–348 BCE",
 "Student of Socrates, architect of ideal cities.",
 "Allievo di Socrate, architetto di città ideali."),
"aristotle": ("Aristotle", "Philosopher · Ethics", "Filosofo · Etica", "384–322 BCE",
 "Stagirite tutor of Alexander, classifier of everything.",
 "Stagirita tutore di Alessandro, classificatore di tutto."),
"epicurus": ("Epicurus", "Philosopher · Garden", "Filosofo · Giardino", "341–270 BCE",
 "Gardener of modest pleasures and friendship.",
 "Giardiniere di modesti piaceri e amicizia."),
"cicero": ("Cicero", "Orator · Rome", "Oratore · Roma", "106–43 BCE",
 "Roman tongue thundering against tyranny.",
 "Lingua romana che tuonò contro la tirannia."),
"epictetus": ("Epictetus", "Philosopher · Stoicism", "Filosofo · Stoicismo", "50–135",
 "Freed slave teaching what depends on us.",
 "Schiavo liberato che insegnò ciò che dipende da noi."),
"confucius": ("Confucius", "Philosopher · Analects", "Filosofo · Dialoghi", "551–479 BCE",
 "Lu sage ordering society by ritual and respect.",
 "Saggio di Lu che ordinò la società con rito e rispetto."),
"laozi": ("Laozi", "Philosopher · Tao", "Filosofo · Tao", "6th c. BCE",
 "Archivist who rode west leaving the Way.",
 "Archivista che cavalcò a ovest lasciando la Via."),
"buddha": ("Buddha", "Teacher · Dharma", "Maestro · Dharma", "5th c. BCE",
 "Nepalese prince waking under the fig tree.",
 "Principe nepalese risvegliato sotto il fico."),
"rumi": ("Rumi", "Poet · Masnavi", "Poeta · Masnavi", "1207–1273",
 "Whirling mystic of love beyond religion.",
 "Mistico roteante d'amore oltre la religione."),
"gibran": ("Kahlil Gibran", "Poet · The Prophet", "Poeta · Il Profeta", "1883–1931",
 "Lebanese painter preaching children and freedom.",
 "Pittore libanese che predicò bambini e libertà."),
"wilde": ("Oscar Wilde", "Writer · Dorian Gray", "Scrittore · Dorian Gray", "1854–1900",
 "Dublin wit martyred for paradox.",
 "Arguzia dublinese martire del paradosso."),
"twain": ("Mark Twain", "Writer · Huckleberry", "Scrittore · Huckleberry", "1835–1910",
 "Mississippi pilot navigating American humor.",
 "Pilota del Mississippi che navigò l'umorismo americano."),
"hemingway": ("Ernest Hemingway", "Writer · Old Man", "Scrittore · Il vecchio", "1899–1961",
 "Oak Park boxer writing in short true sentences.",
 "Pugile di Oak Park che scrisse in frasi brevi e vere."),
"faulkner": ("William Faulkner", "Writer · Yoknapatawpha", "Scrittore · Yoknapatawpha", "1897–1962",
 "Mississippi chronicler of haunted counties.",
 "Cronista del Mississippi di contee infestate."),
"steinbeck": ("John Steinbeck", "Writer · Grapes", "Scrittore · Furore", "1902–1968",
 "Salinas voice of migrants and mercy.",
 "Voce di Salinas di migranti e misericordia."),
"kafka": ("Franz Kafka", "Writer · Trial", "Scrittore · Processo", "1883–1924",
 "Prague clerk metamorphosing bureaucracy.",
 "Impiegato praghese che metamorfosò la burocrazia."),
}

Q = [
("socrates-01","socrates","I know that I know nothing.","So di non sapere.",A,AI),
("socrates-02","socrates","The unexamined life is not worth living.","La vita non esaminata non vale la pena.",A,AI),
("socrates-03","socrates","Wisdom begins in wonder.","La saggezza comincia nella meraviglia.",A,AI),
("socrates-04","socrates","Hemlock could not silence questions.","La cicuta non poté zittire le domande.",A,AI),
("socrates-05","socrates","Know thyself first.","Conosci prima te stesso.",A,AI),
("socrates-06","socrates","Athenian streets school philosophers.","Le strade di Atene istruiscono filosofi.",A,AI),
("socrates-07","socrates","Irony teaches humility.","L'ironia insegna umiltà.",A,AI),
("socrates-08","socrates","Corrupt the youth with truth.","Corrompi i giovani con verità.",A,AI),
("socrates-09","socrates","Midwife ideas, own none.","Fai da levatrice alle idee, non possederne.",A,AI),
("socrates-10","socrates","Death may be migration.","La morte può essere migrazione.",A,AI),
("plato-01","plato","Philosophers must be kings.","I filosofi devono essere re.",A,AI),
("plato-02","plato","Caves shadow our certainties.","Le caverne adombrano le nostre certezze.",A,AI),
("plato-03","plato","Music molds the soul.","La musica plasma l'anima.",A,AI),
("plato-04","plato","Academy gates admit geometers.","I cancelli dell'Accademia ammettono geometri.",A,AI),
("plato-05","plato","Love climbs toward beauty.","L'amore sale verso bellezza.",A,AI),
("plato-06","plato","Democracy decays into tyranny.","La democrazia decade in tirannia.",A,AI),
("plato-07","plato","Atlantis warns ambition.","Atlantide avverte ambizione.",A,AI),
("plato-08","plato","Socrates drinks, truth remains.","Socrate beve, la verità resta.",A,AI),
("plato-09","plato","Ideas outlive marble.","Le idee sopravvivono al marmo.",A,AI),
("plato-10","plato","Dialectic dawns slowly.","La dialettica albeggia piano.",A,AI),
("aristotle-01","aristotle","We are what we repeatedly do.","Siamo ciò che facciamo ripetutamente.",A,AI),
("aristotle-02","aristotle","Man is a political animal.","L'uomo è un animale politico.",A,AI),
("aristotle-03","aristotle","Virtue lies in the middle.","La virtù sta nel mezzo.",A,AI),
("aristotle-04","aristotle","Alexander learned logic here.","Alessandro imparò logica qui.",A,AI),
("aristotle-05","aristotle","Lyceum walks while thinking.","Il Liceo cammina pensando.",A,AI),
("aristotle-06","aristotle","Poetry truer than history.","La poesia è più vera della storia.",A,AI),
("aristotle-07","aristotle","Friendship is one soul in two.","L'amicizia è un'anima in due.",A,AI),
("aristotle-08","aristotle","Stagira births systems.","Stagira partorisce sistemi.",A,AI),
("aristotle-09","aristotle","Causes quadruple understanding.","Le cause quadruplicano comprensione.",A,AI),
("aristotle-10","aristotle","Contemplate, then act.","Contempla, poi agisci.",A,AI),
("epicurus-01","epicurus","Death is nothing to us.","La morte non è nulla per noi.",A,AI),
("epicurus-02","epicurus","Simple bread, serene gods.","Pane semplice, dèi sereni.",A,AI),
("epicurus-03","epicurus","Friendship feasts daily.","L'amicizia banchetta ogni giorno.",A,AI),
("epicurus-04","epicurus","Gardens beat palaces.","I giardini battono i palazzi.",A,AI),
("epicurus-05","epicurus","Desires need limits.","I desideri hanno bisogno di limiti.",A,AI),
("epicurus-06","epicurus","Samos sails Epicurus.","Samo naviga Epicuro.",A,AI),
("epicurus-07","epicurus","Pleasure means absence of pain.","Il piacere è assenza di dolore.",A,AI),
("epicurus-08","epicurus","Write letters to friends.","Scrivi lettere agli amici.",A,AI),
("epicurus-09","epicurus","Gods dwell unbothered.","Gli dèi dimorano indisturbati.",A,AI),
("epicurus-10","epicurus","Cheese suffices with friends.","Il formaggio basta con amici.",A,AI),
("cicero-01","cicero","How long, Catiline, will you abuse us?","Fino a quando, Catilina, abuserai di noi?",A,AI),
("cicero-02","cicero","A room without books is a body without soul.","Una stanza senza libri è un corpo senz'anima.",A,AI),
("cicero-03","cicero","Laws protect freedom.","Le leggi proteggono libertà.",A,AI),
("cicero-04","cicero","Arpinum echoes oratory.","Arpino echeggia oratoria.",A,AI),
("cicero-05","cicero","Old age needs philosophy.","La vecchiaia ha bisogno di filosofia.",A,AI),
("cicero-06","cicero","Friendship improves by candlelight.","L'amicizia migliora a lume di candela.",A,AI),
("cicero-07","cicero","Tyrants fear tongues.","I tiranni temono le lingue.",A,AI),
("cicero-08","cicero","Republics demand rhetoric.","Le repubbliche esigono retorica.",A,AI),
("cicero-09","cicero","Exile sharpens letters.","L'esilio affila lettere.",A,AI),
("cicero-10","cicero","Duty crowns citizens.","Il dovere corona cittadini.",A,AI),
("epictetus-01","epictetus","Some things are up to us.","Alcune cose dipendono da noi.",A,AI),
("epictetus-02","epictetus","Chains freed my mind.","Le catene liberarono la mia mente.",A,AI),
("epictetus-03","epictetus","Desire only what depends on you.","Desidera solo ciò che dipende da te.",A,AI),
("epictetus-04","epictetus","Hierapolis births freedom.","Ierapoli partorisce libertà.",A,AI),
("epictetus-05","epictetus","Obstacles are training.","Gli ostacoli sono allenamento.",A,AI),
("epictetus-06","epictetus","Masters own bodies, never wills.","I padroni possiedono corpi, mai volontà.",A,AI),
("epictetus-07","epictetus","Nicopolis lectures quietly.","Nicopoli insegna piano.",A,AI),
("epictetus-08","epictetus","Impressions await assent.","Le impressioni attendono assenso.",A,AI),
("epictetus-09","epictetus","Lameness walks upright.","La zoppia cammina eretta.",A,AI),
("epictetus-10","epictetus","Philosophy is hospital.","La filosofia è ospedale.",A,AI),
("confucius-01","confucius","Do not do to others what you dislike.","Non fare agli altri ciò che non ti piace.",A,AI),
("confucius-02","confucius","Learning without thought is labor lost.","Studiare senza pensare è fatica persa.",A,AI),
("confucius-03","confucius","Ritual orders chaos.","Il rito ordina il caos.",A,AI),
("confucius-04","confucius","Lu wanders seeking rulers.","Lu vaga cercando governanti.",A,AI),
("confucius-05","confucius","Filial piety roots society.","La pietà filiale radica società.",A,AI),
("confucius-06","confucius","The gentleman understands righteousness.","Il gentiluomo comprende rettitudine.",A,AI),
("confucius-07","confucius","Review the old, know the new.","Ripassa l'antico, conosci il nuovo.",A,AI),
("confucius-08","confucius","Music harmonizes states.","La musica armonizza stati.",A,AI),
("confucius-09","confucius","Disciples record masters.","I discepoli registrano maestri.",A,AI),
("confucius-10","confucius","At seventy, follow desires rightly.","A settanta, segui i desideri giustamente.",A,AI),
("laozi-01","laozi","The journey of a thousand miles begins with one step.","Il viaggio di mille miglia comincia con un passo.",A,AI),
("laozi-02","laozi","Water overcomes stone softly.","L'acqua vince la pietra con dolcezza.",A,AI),
("laozi-03","laozi","Those who know do not speak.","Chi sa non parla.",A,AI),
("laozi-04","laozi","Ride west beyond the pass.","Cavalca a ovest oltre il passo.",A,AI),
("laozi-05","laozi","Emptiness holds the wheel.","Il vuoto tiene la ruota.",A,AI),
("laozi-06","laozi","Archivists vanish wisely.","Gli archivisti svaniscono saggi.",A,AI),
("laozi-07","laozi","Non-action acts everywhere.","Il non-agire agisce ovunque.",A,AI),
("laozi-08","laozi","Eighty-one chapters suffice.","Ottantuno capitoli bastano.",A,AI),
("laozi-09","laozi","Tao that speaks is not Tao.","Il Tao che si dice non è Tao.",A,AI),
("laozi-10","laozi","Return to uncarved wood.","Ritorna al legno non intagliato.",A,AI),
("buddha-01","buddha","Peace comes from within.","La pace viene da dentro.",A,AI),
("buddha-02","buddha","Three things cannot hide: sun, moon, truth.","Tre cose non si nascondono: sole, luna, verità.",A,AI),
("buddha-03","buddha","Hatred ceases by love.","L'odio cessa con amore.",A,AI),
("buddha-04","buddha","Bodhi trees shade awakening.","Gli alberi di Bodhi ombreggiano il risveglio.",A,AI),
("buddha-05","buddha","Middle path avoids extremes.","La via di mezzo evita estremi.",A,AI),
("buddha-06","buddha","Lumbini blooms compassion.","Lumbini fiorisce compassione.",A,AI),
("buddha-07","buddha","Mind precedes phenomena.","La mente precede i fenomeni.",A,AI),
("buddha-08","buddha","Monsoons teach impermanence.","I monsoni insegnano impermanenza.",A,AI),
("buddha-09","buddha","Be lamps unto yourselves.","Siate lampade a voi stessi.",A,AI),
("buddha-10","buddha","Suffering has an end.","La sofferenza ha una fine.",A,AI),
("rumi-01","rumi","What you seek is seeking you.","Ciò che cerchi ti sta cercando.",A,AI),
("rumi-02","rumi","Wound is where light enters.","La ferita è dove entra la luce.",A,AI),
("rumi-03","rumi","Dance when broken open.","Danza quando sei spezzato e aperto.",A,AI),
("rumi-04","rumi","Konya whirls devotion.","Konya turbina devozione.",A,AI),
("rumi-05","rumi","Lovers never meet; they are within.","Gli amanti non si incontrano mai; sono dentro.",A,AI),
("rumi-06","rumi","Shams ignites verses.","Shams accende versi.",A,AI),
("rumi-07","rumi","Sell cleverness, buy bewilderment.","Vendi furbizia, compra smarrimento.",A,AI),
("rumi-08","rumi","Reeds mourn separation.","Le canne piangono separazione.",A,AI),
("rumi-09","rumi","Beyond right and wrong, meet.","Oltre giusto e sbagliato, incontriamoci.",A,AI),
("rumi-10","rumi","Grief prepares gardens.","Il dolore prepara giardini.",A,AI),
("gibran-01","gibran","Your children are not your children.","I vostri figli non sono i vostri figli.",A,AI),
("gibran-02","gibran","Work is love made visible.","Il lavoro è amore reso visibile.",A,AI),
("gibran-03","gibran","Freedom hides in discipline.","La libertà si nasconde nella disciplina.",A,AI),
("gibran-04","gibran","Bsharri cedars whisper prophets.","I cedri di Bsharri sussurrano profeti.",A,AI),
("gibran-05","gibran","Sorrow carves joy's space.","Il dolore intaglia lo spazio della gioia.",A,AI),
("gibran-06","gibran","Boston exiles paint verses.","Gli esuli di Boston dipingono versi.",A,AI),
("gibran-07","gibran","Give without remembering.","Dai senza ricordare.",A,AI),
("gibran-08","gibran","Love crowns and crucifies.","L'amore incorona e crocifigge.",A,AI),
("gibran-09","gibran","Almustafa sails homeward.","Almustafa naviga verso casa.",A,AI),
("gibran-10","gibran","Beauty enchants eternally.","La bellezza incanta eternamente.",A,AI),
("wilde-01","wilde","Be yourself; everyone else is taken.","Sii te stesso; gli altri sono già presi.",A,AI),
("wilde-02","wilde","We are all in the gutter, gazing at stars.","Siamo tutti nella fogna, a guardare le stelle.",A,AI),
("wilde-03","wilde","To live is the rarest thing.","Vivere è la cosa più rara.",A,AI),
("wilde-04","wilde","Dublin wits sparkle sharpest.","Le arguzie di Dublino brillano più taglienti.",A,AI),
("wilde-05","wilde","Experience is the name of mistakes.","Esperienza è il nome degli errori.",A,AI),
("wilde-06","wilde","Art for art's sake endures.","L'arte per l'arte dura.",A,AI),
("wilde-07","wilde","Reading gaols liberate minds.","Le prigioni di Reading liberano menti.",A,AI),
("wilde-08","wilde","Importance of being earnest always.","L'importanza di chiamarsi Ernesto sempre.",A,AI),
("wilde-09","wilde","Paradoxes polish truth.","I paradossi lucidano verità.",A,AI),
("wilde-10","wilde","Dandies die, epigrams don't.","I dandy muoiono, gli epigrammi no.",A,AI),
("twain-01","twain","The secret of getting ahead is getting started.","Il segreto per andare avanti è cominciare.",A,AI),
("twain-02","twain","Travel is fatal to prejudice.","Viaggiare è fatale al pregiudizio.",A,AI),
("twain-03","twain","Mississippi pilots steer humor.","I piloti del Mississippi guidano umorismo.",A,AI),
("twain-04","twain","Huck rafts toward freedom.","Huck naviga su zattera verso libertà.",A,AI),
("twain-05","twain","Reports of my death are exaggerated.","Le voci sulla mia morte sono esagerate.",A,AI),
("twain-06","twain","Clemens typeset truth.","Clemens compose verità.",A,AI),
("twain-07","twain","Good friends, good books, sleepy conscience.","Buoni amici, buoni libri, coscienza sonnolenta.",A,AI),
("twain-08","twain","Hannibal boys dream rivers.","I ragazzi di Hannibal sognano fiumi.",A,AI),
("twain-09","twain","Wrinkles record laughter.","Le rughe registrano risate.",A,AI),
("twain-10","twain","Ink flows muddy and clear.","L'inchiostro scorre torbido e chiaro.",A,AI),
("hemingway-01","hemingway","Write drunk, edit sober.","Scrivi ubriaco, correggi sobrio.",A,AI),
("hemingway-02","hemingway","The world breaks everyone.","Il mondo spezza tutti.",A,AI),
("hemingway-03","hemingway","Paris was a moveable feast.","Parigi era una festa mobile.",A,AI),
("hemingway-04","hemingway","Old men salute marlins.","I vecchi salutano marlin.",A,AI),
("hemingway-05","hemingway","Oak Park boxes sentences.","Oak Park inscatola frasi.",A,AI),
("hemingway-06","hemingway","Bulls run at dawn.","I tori corrono all'alba.",A,AI),
("hemingway-07","hemingway","Icebergs hide seven-eighths.","Gli iceberg nascondono sette ottavi.",A,AI),
("hemingway-08","hemingway","Kilimanjaro snows silence.","Il Kilimangiaro nevica silenzio.",A,AI),
("hemingway-09","hemingway","Courage is grace under pressure.","Il coraggio è grazia sotto pressione.",A,AI),
("hemingway-10","hemingway","Havana rums remember.","I rum dell'Avana ricordano.",A,AI),
("faulkner-01","faulkner","The past is never dead.","Il passato non è mai morto.",A,AI),
("faulkner-02","faulkner","Yoknapatawpha haunts counties.","Yoknapatawpha infesta contee.",A,AI),
("faulkner-03","faulkner","Endure and prevail, writers must.","Resistere e prevalere, devono gli scrittori.",A,AI),
("faulkner-04","faulkner","Mississippi mud births epics.","Il fango del Mississippi partorisce epopee.",A,AI),
("faulkner-05","faulkner","Sound and fury signify struggle.","Rumore e furore significano lotta.",A,AI),
("faulkner-06","faulkner","Oxford desks outlast fame.","Le scrivanie di Oxford durano più della fama.",A,AI),
("faulkner-07","faulkner","Absalom narrates doom.","Assalonne narra destino.",A,AI),
("faulkner-08","faulkner","Compsons decay beautifully.","I Compson decadono bellissimi.",A,AI),
("faulkner-09","faulkner","Hollywood scripts pay whiskey.","Le sceneggiature di Hollywood pagano whiskey.",A,AI),
("faulkner-10","faulkner","Man will not merely endure.","L'uomo non solo resisterà.",A,AI),
("steinbeck-01","steinbeck","I hold that a writer must serve.","Ritengo che uno scrittore debba servire.",A,AI),
("steinbeck-02","steinbeck","Grapes of wrath ripen.","I grappoli dell'ira maturano.",A,AI),
("steinbeck-03","steinbeck","Salinas valleys cradle migrants.","Le valli di Salinas cullano migranti.",A,AI),
("steinbeck-04","steinbeck","Lennie pets soft tragedies.","Lennie accarezza morbide tragedie.",A,AI),
("steinbeck-05","steinbeck","Cannery Row stinks of truth.","Vicolo Cannery puzza di verità.",A,AI),
("steinbeck-06","steinbeck","Monterey tides turn pages.","Le maree di Monterey girano pagine.",A,AI),
("steinbeck-07","steinbeck","East of Eden questions.","A est dell'Eden interroga.",A,AI),
("steinbeck-08","steinbeck","Travels with Charley teach.","In viaggio con Charley insegna.",A,AI),
("steinbeck-09","steinbeck","Pearls corrupt villages.","Le perle corrompono villaggi.",A,AI),
("steinbeck-10","steinbeck","Nobel thanks the dispossessed.","Il Nobel ringrazia i diseredati.",A,AI),
("kafka-01","kafka","One morning Gregor woke transformed.","Una mattina Gregor si svegliò trasformato.",A,AI),
("kafka-02","kafka","Trials begin without accusation.","I processi cominciano senza accusa.",A,AI),
("kafka-03","kafka","Prague offices breed beetles.","Gli uffici di Praga allevano scarafaggi.",A,AI),
("kafka-04","kafka","Castles stay unreachable.","I castelli restano irraggiungibili.",A,AI),
("kafka-05","kafka","Letters to fathers accuse.","Le lettere ai padri accusano.",A,AI),
("kafka-06","kafka","Hunger artists starve applauded.","I digiunatori muoiono di fame applauditi.",A,AI),
("kafka-07","kafka","Burn manuscripts, friend, please.","Brucia i manoscritti, amico, per favore.",A,AI),
("kafka-08","kafka","Brod betrays beautifully.","Brod tradisce bellissimo.",A,AI),
("kafka-09","kafka","Doors of law stand open.","Le porte della legge stanno aperte.",A,AI),
("kafka-10","kafka","Anxiety writes clearest.","L'ansia scrive più chiaro.",A,AI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchL added={added} total_en={len(en)} total_it={len(it)}")
