"""Batch E: cinema (17 authors x 10 = 170 quotes)."""
import json

CAT = "cinema"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"

AUTHORS = {
"hitchcock": ("Alfred Hitchcock", "Director · Psycho, Vertigo", "Regista · Psycho, La donna che visse due volte", "1899–1980",
 "London master of suspense who made fear elegant.",
 "Maestro londinese della suspense che rese elegante la paura."),
"kubrick": ("Stanley Kubrick", "Director · 2001, The Shining", "Regista · 2001, Shining", "1928–1999",
 "Bronx perfectionist filming the human condition in space and war.",
 "Perfezionista del Bronx che filmò la condizione umana nello spazio e in guerra."),
"spielberg": ("Steven Spielberg", "Director · E.T., Schindler's List", "Regista · E.T., Schindler's List", "1946–",
 "Ohio dreamer who taught blockbusters to cry.",
 "Sognatore dell'Ohio che insegnò ai blockbuster a piangere."),
"tarantino": ("Quentin Tarantino", "Director · Pulp Fiction", "Regista · Pulp Fiction", "1963–",
 "Video-store clerk turned dialogue gunslinger.",
 "Commesso di videonoleggio diventato pistolero dei dialoghi."),
"coppola": ("Francis Ford Coppola", "Director · The Godfather", "Regista · Il Padrino", "1939–",
 "Detroit-born weaver of family sagas and wine.",
 "Tessitore nato a Detroit di saghe familiari e vino."),
"almodovar": ("Pedro Almodóvar", "Director · All About My Mother", "Regista · Tutto su mia madre", "1949–",
 "Manchego melodramatist painting women in bold reds.",
 "Melodrammista manchego che dipinge donne in rossi audaci."),
"godard": ("Jean-Luc Godard", "Director · Breathless", "Regista · Fino all'ultimo respiro", "1930–2022",
 "Swiss-French rule-breaker who jump-cut the language of film.",
 "Infrattore svizzero-francese che tagliò con jump-cut il linguaggio del cinema."),
"bergman": ("Ingmar Bergman", "Director · Persona, Fanny", "Regista · Persona, Fanny e Alexander", "1918–2007",
 "Swedish confessor filming God, silence and faces.",
 "Confessore svedese che filmò Dio, silenzio e volti."),
"tarkovsky": ("Andrei Tarkovsky", "Director · Stalker, Solaris", "Regista · Stalker, Solaris", "1932–1986",
 "Russian poet of time, water and burning houses.",
 "Poeta russo del tempo, dell'acqua e delle case in fiamme."),
"ozu": ("Yasujirō Ozu", "Director · Tokyo Story", "Regista · Viaggio a Tokyo", "1903–1963",
 "Tokyo minimalist filming family goodbyes at tatami height.",
 "Minimalista di Tokyo che filmò addii familiari ad altezza tatami."),
"ray": ("Satyajit Ray", "Director · Pather Panchali", "Regista · Pather Panchali", "1921–1992",
 "Bengali humanist who filmed poverty with lyric grace.",
 "Umanista bengalese che filmò la povertà con grazia lirica."),
"desica": ("Vittorio De Sica", "Director · Bicycle Thieves", "Regista · Ladri di biciclette", "1901–1974",
 "Neorealist heart filming Rome's streets and souls.",
 "Cuore neorealista che filmò strade e anime di Roma."),
"rossellini": ("Roberto Rossellini", "Director · Rome Open City", "Regista · Roma città aperta", "1906–1977",
 "Roman pioneer who shot ruins into rebirth.",
 "Pioniere romano che girò le rovine in rinascita."),
"visconti": ("Luchino Visconti", "Director · The Leopard", "Regista · Il Gattopardo", "1906–1976",
 "Aristocrat filming decadence with operatic splendor.",
 "Aristocratico che filmò la decadenza con splendore operistico."),
"pasolini": ("Pier Paolo Pasolini", "Director · Teorema", "Regista · Teorema", "1922–1975",
 "Bolognese poet filming the sacred among outcasts.",
 "Poeta bolognese che filmò il sacro tra gli emarginati."),
"leone": ("Sergio Leone", "Director · The Good, the Bad", "Regista · Il buono, il brutto", "1929–1989",
 "Roman mythmaker who widened the West to epic silence.",
 "Mitografo romano che allargò il West a silenzio epico."),
"bertolucci": ("Bernardo Bertolucci", "Director · Last Tango, 1900", "Regista · Ultimo tango, Novecento", "1941–2018",
 "Parma dreamer of history, desire and vast plains.",
 "Sognatore parmense di storia, desiderio e vaste pianure."),
}

Q = [
("hitchcock-01","hitchcock","Fear isn't so difficult to understand.","La paura non è così difficile da capire.",S,SI),
("hitchcock-02","hitchcock","Suspense is information plus anticipation.","La suspense è informazione più attesa.",S,SI),
("hitchcock-03","hitchcock","The birds taught me patience.","Gli uccelli mi insegnarono pazienza.",A,AI),
("hitchcock-04","hitchcock","A murderer needs an elegant staircase.","Un assassino ha bisogno di una scala elegante.",A,AI),
("hitchcock-05","hitchcock","Television is like the toaster of images.","La televisione è come il tostapane delle immagini.",A,AI),
("hitchcock-06","hitchcock","Blondes make the best victims.","Le bionde sono le migliori vittime.",A,AI),
("hitchcock-07","hitchcock","Drama is life with the dull bits cut out.","Il dramma è la vita senza le parti noiose.",A,AI),
("hitchcock-08","hitchcock","Always make the audience suffer.","Fai sempre soffrire il pubblico.",S,SI),
("hitchcock-09","hitchcock","Vertigo begins at the top.","Le vertigini cominciano in cima.",A,AI),
("hitchcock-10","hitchcock","Good evening, and mind the shower.","Buonasera, e attenti alla doccia.",A,AI),
("kubrick-01","kubrick","The eye must compose the chaos.","L'occhio deve comporre il caos.",S,SI),
("kubrick-02","kubrick","Perfectionism is obsession with purpose.","Il perfezionismo è ossessione con uno scopo.",A,AI),
("kubrick-03","kubrick","Take fifty takes; truth hides deep.","Fai cinquanta ciak; la verità si nasconde in fondo.",A,AI),
("kubrick-04","kubrick","Space reveals our smallness.","Lo spazio rivela la nostra piccolezza.",S,SI),
("kubrick-05","kubrick","Horror is domestic.","L'orrore è domestico.",A,AI),
("kubrick-06","kubrick","Chess taught me cinema.","Gli scacchi mi insegnarono il cinema.",S,SI),
("kubrick-07","kubrick","Light the candle, wait for dawn.","Accendi la candela, aspetta l'alba.",A,AI),
("kubrick-08","kubrick","War unmasks every uniform.","La guerra smaschera ogni uniforme.",S,SI),
("kubrick-09","kubrick","Symmetry calms, then disturbs.","La simmetria calma, poi turba.",A,AI),
("kubrick-10","kubrick","The future is a long corridor.","Il futuro è un lungo corridoio.",A,AI),
("spielberg-01","spielberg","Wonder is my camera.","La meraviglia è la mia camera.",S,SI),
("spielberg-02","spielberg","A shark taught me fear; a boy taught me flight.","Uno squalo mi insegnò la paura; un bambino il volo.",S,SI),
("spielberg-03","spielberg","Memory must be filmed to survive.","La memoria va filmata per sopravvivere.",S,SI),
("spielberg-04","spielberg","E.T. phones every childhood.","E.T. telefona a ogni infanzia.",A,AI),
("spielberg-05","spielberg","Dinosaurs forgive bad dialogue.","I dinosauri perdonano i brutti dialoghi.",A,AI),
("spielberg-06","spielberg","Light the face, save the soul.","Illumina il volto, salva l'anima.",A,AI),
("spielberg-07","spielberg","Lists save names; films save memory.","Le liste salvano nomi; i film la memoria.",S,SI),
("spielberg-08","spielberg","Never terrify without tenderness.","Mai terrorizzare senza tenerezza.",S,SI),
("spielberg-09","spielberg","Childhood is the best studio.","L'infanzia è il miglior studio.",A,AI),
("spielberg-10","spielberg","Dream in blockbusters, wake in history.","Sogna in blockbuster, svegliati nella storia.",A,AI),
("tarantino-01","tarantino","Dialogue is action with words.","Il dialogo è azione con le parole.",S,SI),
("tarantino-02","tarantino","Steal from everyone, credit cinema.","Ruba da tutti, accredita il cinema.",A,AI),
("tarantino-03","tarantino","Violence dances to old songs.","La violenza danza su vecchie canzoni.",S,SI),
("tarantino-04","tarantino","Trunks hide the best conversations.","I bagagliai nascondono le migliori conversazioni.",A,AI),
("tarantino-05","tarantino","Chapters liberate time.","I capitoli liberano il tempo.",S,SI),
("tarantino-06","tarantino","Feet, fries and philosophy.","Piedi, patatine e filosofia.",A,AI),
("tarantino-07","tarantino","Revenge needs a soundtrack.","La vendetta ha bisogno di colonna sonora.",S,SI),
("tarantino-08","tarantino","Video stores raised me.","I videonoleggi mi hanno cresciuto.",S,SI),
("tarantino-09","tarantino","Blood must be beautiful.","Il sangue deve essere bello.",A,AI),
("tarantino-10","tarantino","Endings rewrite beginnings.","I finali riscrivono gli inizi.",S,SI),
("coppola-01","coppola","Family is the greatest saga.","La famiglia è la più grande saga.",S,SI),
("coppola-02","coppola","An offer of light and shadow.","Un'offerta di luce e ombra.",A,AI),
("coppola-03","coppola","Wine, like film, needs time.","Il vino, come il film, ha bisogno di tempo.",S,SI),
("coppola-04","coppola","Risk the studio for the vision.","Rischia lo studio per la visione.",S,SI),
("coppola-05","coppola","Darkness photographs loyalty.","Il buio fotografa la lealtà.",A,AI),
("coppola-06","coppola","Apocalypse begins in the edit.","L'apocalisse comincia in montaggio.",S,SI),
("coppola-07","coppola","Fathers cast the longest shadows.","I padri proiettano le ombre più lunghe.",A,AI),
("coppola-08","coppola","Napa edits my dreams.","Napa monta i miei sogni.",S,SI),
("coppola-09","coppola","Power whispers in Sicilian.","Il potere sussurra in siciliano.",A,AI),
("coppola-10","coppola","Never rush the saga.","Mai affrettare la saga.",S,SI),
("almodovar-01","almodovar","Women are my landscape.","Le donne sono il mio paesaggio.",S,SI),
("almodovar-02","almodovar","Red heals everything.","Il rosso guarisce tutto.",S,SI),
("almodovar-03","almodovar","Melodrama tells the truth loudly.","Il melodramma dice la verità ad alta voce.",S,SI),
("almodovar-04","almodovar","Madrid raised my colors.","Madrid ha cresciuto i miei colori.",S,SI),
("almodovar-05","almodovar","Desire needs close-ups.","Il desiderio ha bisogno di primi piani.",A,AI),
("almodovar-06","almodovar","Mothers hold every plot.","Le madri tengono ogni trama.",S,SI),
("almodovar-07","almodovar","Kitsch with a beating heart.","Kitsch con cuore pulsante.",A,AI),
("almodovar-08","almodovar","Pain writes the best scripts.","Il dolore scrive le migliori sceneggiature.",S,SI),
("almodovar-09","almodovar","Talk to her, always.","Parla con lei, sempre.",A,AI),
("almodovar-10","almodovar","La Mancha dreams in Technicolor.","La Mancia sogna in Technicolor.",A,AI),
("godard-01","godard","A story needs a beginning, middle and end, not necessarily in that order.","Una storia vuole inizio, metà e fine, non per forza in quest'ordine.",A,AI),
("godard-02","godard","Cinema is truth at twenty-four frames.","Il cinema è verità a ventiquattro fotogrammi.",A,AI),
("godard-03","godard","Jump-cut the boredom.","Taglia con jump-cut la noia.",S,SI),
("godard-04","godard","All you need is a girl and a gun.","Bastano una ragazza e una pistola.",A,AI),
("godard-05","godard","Politics in every tracking shot.","Politica in ogni carrellata.",S,SI),
("godard-06","godard","3D is flat without ideas.","Il 3D è piatto senza idee.",S,SI),
("godard-07","godard","Breathe out of sync.","Respira fuori sincrono.",A,AI),
("godard-08","godard","Criticism is cinema thinking.","La critica è cinema che pensa.",S,SI),
("godard-09","godard","Color argues with itself.","Il colore discute con sé stesso.",A,AI),
("godard-10","godard","Endings are beginnings that stopped.","I finali sono inizi che si sono fermati.",A,AI),
("bergman-01","bergman","Silence speaks the loudest lines.","Il silenzio dice le battute più forti.",S,SI),
("bergman-02","bergman","Faces are landscapes of faith.","I volti sono paesaggi di fede.",S,SI),
("bergman-03","bergman","God hides in close-ups.","Dio si nasconde nei primi piani.",A,AI),
("bergman-04","bergman","Fårö wind directs my actors.","Il vento di Fårö dirige i miei attori.",S,SI),
("bergman-05","bergman","Marriage is a long chess game.","Il matrimonio è una lunga partita a scacchi.",A,AI),
("bergman-06","bergman","Persona: two souls, one frame.","Persona: due anime, un'inquadratura.",S,SI),
("bergman-07","bergman","Doubt photographs beautifully.","Il dubbio fotografa benissimo.",A,AI),
("bergman-08","bergman","Childhood summers never end.","Le estati dell'infanzia non finiscono mai.",S,SI),
("bergman-09","bergman","Confess to the camera.","Confessati alla camera.",A,AI),
("bergman-10","bergman","Winter light forgives nothing.","La luce d'inverno non perdona nulla.",A,AI),
("tarkovsky-01","tarkovsky","Time sculpts in cinema.","Il tempo scolpisce nel cinema.",S,SI),
("tarkovsky-02","tarkovsky","Water remembers everything.","L'acqua ricorda tutto.",A,AI),
("tarkovsky-03","tarkovsky","The Zone grants inner wishes.","La Zona esaudisce desideri interiori.",S,SI),
("tarkovsky-04","tarkovsky","Burn the house, keep the faith.","Brucia la casa, conserva la fede.",A,AI),
("tarkovsky-05","tarkovsky","Childhood rains forever.","Le piogge dell'infanzia durano per sempre.",A,AI),
("tarkovsky-06","tarkovsky","Slow cinema, deep soul.","Cinema lento, anima profonda.",S,SI),
("tarkovsky-07","tarkovsky","Mirrors multiply memory.","Gli specchi moltiplicano la memoria.",A,AI),
("tarkovsky-08","tarkovsky","Solaris reads your grief.","Solaris legge il tuo dolore.",S,SI),
("tarkovsky-09","tarkovsky","Art needs sacrifice.","L'arte ha bisogno di sacrificio.",S,SI),
("tarkovsky-10","tarkovsky","Exile sharpens vision.","L'esilio affila la visione.",A,AI),
("ozu-01","ozu","Family fades like afternoon tea.","La famiglia svanisce come il tè del pomeriggio.",A,AI),
("ozu-02","ozu","Low camera, deep respect.","Camera bassa, profondo rispetto.",S,SI),
("ozu-03","ozu","Tokyo goodbyes take seasons.","Gli addii di Tokyo richiedono stagioni.",A,AI),
("ozu-04","ozu","Parents wait, children leave.","I genitori aspettano, i figli partono.",S,SI),
("ozu-05","ozu","Tatami perspective, human measure.","Prospettiva tatami, misura umana.",S,SI),
("ozu-06","ozu","Tea cools, love stays.","Il tè si raffredda, l'amore resta.",A,AI),
("ozu-07","ozu","Repeat the shot, deepen the feeling.","Ripeti l'inquadratura, approfondisci il sentimento.",S,SI),
("ozu-08","ozu","Stillness moves most.","La quiete commuove di più.",A,AI),
("ozu-09","ozu","Generations pass like trains.","Le generazioni passano come treni.",S,SI),
("ozu-10","ozu","Simplicity is the final style.","La semplicità è lo stile finale.",A,AI),
("ray-01","ray","Poverty sings in lyric frames.","La povertà canta in inquadrature liriche.",S,SI),
("ray-02","ray","Bengal taught me humanity.","Il Bengala mi insegnò umanità.",S,SI),
("ray-03","ray","A child's eyes direct best.","Gli occhi di un bambino dirigono meglio.",A,AI),
("ray-04","ray","Music walks beside images.","La musica cammina accanto alle immagini.",S,SI),
("ray-05","ray","Apu grows with every viewer.","Apu cresce con ogni spettatore.",S,SI),
("ray-06","ray","Calcutta crowds whisper epics.","Le folle di Calcutta sussurrano epopee.",A,AI),
("ray-07","ray","Dignity needs no budget.","La dignità non ha bisogno di budget.",A,AI),
("ray-08","ray","Train whistles announce fate.","I fischi dei treni annunciano il destino.",A,AI),
("ray-09","ray","Observe gently, reveal deeply.","Osserva con garbo, rivela in profondità.",S,SI),
("ray-10","ray","Humanism is my special effect.","L'umanesimo è il mio effetto speciale.",S,SI),
("desica-01","desica","Streets write better scripts.","Le strade scrivono sceneggiature migliori.",S,SI),
("desica-02","desica","A bicycle carries dignity.","Una bicicletta porta dignità.",S,SI),
("desica-03","desica","Non-actors act truth.","I non attori recitano verità.",S,SI),
("desica-04","desica","Rome's ruins hold hope.","Le rovine di Roma custodiscono speranza.",A,AI),
("desica-05","desica","Children see clearest.","I bambini vedono più chiaro.",A,AI),
("desica-06","desica","Umbrellas open solidarity.","Gli ombrelli aprono solidarietà.",A,AI),
("desica-07","desica","Shoot where life hurts.","Gira dove la vita fa male.",S,SI),
("desica-08","desica","Neorealism is compassion.","Il neorealismo è compassione.",S,SI),
("desica-09","desica","Miracles need bus fare.","I miracoli hanno bisogno del biglietto del bus.",A,AI),
("desica-10","desica","Yesterday's hunger films today.","La fame di ieri filma l'oggi.",A,AI),
("rossellini-01","rossellini","Ruins are sets of rebirth.","Le rovine sono set di rinascita.",S,SI),
("rossellini-02","rossellini","Open cities, open cameras.","Città aperte, camere aperte.",S,SI),
("rossellini-03","rossellini","History must be shot now.","La storia va girata ora.",S,SI),
("rossellini-04","rossellini","Resistance lives in faces.","La resistenza vive nei volti.",A,AI),
("rossellini-05","rossellini","Television can teach nations.","La televisione può insegnare alle nazioni.",S,SI),
("rossellini-06","rossellini","Facts first, fiction follows.","Prima i fatti, poi la finzione.",S,SI),
("rossellini-07","rossellini","Rome bleeds and hopes.","Roma sanguina e spera.",A,AI),
("rossellini-08","rossellini","Document to imagine.","Documenta per immaginare.",S,SI),
("rossellini-09","rossellini","War ends, lenses remain.","La guerra finisce, gli obiettivi restano.",A,AI),
("rossellini-10","rossellini","Journey to every Italy.","Viaggio in ogni Italia.",A,AI),
("visconti-01","visconti","Decadence deserves splendor.","La decadenza merita splendore.",S,SI),
("visconti-02","visconti","Leopards change to remain.","I gattopardi cambiano per restare.",S,SI),
("visconti-03","visconti","Opera directs my camera.","L'opera dirige la mia camera.",S,SI),
("visconti-04","visconti","Sicily mourns in gold.","La Sicilia piange in oro.",A,AI),
("visconti-05","visconti","Beauty rots exquisitely.","La bellezza marcisce squisitamente.",A,AI),
("visconti-06","visconti","Aristocrats fund revolutions.","Gli aristocratici finanziano rivoluzioni.",A,AI),
("visconti-07","visconti","Chandeliers witness history.","I lampadari testimoniano la storia.",A,AI),
("visconti-08","visconti","Venice drowns desire.","Venezia annega il desiderio.",A,AI),
("visconti-09","visconti","Dinners decide destinies.","Le cene decidono destini.",A,AI),
("visconti-10","visconti","Style is ideology.","Lo stile è ideologia.",S,SI),
("pasolini-01","pasolini","The sacred hides in slums.","Il sacro si nasconde nelle borgate.",S,SI),
("pasolini-02","pasolini","Bodies protest louder than slogans.","I corpi protestano più forte degli slogan.",A,AI),
("pasolini-03","pasolini","Rome's outskirts preach truth.","Le periferie di Roma predicano verità.",S,SI),
("pasolini-04","pasolini","Consumerism devours dialects.","Il consumismo divora i dialetti.",S,SI),
("pasolini-05","pasolini","Christ walks with the poor.","Cristo cammina con i poveri.",A,AI),
("pasolini-06","pasolini","Medea sings ancient rage.","Medea canta rabbia antica.",A,AI),
("pasolini-07","pasolini","Poetry accuses power.","La poesia accusa il potere.",S,SI),
("pasolini-08","pasolini","Bologna remembers my verses.","Bologna ricorda i miei versi.",A,AI),
("pasolini-09","pasolini","Innocence indicts.","L'innocenza incrimina.",A,AI),
("pasolini-10","pasolini","Prophecy needs a camera.","La profezia ha bisogno di una camera.",S,SI),
("leone-01","leone","Silence shoots first.","Il silenzio spara per primo.",S,SI),
("leone-02","leone","Close-ups are duels.","I primi piani sono duelli.",S,SI),
("leone-03","leone","The West is an Italian dream.","Il West è un sogno italiano.",S,SI),
("leone-04","leone","Whistles widen horizons.","I fischi allargano gli orizzonti.",A,AI),
("leone-05","leone","Dust reveals character.","La polvere rivela il carattere.",A,AI),
("leone-06","leone","Three men, one destiny.","Tre uomini, un destino.",A,AI),
("leone-07","leone","Morricone aims my pistol.","Morricone mira la mia pistola.",S,SI),
("leone-08","leone","Stare longer than fear.","Fissa più a lungo della paura.",A,AI),
("leone-09","leone","America reflects Cinecittà.","L'America riflette Cinecittà.",S,SI),
("leone-10","leone","Once upon my time.","C'era una volta il mio tempo.",A,AI),
("bertolucci-01","bertolucci","History dances in ballrooms.","La storia danza nelle sale da ballo.",S,SI),
("bertolucci-02","bertolucci","Parma plains hold epics.","Le pianure di Parma custodiscono epopee.",S,SI),
("bertolucci-03","bertolucci","Desire defies empires.","Il desiderio sfida gli imperi.",A,AI),
("bertolucci-04","bertolucci","The last emperor dreams within walls.","L'ultimo imperatore sogna tra mura.",S,SI),
("bertolucci-05","bertolucci","1900 spans a century of wheat.","Novecento attraversa un secolo di grano.",S,SI),
("bertolucci-06","bertolucci","Conformists fear color.","I conformisti temono il colore.",A,AI),
("bertolucci-07","bertolucci","Tangos translate loneliness.","I tanghi traducono solitudine.",A,AI),
("bertolucci-08","bertolucci","Steal beauty from paintings.","Ruba bellezza dai quadri.",S,SI),
("bertolucci-09","bertolucci","Revolution needs a wide shot.","La rivoluzione ha bisogno di campo lungo.",A,AI),
("bertolucci-10","bertolucci","Dreamers inherit the screen.","I sognatori ereditano lo schermo.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchE added={added} total_en={len(en)} total_it={len(it)}")
