"""Batch G: Italian entrepreneurs 3 (15 authors x 10 = 150 quotes)."""
import json

CAT = "italian_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"lamborghini": ("Ferruccio Lamborghini", "Founder · Lamborghini", "Fondatore · Lamborghini", "1916–1993",
 "Tractor maker who challenged Ferrari and won the bull's roar.",
 "Costruttore di trattori che sfidò Ferrari e vinse il ruggito del toro."),
"maserati": ("Alfieri Maserati", "Founder · Maserati", "Fondatore · Maserati", "1887–1932",
 "Bolognese racer whose trident electrified speed.",
 "Pilota bolognese il cui tridente elettrizzò la velocità."),
"ducati": ("Antonio Cavalieri Ducati", "Founder · Ducati", "Fondatore · Ducati", "19th c.",
 "Bologna pioneer whose name became red speed.",
 "Pioniere bolognese il cui nome divenne velocità rossa."),
"innocenti": ("Ferdinando Innocenti", "Founder · Lambretta", "Fondatore · Lambretta", "1891–1966",
 "Scaffolding maker who scootered postwar Italy.",
 "Costruttore di ponteggi che mise su scooter l'Italia del dopoguerra."),
"marcegaglia": ("Emma Marcegaglia", "Leader · Marcegaglia", "Guida · Marcegaglia", "1965–",
 "Steel leader who chaired Confindustria with resolve.",
 "Leader dell'acciaio che presiedette Confindustria con determinazione."),
"tronchetti": ("Marco Tronchetti Provera", "Leader · Pirelli", "Guida · Pirelli", "1948–",
 "Milan manager steering Pirelli through eras.",
 "Manager milanese al timone Pirelli attraverso le epoche."),
"cairo": ("Urbano Cairo", "Founder · Cairo Communication", "Fondatore · Cairo Communication", "1957–",
 "Turin publisher rebuilding RCS page by page.",
 "Editore torinese che ricostruisce RCS pagina per pagina."),
"montezemolo": ("Luca Cordero di Montezemolo", "Leader · Ferrari", "Guida · Ferrari", "1947–",
 "Bolognese gentleman who revived the prancing horse.",
 "Gentiluomo bolognese che resuscitò il cavallino rampante."),
"marchionne": ("Sergio Marchionne", "Leader · Fiat Chrysler", "Guida · Fiat Chrysler", "1952–2018",
 "Sweatered turnaround artist of Fiat and Chrysler.",
 "Mago dei risanamenti in maglione di Fiat e Chrysler."),
"elkann": ("John Elkann", "Leader · Exor, Ferrari", "Guida · Exor, Ferrari", "1976–",
 "Turin heir investing Agnelli legacy in the future.",
 "Erede torinese che investe l'eredità Agnelli nel futuro."),
"alessi": ("Alberto Alessi", "Leader · Alessi", "Guida · Alessi", "1946–",
 "Crusinallo dreamer turning kettles into sculptures.",
 "Sognatore di Crusinallo che trasforma bollitori in sculture."),
"luti": ("Claudio Luti", "Leader · Kartell", "Guida · Kartell", "1950–",
 "Milan plastic poet of transparent design.",
 "Poeta milanese della plastica del design trasparente."),
"bisazza": ("Piero Bisazza", "Leader · Bisazza", "Guida · Bisazza", "19..–",
 "Vicenza mosaic maker tiling luxury worldwide.",
 "Mosaicista vicentino che piastrella il lusso nel mondo."),
"delonghi": ("Giuseppe De'Longhi", "Leader · De'Longhi", "Guida · De'Longhi", "1939–",
 "Treviso maker of heaters turned coffee rituals.",
 "Costruttore trevigiano di stufe diventato rito del caffè."),
"bertazzoni": ("Vittorio Bertazzoni", "Leader · Smeg", "Guida · Smeg", "19..–",
 "Guastalla cookersmith styling kitchens in fifty colors.",
 "Fabbro guastallese di cucine in cinquanta colori."),
}

Q = [
("lamborghini-01","lamborghini","Tractors taught me torque; pride built supercars.","I trattori mi insegnarono coppia; l'orgoglio le supercar.",S,SI),
("lamborghini-02","lamborghini","If Ferrari won't listen, outbuild him.","Se Ferrari non ascolta, costruisci meglio di lui.",A,AI),
("lamborghini-03","lamborghini","The bull charges, never retreats.","Il toro carica, mai ritirarsi.",A,AI),
("lamborghini-04","lamborghini","Farm mud, Sant'Agata glory.","Fango di fattoria, gloria di Sant'Agata.",A,AI),
("lamborghini-05","lamborghini","V12 or nothing.","V12 o niente.",A,AI),
("lamborghini-06","lamborghini","Miura drew the future's silhouette.","La Miura disegnò la silhouette del futuro.",S,SI),
("lamborghini-07","lamborghini","Mechanics first, myth follows.","Prima la meccanica, poi il mito.",S,SI),
("lamborghini-08","lamborghini","Countach: shock as strategy.","Countach: lo shock come strategia.",A,AI),
("lamborghini-09","lamborghini","Wine after engines, both with patience.","Vino dopo i motori, entrambi con pazienza.",S,SI),
("lamborghini-10","lamborghini","Challenge giants politely, beat them loudly.","Sfida i giganti con garbo, battili forte.",A,AI),
("maserati-01","maserati","The trident strikes at speed.","Il tridente colpisce in velocità.",A,AI),
("maserati-02","maserati","Brothers race, legends follow.","I fratelli corrono, le leggende seguono.",S,SI),
("maserati-03","maserati","Bologna's spark plugs ignite history.","Le candele di Bologna accendono la storia.",A,AI),
("maserati-04","maserati","Targa Florio rewards the brave.","La Targa Florio premia i coraggiosi.",S,SI),
("maserati-05","maserati","Tune engines, tune destiny.","Accorda motori, accorda destini.",A,AI),
("maserati-06","maserati","Neptune guides fast waters.","Nettuno guida acque veloci.",A,AI),
("maserati-07","maserati","Workshop smoke, podium glory.","Fumo d'officina, gloria di podio.",A,AI),
("maserati-08","maserati","Six brothers, one roar.","Sei fratelli, un ruggito.",S,SI),
("maserati-09","maserati","Elegance at 200 an hour.","Eleganza a 200 all'ora.",A,AI),
("maserati-10","maserati","Modena remembers every lap.","Modena ricorda ogni giro.",A,AI),
("ducati-01","ducati","Red is a racing promise.","Il rosso è una promessa da corsa.",A,AI),
("ducati-02","ducati","Desmo valves sing precision.","Le valvole desmo cantano precisione.",C,CI),
("ducati-03","ducati","Borgo Panigale bleeds speed.","Borgo Panigale sanguina velocità.",A,AI),
("ducati-04","ducati","Radio parts became roaring hearts.","Parti radio divennero cuori ruggenti.",S,SI),
("ducati-05","ducati","Lean into every curve.","Piegati in ogni curva.",A,AI),
("ducati-06","ducati","Twin cylinders, twin passions.","Bicilindrici, doppie passioni.",C,CI),
("ducati-07","ducati","Win Sunday, sell Monday.","Vinci domenica, vendi lunedì.",A,AI),
("ducati-08","ducati","Light frames, heavy dreams.","Telai leggeri, sogni pesanti.",A,AI),
("ducati-09","ducati","The island of Man tests men.","L'isola di Man mette alla prova gli uomini.",S,SI),
("ducati-10","ducati","Style at full throttle.","Stile a tutto gas.",A,AI),
("innocenti-01","innocenti","Scaffolds held buildings; scooters hold freedom.","I ponteggi tenevano edifici; gli scooter la libertà.",S,SI),
("innocenti-02","innocenti","Lambretta: Milan's wasp.","Lambretta: la vespa di Milano.",A,AI),
("innocenti-03","innocenti","Rebuild Italy on two wheels.","Ricostruisci l'Italia su due ruote.",S,SI),
("innocenti-04","innocenti","Steel tubes, endless roads.","Tubi d'acciaio, strade infinite.",C,CI),
("innocenti-05","innocenti","Workers deserve wings.","Gli operai meritano ali.",A,AI),
("innocenti-06","innocenti","Lambrate hums with engines.","Lambrate ronza di motori.",A,AI),
("innocenti-07","innocenti","Simple machines, grand mobility.","Macchine semplici, grande mobilità.",C,CI),
("innocenti-08","innocenti","Rival the best, price for all.","Sfida i migliori, prezzo per tutti.",S,SI),
("innocenti-09","innocenti","Postwar grey needs chrome.","Il grigio del dopoguerra ha bisogno di cromo.",A,AI),
("innocenti-10","innocenti","Move the masses beautifully.","Muovi le masse con bellezza.",A,AI),
("marcegaglia-01","marcegaglia","Steel bends to will.","L'acciaio si piega alla volontà.",S,SI),
("marcegaglia-02","marcegaglia","Mantua forges ahead.","Mantova forgia in avanti.",S,SI),
("marcegaglia-03","marcegaglia","Lead industry, serve country.","Guida l'industria, servi il paese.",S,SI),
("marcegaglia-04","marcegaglia","Family steel, global spine.","Acciaio di famiglia, spina globale.",C,CI),
("marcegaglia-05","marcegaglia","Resolve rolls coils.","La determinazione lamina rotoli.",A,AI),
("marcegaglia-06","marcegaglia","Women lead furnaces too.","Anche le donne guidano fornaci.",S,SI),
("marcegaglia-07","marcegaglia","Crisis tempers leaders.","La crisi tempra i leader.",S,SI),
("marcegaglia-08","marcegaglia","Export strength, import ideas.","Esporta forza, importa idee.",S,SI),
("marcegaglia-09","marcegaglia","Sustainability steels tomorrow.","La sostenibilità acciaia il domani.",C,CI),
("marcegaglia-10","marcegaglia","Speak plainly, act firmly.","Parla chiaro, agisci fermo.",S,SI),
("tronchetti-01","tronchetti","Steer through eras, keep the brand.","Guida attraverso le epoche, conserva il marchio.",S,SI),
("tronchetti-02","tronchetti","Calcio teaches management.","Il calcio insegna management.",S,SI),
("tronchetti-03","tronchetti","Long vision, quick decisions.","Visione lunga, decisioni rapide.",S,SI),
("tronchetti-04","tronchetti","Milan negotiates worldwide.","Milano negozia nel mondo.",A,AI),
("tronchetti-05","tronchetti","Tyres grip change.","Gli pneumatici afferrano il cambiamento.",C,CI),
("tronchetti-06","tronchetti","Alliances need backbones.","Le alleanze hanno bisogno di spina dorsale.",S,SI),
("tronchetti-07","tronchetti","Elegance in the boardroom.","Eleganza in consiglio.",A,AI),
("tronchetti-08","tronchetti","Patience compounds control.","La pazienza accumula controllo.",A,AI),
("tronchetti-09","tronchetti","Global capital, Italian heart.","Capitale globale, cuore italiano.",S,SI),
("tronchetti-10","tronchetti","Endure, adapt, lead.","Resisti, adattati, guida.",S,SI),
("cairo-01","cairo","Rebuild pages daily.","Ricostruisci pagine ogni giorno.",S,SI),
("cairo-02","cairo","Newspapers survive by truth.","I giornali sopravvivono di verità.",S,SI),
("cairo-03","cairo","Turin edits with patience.","Torino corregge con pazienza.",A,AI),
("cairo-04","cairo","Giro d'Italia pedals ink.","Il Giro pedala inchiostro.",S,SI),
("cairo-05","cairo","Debts demand discipline.","I debiti esigono disciplina.",S,SI),
("cairo-06","cairo","Print at dawn, decide at dusk.","Stampa all'alba, decidi al tramonto.",A,AI),
("cairo-07","cairo","Football funds the press.","Il calcio finanzia la stampa.",S,SI),
("cairo-08","cairo","Corriere carries history.","Il Corriere porta la storia.",S,SI),
("cairo-09","cairo","Advertise wisely, invest boldly.","Pubblicizza saggio, investi audace.",C,CI),
("cairo-10","cairo","Owners serve readers.","Gli editori servono i lettori.",S,SI),
("montezemolo-01","montezemolo","Revive the horse, honor the myth.","Resuscita il cavallo, onora il mito.",S,SI),
("montezemolo-02","montezemolo","Winning restores aura.","Vincere restaura l'aura.",S,SI),
("montezemolo-03","montezemolo","Schumacher drove renaissance.","Schumacher guidò la rinascita.",S,SI),
("montezemolo-04","montezemolo","Elegance manages speed.","L'eleganza gestisce la velocità.",A,AI),
("montezemolo-05","montezemolo","Maranello dreams in red.","Maranello sogna in rosso.",S,SI),
("montezemolo-06","montezemolo","Teams win championships.","I team vincono campionati.",C,CI),
("montezemolo-07","montezemolo","Bologna manners, global podiums.","Maniere bolognesi, podi globali.",A,AI),
("montezemolo-08","montezemolo","Luxury needs racing soul.","Il lusso ha bisogno di anima racing.",C,CI),
("montezemolo-09","montezemolo","Trains can run on time.","I treni possono arrivare in orario.",S,SI),
("montezemolo-10","montezemolo","Charm opens pit lanes.","Il fascino apre le pit lane.",A,AI),
("marchionne-01","marchionne","Mediocrity is not worth the trip.","La mediocrità non vale il viaggio.",S,SI),
("marchionne-02","marchionne","Wear the sweater, do the work.","Indossa il maglione, fai il lavoro.",S,SI),
("marchionne-03","marchionne","Numbers tell, leaders decide.","I numeri raccontano, i leader decidono.",S,SI),
("marchionne-04","marchionne","Merge or die trying.","Fondi o muori provandoci.",S,SI),
("marchionne-05","marchionne","Detroit respects results.","Detroit rispetta i risultati.",S,SI),
("marchionne-06","marchionne","Sleep little, fix much.","Dormi poco, sistema molto.",A,AI),
("marchionne-07","marchionne","Culture eats strategy daily.","La cultura mangia strategia ogni giorno.",A,AI),
("marchionne-08","marchionne","Smoke, think, execute.","Fuma, pensa, esegui.",A,AI),
("marchionne-09","marchionne","Turnarounds need truth.","I risanamenti hanno bisogno di verità.",S,SI),
("marchionne-10","marchionne","Leave companies stronger.","Lascia le aziende più forti.",S,SI),
("elkann-01","elkann","Invest the legacy forward.","Investi l'eredità in avanti.",S,SI),
("elkann-02","elkann","Turin roots, global portfolio.","Radici torinesi, portafoglio globale.",S,SI),
("elkann-03","elkann","Patience owns the future.","La pazienza possiede il futuro.",S,SI),
("elkann-04","elkann","Ferrari deserves obsession.","La Ferrari merita ossessione.",S,SI),
("elkann-05","elkann","Letters teach leadership.","Le lettere insegnano leadership.",A,AI),
("elkann-06","elkann","Back founders early.","Sostieni i fondatori presto.",C,CI),
("elkann-07","elkann","Stellantis scales history.","Stellantis scala la storia.",S,SI),
("elkann-08","elkann","Philanthropy with method.","Filantropia con metodo.",S,SI),
("elkann-09","elkann","Quiet capital, loud results.","Capitale silenzioso, risultati forti.",A,AI),
("elkann-10","elkann","Agnelli means long term.","Agnelli significa lungo periodo.",S,SI),
("alessi-01","alessi","Kettles can be sculptures.","I bollitori possono essere sculture.",S,SI),
("alessi-02","alessi","Dream with designers.","Sogna con i designer.",C,CI),
("alessi-03","alessi","Crusinallo crafts joy.","Crusinallo artigiana gioia.",A,AI),
("alessi-04","alessi","Playful steel sells.","L'acciaio giocoso vende.",C,CI),
("alessi-05","alessi","Starck whistles in kitchens.","Starck fischia in cucina.",S,SI),
("alessi-06","alessi","Factories of dreams, not just goods.","Fabbriche di sogni, non solo merci.",S,SI),
("alessi-07","alessi","Humor belongs on tables.","L'umorismo appartiene alle tavole.",C,CI),
("alessi-08","alessi","Borderline products win hearts.","I prodotti borderline vincono cuori.",S,SI),
("alessi-09","alessi","Lake Orta reflects ideas.","Il lago d'Orta riflette idee.",A,AI),
("alessi-10","alessi","Poetry pays.","La poesia paga.",A,AI),
("luti-01","luti","Plastic can be poetry.","La plastica può essere poesia.",S,SI),
("luti-02","luti","Transparency reveals design.","La trasparenza rivela il design.",C,CI),
("luti-03","luti","Kartell chairs the world.","Kartell presiede il mondo.",A,AI),
("luti-04","luti","Milan molds the future.","Milano modella il futuro.",S,SI),
("luti-05","luti","Starck ghosts haunt beautifully.","I fantasmi di Starck infestano bellissimi.",A,AI),
("luti-06","luti","Color in polycarbonate.","Colore in policarbonato.",C,CI),
("luti-07","luti","Design democratizes luxury.","Il design democratizza il lusso.",S,SI),
("luti-08","luti","Museums stock our shelves.","I musei riforniscono i nostri scaffali.",S,SI),
("luti-09","luti","Light passes, form stays.","La luce passa, la forma resta.",A,AI),
("luti-10","luti","Bourgie lights ideas.","Bourgie illumina idee.",A,AI),
("bisazza-01","bisazza","Mosaics tile luxury.","I mosaici piastrellano il lusso.",C,CI),
("bisazza-02","bisazza","Glass tesserae, golden rooms.","Tessere di vetro, stanze dorate.",A,AI),
("bisazza-03","bisazza","Vicenza details dazzle.","I dettagli vicentini abbagliano.",S,SI),
("bisazza-04","bisazza","Blends color architecture.","Le miscele colorano architettura.",C,CI),
("bisazza-05","bisazza","Spas wear our skin.","Le spa vestono la nostra pelle.",A,AI),
("bisazza-06","bisazza","Artisans place millions.","Gli artigiani posano milioni.",C,CI),
("bisazza-07","bisazza","Fashion houses bathe here.","Le maison fanno il bagno qui.",A,AI),
("bisazza-08","bisazza","Shimmer with restraint.","Brilla con misura.",A,AI),
("bisazza-09","bisazza","Montebello fires beauty.","Montebello cuoce bellezza.",S,SI),
("bisazza-10","bisazza","Small tiles, vast surfaces.","Piccole tessere, vaste superfici.",C,CI),
("delonghi-01","delonghi","Heaters warmed hands; coffee warms souls.","Le stufe scaldavano mani; il caffè scalda anime.",S,SI),
("delonghi-02","delonghi","Treviso engineers rituals.","Treviso ingegnerizza riti.",C,CI),
("delonghi-03","delonghi","Better beans through better machines.","Migliori chicchi con migliori macchine.",C,CI),
("delonghi-04","delonghi","Espresso at home, café in heart.","Espresso a casa, caffè nel cuore.",C,CI),
("delonghi-05","delonghi","Design the morning.","Disegna il mattino.",A,AI),
("delonghi-06","delonghi","Quiet machines, loud aroma.","Macchine silenziose, aroma forte.",C,CI),
("delonghi-07","delonghi","Acquire wisely, integrate kindly.","Acquisisci saggio, integra gentile.",S,SI),
("delonghi-08","delonghi","Kenwood kneads the world.","Kenwood impasta il mondo.",S,SI),
("delonghi-09","delonghi","Comfort has buttons.","Il comfort ha pulsanti.",A,AI),
("delonghi-10","delonghi","From radiators to rituals.","Dai radiatori ai riti.",S,SI),
("bertazzoni-01","bertazzoni","Cookers in fifty colors.","Cucine in cinquanta colori.",C,CI),
("bertazzoni-02","bertazzoni","Guastalla fires flavor.","Guastalla cuoce sapore.",A,AI),
("bertazzoni-03","bertazzoni","Family ovens since forever.","Forni di famiglia da sempre.",C,CI),
("bertazzoni-04","bertazzoni","Style simmers slowly.","Lo stile sobbollisce piano.",A,AI),
("bertazzoni-05","bertazzoni","Chefs choose our flames.","Gli chef scelgono le nostre fiamme.",C,CI),
("bertazzoni-06","bertazzoni","Enamel like Emilia's sunsets.","Smalto come i tramonti emiliani.",A,AI),
("bertazzoni-07","bertazzoni","Six generations, one heat.","Sei generazioni, un solo calore.",S,SI),
("bertazzoni-08","bertazzoni","Kitchens wear couture.","Le cucine vestono couture.",A,AI),
("bertazzoni-09","bertazzoni","Precision bakes passion.","La precisione cuoce passione.",C,CI),
("bertazzoni-10","bertazzoni","Heritage heats forward.","L'eredità scalda in avanti.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchG added={added} total_en={len(en)} total_it={len(it)}")
