"""Batch J: cinema directors 2 (17 x 10 = 170)."""
import json

CAT = "cinema"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"

AUTHORS = {
"welles": ("Orson Welles", "Director · Citizen Kane", "Regista · Quarto potere", "1915–1985",
 "Kenosha prodigy who shook radio and cinema alike.",
 "Prodigio di Kenosha che scosse radio e cinema."),
"capra": ("Frank Capra", "Director · Wonderful Life", "Regista · La vita è meravigliosa", "1897–1991",
 "Sicilian immigrant filming American decency.",
 "Immigrato siciliano che filmò la decenza americana."),
"hawks": ("Howard Hawks", "Director · Rio Bravo", "Regista · Rio Bravo", "1896–1977",
 "Goshen professional filming men at work.",
 "Professionista di Goshen che filmò uomini al lavoro."),
"wilder": ("Billy Wilder", "Director · Sunset Blvd", "Regista · Viale del tramonto", "1906–2002",
 "Viennese cynic writing Hollywood's sharpest lines.",
 "Cinico viennese che scrisse le battute più taglienti di Hollywood."),
"huston": ("John Huston", "Director · Maltese Falcon", "Regista · Il mistero del falco", "1906–1987",
 "Missouri adventurer hunting falcons and whales.",
 "Avventuriero del Missouri a caccia di falchi e balene."),
"kazan": ("Elia Kazan", "Director · On the Waterfront", "Regista · Fronte del porto", "1909–2003",
 "Anatolian actor-director of raw intensity.",
 "Attore-regista anatolico di cruda intensità."),
"lynch": ("David Lynch", "Director · Blue Velvet", "Regista · Velluto blu", "1946–2025",
 "Montana dreamer filming suburbia's dark underbelly.",
 "Sognatore del Montana che filmò il ventre oscuro della provincia."),
"coenj": ("Joel Coen", "Director · Fargo, Big Lebowski", "Regista · Fargo, Il grande Lebowski", "1954–",
 "Minnesota minimalist of chaos with brother Ethan.",
 "Minimalista del Minnesota del caos col fratello Ethan."),
"wesanderson": ("Wes Anderson", "Director · Grand Budapest", "Regista · Grand Budapest Hotel", "1969–",
 "Houston symmetrist of pastel melancholy.",
 "Simmetrista di Houston di malinconia pastello."),
"nolan": ("Christopher Nolan", "Director · Inception", "Regista · Inception", "1970–",
 "London clockmaker bending time on IMAX.",
 "Orologiaio londinese che piega il tempo in IMAX."),
"villeneuve": ("Denis Villeneuve", "Director · Dune", "Regista · Dune", "1967–",
 "Québec architect of sand and silence.",
 "Architetto del Québec di sabbia e silenzio."),
"cuaron": ("Alfonso Cuarón", "Director · Roma, Gravity", "Regista · Roma, Gravity", "1961–",
 "Mexico City floater of long takes and memory.",
 "Galleggiante di Città del Messico di piani sequenza e memoria."),
"inarritu": ("Alejandro G. Iñárritu", "Director · Birdman", "Regista · Birdman", "1963–",
 "Mexico City weaver of fractured fates.",
 "Tessitore di Città del Messico di destini frammentati."),
"deltoro": ("Guillermo del Toro", "Director · Shape of Water", "Regista · La forma dell'acqua", "1964–",
 "Guadalajara monster-lover with a tender heart.",
 "Amante dei mostri di Guadalajara dal cuore tenero."),
"wong": ("Wong Kar-wai", "Director · In the Mood", "Regista · In the Mood for Love", "1958–",
 "Shanghai romantic filming neon goodbyes.",
 "Romantico di Shanghai che filma addii al neon."),
"mizoguchi": ("Kenji Mizoguchi", "Director · Ugetsu", "Regista · Ugetsu", "1898–1956",
 "Tokyo painter of suffering women and mist.",
 "Pittore di Tokyo di donne sofferenti e nebbia."),
"kieslowski": ("Krzysztof Kieślowski", "Director · Dekalog", "Regista · Decalogo", "1941–1996",
 "Polish moralist filming commandments in grey blocks.",
 "Moralista polacco che filmò comandamenti in palazzi grigi."),
}

Q = [
("welles-01","welles","Rosebud hides every childhood.","Rosabella nasconde ogni infanzia.",A,AI),
("welles-02","welles","Martians panic better than critics.","I marziani creano panico meglio dei critici.",A,AI),
("welles-03","welles","A film studio is the greatest train set.","Uno studio è il più grande trenino.",A,AI),
("welles-04","welles","Touch of evil, touch of genius.","Tocco di male, tocco di genio.",A,AI),
("welles-05","welles","Kenosha boys dream biggest.","I ragazzi di Kenosha sognano più grande.",A,AI),
("welles-06","welles","Shadows speak Shakespeare.","Le ombre parlano Shakespeare.",A,AI),
("welles-07","welles","Wine improves monologues.","Il vino migliora i monologhi.",A,AI),
("welles-08","welles","Deep focus, deeper ambition.","Profondità di campo, ambizione più profonda.",S,SI),
("welles-09","welles","Radio panics, cinema endures.","La radio panica, il cinema dura.",S,SI),
("welles-10","welles","Greatness needs final cuts.","La grandezza ha bisogno di final cut.",A,AI),
("capra-01","capra","Every man is George Bailey.","Ogni uomo è George Bailey.",S,SI),
("capra-02","capra","Sicily sails to Bedford Falls.","La Sicilia naviga a Bedford Falls.",A,AI),
("capra-03","capra","Decency defeats cynicism.","La decenza sconfigge il cinismo.",S,SI),
("capra-04","capra","Bells ring for angels.","Le campane suonano per gli angeli.",A,AI),
("capra-05","capra","Mr. Smith filibusters despair.","Mr. Smith ostruziona la disperazione.",A,AI),
("capra-06","capra","Christmas saves cynics.","Il Natale salva i cinici.",A,AI),
("capra-07","capra","Small towns hold big hearts.","Le piccole città custodiscono grandi cuori.",S,SI),
("capra-08","capra","Capra-corn feeds hope.","Il Capra-corn nutre speranza.",A,AI),
("capra-09","capra","Wonderful lives need friends.","Le vite meravigliose hanno bisogno di amici.",S,SI),
("capra-10","capra","Idealism photographs well.","L'idealismo fotografa bene.",S,SI),
("hawks-01","hawks","A good movie has three great scenes.","Un buon film ha tre grandi scene.",A,AI),
("hawks-02","hawks","Men at work, women sparring.","Uomini al lavoro, donne che duellano.",S,SI),
("hawks-03","hawks","Rio Bravo holds the line.","Rio Bravo tiene la linea.",S,SI),
("hawks-04","hawks","Screwball needs timing.","Lo screwball ha bisogno di tempi.",S,SI),
("hawks-05","hawks","Professionals improvise.","I professionisti improvvisano.",A,AI),
("hawks-06","hawks","Goshen grit, Hollywood gold.","Grinta di Goshen, oro di Hollywood.",A,AI),
("hawks-07","hawks","Leopards change leading ladies.","I leopardi cambiano prime donne.",A,AI),
("hawks-08","hawks","Flying planes, filming faster.","Pilotare aerei, filmare più veloce.",A,AI),
("hawks-09","hawks","Hatari hunts honesty.","Hatari caccia onestà.",A,AI),
("hawks-10","hawks","Genre is a tool, not a cage.","Il genere è uno strumento, non una gabbia.",S,SI),
("wilder-01","wilder","Nobody's perfect, especially endings.","Nessuno è perfetto, specie i finali.",A,AI),
("wilder-02","wilder","Sunset fades, dialogue stays.","Il tramonto sfuma, i dialoghi restano.",S,SI),
("wilder-03","wilder","Vienna wit, Hollywood bite.","Arguzia viennese, morso di Hollywood.",A,AI),
("wilder-04","wilder","Some like it cynical.","A qualcuno piace cinico.",A,AI),
("wilder-05","wilder","Apartments hide affairs.","Gli appartamenti nascondono relazioni.",A,AI),
("wilder-06","wilder","Write drunk on structure.","Scrivi ubriaco di struttura.",A,AI),
("wilder-07","wilder","Audiences are smarter than studios.","Il pubblico è più sveglio degli studio.",S,SI),
("wilder-08","wilder","Double indemnity, double pleasure.","Doppia indennità, doppio piacere.",A,AI),
("wilder-09","wilder","Exile sharpens jokes.","L'esilio affila le battute.",S,SI),
("wilder-10","wilder","Close-ups need cruelty.","I primi piani hanno bisogno di crudeltà.",A,AI),
("huston-01","huston","The falcon flies darkest.","Il falco vola più scuro.",A,AI),
("huston-02","huston","Whales humble captains.","Le balene umiliano i capitani.",A,AI),
("huston-03","huston","Missouri grit, Irish mist.","Grinta del Missouri, nebbia irlandese.",A,AI),
("huston-04","huston","Treasure maddens men.","Il tesoro fa impazzire gli uomini.",A,AI),
("huston-05","huston","Paint, box, film, repeat.","Dipingi, boxa, filma, ripeti.",S,SI),
("huston-06","huston","Africa tests auteurs.","L'Africa mette alla prova gli autori.",S,SI),
("huston-07","huston","Bogart smirks forever.","Bogart sogghigna per sempre.",A,AI),
("huston-08","huston","Gamble on every picture.","Scommetti su ogni film.",S,SI),
("huston-09","huston","Volcanoes end stories.","I vulcani chiudono le storie.",A,AI),
("huston-10","huston","Adventures direct themselves.","Le avventure si dirigono da sole.",A,AI),
("kazan-01","kazan","I coulda been a contender.","Potevo essere un campione.",A,AI),
("kazan-02","kazan","Actors bleed truth.","Gli attori sanguinano verità.",S,SI),
("kazan-03","kazan","Waterfronts test conscience.","I porti mettono alla prova la coscienza.",S,SI),
("kazan-04","kazan","Anatolia burns in method.","L'Anatolia brucia nel metodo.",A,AI),
("kazan-05","kazan","Brando mumbles thunder.","Brando borbotta tuoni.",S,SI),
("kazan-06","kazan","East of Eden aches.","La valle dell'Eden duole.",A,AI),
("kazan-07","kazan","Testify, then film.","Testimonia, poi filma.",S,SI),
("kazan-08","kazan","Group Theatre forged fire.","Il Group Theatre forgiò fuoco.",S,SI),
("kazan-09","kazan","Desire streetcars screech.","I tram del desiderio stridono.",A,AI),
("kazan-10","kazan","America splits audiences.","L'America divide il pubblico.",A,AI),
("lynch-01","lynch","Owls are not what they seem.","I gufi non sono ciò che sembrano.",A,AI),
("lynch-02","lynch","Suburbia hides velvet darkness.","La provincia nasconde oscurità di velluto.",S,SI),
("lynch-03","lynch","Meditate, then disturb.","Medita, poi turba.",S,SI),
("lynch-04","lynch","Montana skies birth nightmares.","I cieli del Montana partoriscono incubi.",A,AI),
("lynch-05","lynch","Coffee and cherry pie solve.","Caffè e torta di ciliegie risolvono.",A,AI),
("lynch-06","lynch","Damn fine sound design.","Dannatamente buon sound design.",A,AI),
("lynch-07","lynch","Eraserheads fear fatherhood.","Gli Eraserhead temono la paternità.",A,AI),
("lynch-08","lynch","Mulholland dreams deceive.","Mulholland sogna inganni.",A,AI),
("lynch-09","lynch","Red rooms loop forever.","Le stanze rosse girano per sempre.",A,AI),
("lynch-10","lynch","Ideas arrive like fish.","Le idee arrivano come pesci.",S,SI),
("coenj-01","coenj","Fargo snows absurdity.","Fargo nevica assurdità.",S,SI),
("coenj-02","coenj","The Dude abides always.","Il Drugo resiste sempre.",A,AI),
("coenj-03","coenj","Minnesota nice, noir mean.","Gentilezza del Minnesota, noir cattivo.",A,AI),
("coenj-04","coenj","Woodchippers grind greed.","Le cippatrici macinano avidità.",A,AI),
("coenj-05","coenj","Brothers share one brain.","I fratelli condividono un cervello.",S,SI),
("coenj-06","coenj","No Country spares none.","Non è un paese per vecchi non risparmia nessuno.",A,AI),
("coenj-07","coenj","Raising Arizona amplifies.","Arizona Junior amplifica.",A,AI),
("coenj-08","coenj","O Brother sings escape.","Fratello, dove sei? canta fuga.",A,AI),
("coenj-09","coenj","Rugs tie rooms together.","I tappeti legano le stanze.",A,AI),
("coenj-10","coenj","Blood simple, plots complex.","Sangue facile, trame complesse.",S,SI),
("wesanderson-01","wesanderson","Symmetry soothes chaos.","La simmetria lenisce il caos.",S,SI),
("wesanderson-02","wesanderson","Pastels mourn politely.","I pastelli piangono educati.",A,AI),
("wesanderson-03","wesanderson","Houston plans every frame.","Houston pianifica ogni inquadratura.",S,SI),
("wesanderson-04","wesanderson","Budapest hotels host ghosts.","Gli hotel di Budapest ospitano fantasmi.",A,AI),
("wesanderson-05","wesanderson","Foxes steal melancholy.","Le volpi rubano malinconia.",A,AI),
("wesanderson-06","wesanderson","Tenenbaums fail beautifully.","I Tenenbaum falliscono bellissimi.",A,AI),
("wesanderson-07","wesanderson","Trains carry whimsy.","I treni portano bizzarria.",A,AI),
("wesanderson-08","wesanderson","Dioramas direct feelings.","I diorami dirigono sentimenti.",S,SI),
("wesanderson-09","wesanderson","Futura types nostalgia.","Futura compone nostalgia.",A,AI),
("wesanderson-10","wesanderson","Islands isolate love.","Le isole isolano l'amore.",A,AI),
("nolan-01","nolan","Time folds, IMAX unfolds.","Il tempo si piega, IMAX si spiega.",S,SI),
("nolan-02","nolan","Dreams need architects.","I sogni hanno bisogno di architetti.",S,SI),
("nolan-03","nolan","Celluloid over pixels.","Pellicola sopra i pixel.",S,SI),
("nolan-04","nolan","Batman broods in daylight.","Batman rimugina alla luce.",A,AI),
("nolan-05","nolan","Interstellar loves relativity.","Interstellar ama la relatività.",S,SI),
("nolan-06","nolan","London boys build mazes.","I ragazzi di Londra costruiscono labirinti.",A,AI),
("nolan-07","nolan","Oppenheimer burns brightly.","Oppenheimer brucia luminoso.",S,SI),
("nolan-08","nolan","Practical effects, impossible feelings.","Effetti pratici, sentimenti impossibili.",S,SI),
("nolan-09","nolan","Tenet inverts patience.","Tenet inverte la pazienza.",A,AI),
("nolan-10","nolan","Dunkirk ticks survival.","Dunkirk scandisce sopravvivenza.",S,SI),
("villeneuve-01","villeneuve","Sand sings in silence.","La sabbia canta in silenzio.",S,SI),
("villeneuve-02","villeneuve","Québec winters forge epics.","Gli inverni del Québec forgiano epopee.",A,AI),
("villeneuve-03","villeneuve","Arrival translates grief.","Arrival traduce dolore.",S,SI),
("villeneuve-04","villeneuve","Blade runners rust beautifully.","I blade runner arrugginiscono bellissimi.",S,SI),
("villeneuve-05","villeneuve","Dune demands patience.","Dune esige pazienza.",S,SI),
("villeneuve-06","villeneuve","Sicario borders blur.","Sicario sfuma confini.",A,AI),
("villeneuve-07","villeneuve","Scale humbles characters.","La scala umilia i personaggi.",S,SI),
("villeneuve-08","villeneuve","Desert power needs restraint.","Il potere del deserto ha bisogno di misura.",A,AI),
("villeneuve-09","villeneuve","Sound designs dread.","Il suono disegna terrore.",S,SI),
("villeneuve-10","villeneuve","Slow cinema, vast soul.","Cinema lento, anima vasta.",A,AI),
("cuaron-01","cuaron","Long takes hold breath.","I piani sequenza trattengono il respiro.",S,SI),
("cuaron-02","cuaron","Roma remembers maids.","Roma ricorda le domestiche.",S,SI),
("cuaron-03","cuaron","Gravity floats grief.","Gravity fa galleggiare il dolore.",S,SI),
("cuaron-04","cuaron","Mexico City floods memory.","Città del Messico inonda memoria.",S,SI),
("cuaron-05","cuaron","Children run through coups.","I bambini corrono tra colpi di stato.",A,AI),
("cuaron-06","cuaron","Digital cameras liberate.","Le camere digitali liberano.",S,SI),
("cuaron-07","cuaron","Cleo cleans frames.","Cleo pulisce inquadrature.",A,AI),
("cuaron-08","cuaron","Space silences mothers.","Lo spazio silenzia madri.",A,AI),
("cuaron-09","cuaron","One shot, many lives.","Un piano, molte vite.",S,SI),
("cuaron-10","cuaron","Water breaks, films flow.","Le acque si rompono, i film scorrono.",A,AI),
("inarritu-01","inarritu","Fates fracture beautifully.","I destini si fratturano bellissimi.",S,SI),
("inarritu-02","inarritu","Birdman flies in one take.","Birdman vola in un piano.",S,SI),
("inarritu-03","inarritu","Revenants crawl for Oscars.","I revenant strisciano per Oscar.",A,AI),
("inarritu-04","inarritu","Mexico City intersections collide.","Gli incroci di Città del Messico collidono.",S,SI),
("inarritu-05","inarritu","Drums drive dread.","I tamburi guidano terrore.",A,AI),
("inarritu-06","inarritu","Lubezki lights labyrinths.","Lubezki illumina labirinti.",S,SI),
("inarritu-07","inarritu","Radio hosted hunger.","La radio ospitò fame.",A,AI),
("inarritu-08","inarritu","Amores perros bite.","Amores perros mordono.",A,AI),
("inarritu-09","inarritu","Snow buries vengeance.","La neve seppellisce vendetta.",A,AI),
("inarritu-10","inarritu","Egos soar, then splat.","Gli ego volano, poi spiaccicano.",A,AI),
("deltoro-01","deltoro","Monsters love tenderly.","I mostri amano teneramente.",S,SI),
("deltoro-02","deltoro","Guadalajara ghosts guide.","I fantasmi di Guadalajara guidano.",S,SI),
("deltoro-03","deltoro","Water shapes longing.","L'acqua plasma desiderio.",S,SI),
("deltoro-04","deltoro","Fauns test obedience.","I fauni testano obbedienza.",A,AI),
("deltoro-05","deltoro","Bleak House brims with beasts.","Bleak House trabocca di bestie.",A,AI),
("deltoro-06","deltoro","Pinocchio woodens wisdom.","Pinocchio ligneo saggezza.",S,SI),
("deltoro-07","deltoro","Crimson peaks bleed.","Le cime cremisi sanguinano.",A,AI),
("deltoro-08","deltoro","Insects inspire auteurs.","Gli insetti ispirano autori.",A,AI),
("deltoro-09","deltoro","Hellboys punch Nazis.","Gli Hellboy picchiano nazisti.",A,AI),
("deltoro-10","deltoro","Fairy tales bite back.","Le fiabe mordono indietro.",S,SI),
("wong-01","wong","Neon goodbyes linger.","Gli addii al neon indugiano.",S,SI),
("wong-02","wong","Clock ticks 2046.","L'orologio scandisce 2046.",A,AI),
("wong-03","wong","Noodles steam longing.","I noodles fumano desiderio.",A,AI),
("wong-04","wong","Shanghai sways in cheongsam.","Shanghai ondeggia in cheongsam.",A,AI),
("wong-05","wong","Expiring pineapples expire love.","Gli ananas scaduti scadono amore.",A,AI),
("wong-06","wong","Hotel rooms host almost.","Le stanze d'hotel ospitano quasi.",A,AI),
("wong-07","wong","Doyle frames haze.","Doyle inquadra foschia.",S,SI),
("wong-08","wong","Time zones ache.","I fusi orari dolgono.",A,AI),
("wong-09","wong","Fallen angels fly low.","Gli angeli caduti volano bassi.",A,AI),
("wong-10","wong","Love needs a timepiece.","L'amore ha bisogno di un orologio.",A,AI),
("mizoguchi-01","mizoguchi","Mist veils suffering women.","La nebbia vela donne sofferenti.",S,SI),
("mizoguchi-02","mizoguchi","One shot, one sorrow.","Un piano, un dolore.",S,SI),
("mizoguchi-03","mizoguchi","Kyoto weeps elegantly.","Kyoto piange elegante.",A,AI),
("mizoguchi-04","mizoguchi","Ugetsu moons madness.","Ugetsu illuna follia.",A,AI),
("mizoguchi-05","mizoguchi","Courtesans accuse history.","Le cortigiane accusano la storia.",S,SI),
("mizoguchi-06","mizoguchi","Rain directs grief.","La pioggia dirige dolore.",A,AI),
("mizoguchi-07","mizoguchi","Cranes cross injustice.","Le gru attraversano ingiustizia.",A,AI),
("mizoguchi-08","mizoguchi","Empathy needs long takes.","L'empatia ha bisogno di piani lunghi.",S,SI),
("mizoguchi-09","mizoguchi","Osaka nights confess.","Le notti di Osaka confessano.",A,AI),
("mizoguchi-10","mizoguchi","Life of Oharu endures.","La vita di Oharu dura.",A,AI),
("kieslowski-01","kieslowski","Grey blocks hide commandments.","I palazzi grigi nascondono comandamenti.",S,SI),
("kieslowski-02","kieslowski","Blue liberates grief.","Il blu libera dolore.",S,SI),
("kieslowski-03","kieslowski","White freezes fraternity.","Il bianco congela fratellanza.",A,AI),
("kieslowski-04","kieslowski","Red entangles fate.","Il rosso intreccia destino.",A,AI),
("kieslowski-05","kieslowski","Dekalog counts souls.","Il Decalogo conta anime.",S,SI),
("kieslowski-06","kieslowski","Chance kisses baldness.","Il caso bacia calvizie.",A,AI),
("kieslowski-07","kieslowski","Veronique doubles music.","Veronique raddoppia musica.",A,AI),
("kieslowski-08","kieslowski","Amateurs film truth.","I dilettanti filmano verità.",S,SI),
("kieslowski-09","kieslowski","Poland questions quietly.","La Polonia interroga piano.",A,AI),
("kieslowski-10","kieslowski","Endings remain open.","I finali restano aperti.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchJ added={added} total_en={len(en)} total_it={len(it)}")
