"""Batch I: international entrepreneurs 4, modern tech (17 x 10 = 170)."""
import json

CAT = "international_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"page": ("Larry Page", "Co-founder · Google", "Co-fondatore · Google", "1973–",
 "Stanford dreamer ranking the world's information.",
 "Sognatore di Stanford che classifica l'informazione mondiale."),
"brin": ("Sergey Brin", "Co-founder · Google", "Co-fondatore · Google", "1973–",
 "Moscow-born miner of data and moonshots.",
 "Minatore di dati e moonshot nato a Mosca."),
"zuckerberg": ("Mark Zuckerberg", "Co-founder · Meta", "Co-fondatore · Meta", "1984–",
 "Dorm-room coder connecting billions, for better and worse.",
 "Programmatore da dormitorio che connette miliardi, nel bene e nel male."),
"dorsey": ("Jack Dorsey", "Co-founder · Twitter", "Co-fondatore · Twitter", "1976–",
 "140-character poet of the real-time crowd.",
 "Poeta da 140 caratteri della folla in tempo reale."),
"hoffman": ("Reid Hoffman", "Co-founder · LinkedIn", "Co-fondatore · LinkedIn", "1967–",
 "PayPal philosopher networking careers.",
 "Filosofo PayPal che mette in rete carriere."),
"thiel": ("Peter Thiel", "Co-founder · PayPal", "Co-fondatore · PayPal", "1967–",
 "Contrarian backing zero-to-one futures.",
 "Controcorrente che scommette su futuri da zero a uno."),
"andreessen": ("Marc Andreessen", "Co-founder · Netscape", "Co-fondatore · Netscape", "1971–",
 "Mosaic browser kid declaring software eats the world.",
 "Ragazzo del browser Mosaic che dichiarò il software mangia-mondo."),
"benioff": ("Marc Benioff", "Founder · Salesforce", "Fondatore · Salesforce", "1964–",
 "Cloud salesman preaching 1-1-1 philanthropy.",
 "Venditore cloud che predica filantropia 1-1-1."),
"nadella": ("Satya Nadella", "Leader · Microsoft", "Guida · Microsoft", "1967–",
 "Hyderabad empathetic rebooting Microsoft's soul.",
 "Empatico di Hyderabad che riavviò l'anima Microsoft."),
"cook": ("Tim Cook", "Leader · Apple", "Guida · Apple", "1960–",
 "Alabama operator perfecting Apple's supply grace.",
 "Operatore dell'Alabama che perfezionò la grazia Apple."),
"huang": ("Jensen Huang", "Co-founder · NVIDIA", "Co-fondatore · NVIDIA", "1963–",
 "Leather-jacket chef cooking parallel universes.",
 "Chef in giacca di pelle che cucina universi paralleli."),
"lisasu": ("Lisa Su", "Leader · AMD", "Guida · AMD", "1969–",
 "Chip engineer reviving AMD with zen focus.",
 "Ingegnera dei chip che resuscitò AMD con focus zen."),
"graham": ("Paul Graham", "Co-founder · Y Combinator", "Co-fondatore · Y Combinator", "1964–",
 "Lisp hacker funding founders' defaults alive.",
 "Hacker Lisp che finanzia fondatori per default vivi."),
"collison": ("Patrick Collison", "Co-founder · Stripe", "Co-fondatore · Stripe", "1988–",
 "Irish API kid paving internet payments.",
 "Ragazzo irlandese delle API che pavimentò pagamenti internet."),
"altman": ("Sam Altman", "Leader · OpenAI", "Guida · OpenAI", "1985–",
 "St. Louis optimist scaling intelligence.",
 "Ottimista di St. Louis che scala intelligenza."),
"hassabis": ("Demis Hassabis", "Co-founder · DeepMind", "Co-fondatore · DeepMind", "1976–",
 "Chess prodigy folding proteins with machines.",
 "Prodigio degli scacchi che ripiega proteine con macchine."),
"wojcicki": ("Susan Wojcicki", "Leader · YouTube", "Guida · YouTube", "1968–2025",
 "Garage landlord who hosted Google, then video.",
 "Padrona del garage che ospitò Google, poi i video."),
}

Q = [
("page-01","page","Rank the world's information fearlessly.","Classifica l'informazione mondiale senza paura.",S,SI),
("page-02","page","Moonshots beat incrementalism.","I moonshot battono l'incrementalismo.",S,SI),
("page-03","page","Don't be evil scales.","Non essere malvagio scala.",C,CI),
("page-04","page","Dorm servers hum ambition.","I server del dormitorio ronzano ambizione.",A,AI),
("page-05","page","Speed matters most.","La velocità conta di più.",S,SI),
("page-06","page","BackRub became the library.","BackRub divenne la biblioteca.",S,SI),
("page-07","page","10x thinking only.","Solo pensiero 10x.",S,SI),
("page-08","page","Michigan roads lead to Mountain View.","Le strade del Michigan portano a Mountain View.",A,AI),
("page-09","page","Alphabet bets broadly.","Alphabet scommette ampio.",S,SI),
("page-10","page","Unlimited curiosity, indexed.","Curiosità illimitata, indicizzata.",A,AI),
("brin-01","brin","Moscow math, Stanford search.","Matematica di Mosca, ricerca di Stanford.",S,SI),
("brin-02","brin","Data mines need canaries.","Le miniere di dati hanno bisogno di canarini.",A,AI),
("brin-03","brin","Glass the future, learn fast.","Prova occhiali al futuro, impara in fretta.",S,SI),
("brin-04","brin","Immigrant hunger codes.","La fame dell'immigrato codifica.",S,SI),
("brin-05","brin","Balloons beam remote schools.","I palloni trasmettono a scuole remote.",S,SI),
("brin-06","brin","Parkinson's funds persistence.","Il Parkinson finanzia tenacia.",S,SI),
("brin-07","brin","Burning Man brainstorms.","Il Burning Man fa brainstorming.",A,AI),
("brin-08","brin","Calico ages gracefully.","Calico invecchia con grazia.",S,SI),
("brin-09","brin","Search serves serendipity.","La ricerca serve serendipità.",C,CI),
("brin-10","brin","Moonshots need math.","I moonshot hanno bisogno di matematica.",A,AI),
("zuckerberg-01","zuckerberg","Move fast and break things.","Muoviti in fretta e rompi cose.",A,AI),
("zuckerberg-02","zuckerberg","Connect every human.","Connetti ogni umano.",C,CI),
("zuckerberg-03","zuckerberg","Dorm blue paints billions.","Il blu del dormitorio dipinge miliardi.",A,AI),
("zuckerberg-04","zuckerberg","The metaverse awaits builders.","Il metaverso attende costruttori.",S,SI),
("zuckerberg-05","zuckerberg","Done beats perfect.","Fatto batte perfetto.",A,AI),
("zuckerberg-06","zuckerberg","Harvard dropouts ship.","Gli ex Harvard spediscono.",A,AI),
("zuckerberg-07","zuckerberg","Open defaults win.","I default aperti vincono.",C,CI),
("zuckerberg-08","zuckerberg","Hoodies outlast suits.","Le felpe durano più dei completi.",A,AI),
("zuckerberg-09","zuckerberg","Give 99 percent away.","Dona via il 99 per cento.",S,SI),
("zuckerberg-10","zuckerberg","Groups gather humanity.","I gruppi radunano umanità.",C,CI),
("dorsey-01","dorsey","140 characters changed nations.","140 caratteri cambiarono nazioni.",S,SI),
("dorsey-02","dorsey","Disagree silently, ship loudly.","Dissenti silenzioso, spedici forte.",A,AI),
("dorsey-03","dorsey","Square the payments.","Riquadra i pagamenti.",S,SI),
("dorsey-04","dorsey","Beards hide roadmaps.","Le barbe nascondono roadmap.",A,AI),
("dorsey-05","dorsey","Decentralize everything.","Decentralizza tutto.",S,SI),
("dorsey-06","dorsey","St. Louis dispatches worldwide.","St. Louis dispaccia nel mondo.",A,AI),
("dorsey-07","dorsey","Protocols outlive platforms.","I protocolli sopravvivono alle piattaforme.",S,SI),
("dorsey-08","dorsey","Meditate, then merge.","Medita, poi fondi.",A,AI),
("dorsey-09","dorsey","Bitcoin needs builders.","Bitcoin ha bisogno di costruttori.",S,SI),
("dorsey-10","dorsey","Hashtags organize history.","Gli hashtag organizzano la storia.",A,AI),
("hoffman-01","hoffman","Your network is your net worth.","La tua rete è il tuo patrimonio.",A,AI),
("hoffman-02","hoffman","Blitzscale or bust.","Blitzscala o fallisci.",S,SI),
("hoffman-03","hoffman","Careers are tours of duty.","Le carriere sono missioni.",S,SI),
("hoffman-04","hoffman","PayPal mafia mentors.","La mafia PayPal fa da mentore.",S,SI),
("hoffman-05","hoffman","LinkedIn links livelihoods.","LinkedIn collega vite.",C,CI),
("hoffman-06","hoffman","AI needs human networks.","L'IA ha bisogno di reti umane.",S,SI),
("hoffman-07","hoffman","Podcasts scale wisdom.","I podcast scalano saggezza.",S,SI),
("hoffman-08","hoffman","Oxford philosophy, Silicon Valley practice.","Filosofia di Oxford, pratica di Silicon Valley.",A,AI),
("hoffman-09","hoffman","Alliances compound.","Le alleanze si accumulano.",C,CI),
("hoffman-10","hoffman","Invest in people networks.","Investi in reti di persone.",S,SI),
("thiel-01","thiel","Zero to one, never one to n.","Da zero a uno, mai da uno a n.",S,SI),
("thiel-02","thiel","Monopolies do good.","I monopoli fanno bene.",S,SI),
("thiel-03","thiel","Contrarians compound.","I controcorrente accumulano.",A,AI),
("thiel-04","thiel","College is overrated debt.","L'università è debito sopravvalutato.",S,SI),
("thiel-05","thiel","Secrets hide in plain sight.","I segreti si nascondono in vista.",S,SI),
("thiel-06","thiel","Definite optimism builds.","L'ottimismo definito costruisce.",S,SI),
("thiel-07","thiel","Founders need strangeness.","I fondatori hanno bisogno di stranezza.",A,AI),
("thiel-08","thiel","PayPal plotted escape.","PayPal pianificò fuga.",S,SI),
("thiel-09","thiel","Competition is for losers.","La competizione è per perdenti.",A,AI),
("thiel-10","thiel","Live 120 years curious.","Vivi 120 anni curioso.",A,AI),
("andreessen-01","andreessen","Software is eating the world.","Il software sta mangiando il mondo.",S,SI),
("andreessen-02","andreessen","Mosaic opened the floodgates.","Mosaic aprì le cateratte.",S,SI),
("andreessen-03","andreessen","Bits beat atoms.","I bit battono gli atomi.",S,SI),
("andreessen-04","andreessen","Tweet the future daily.","Twitta il futuro ogni giorno.",A,AI),
("andreessen-05","andreessen","Build, baby, build.","Costruisci, baby, costruisci.",S,SI),
("andreessen-06","andreessen","Netscape navigated first.","Netscape navigò per primo.",S,SI),
("andreessen-07","andreessen","Crypto eats finance.","Le crypto mangiano la finanza.",S,SI),
("andreessen-08","andreessen","Wisconsin winters code.","Gli inverni del Wisconsin codificano.",A,AI),
("andreessen-09","andreessen","A16Z bets on weird.","A16Z scommette sullo strano.",C,CI),
("andreessen-10","andreessen","Abundance needs builders.","L'abbondanza ha bisogno di costruttori.",S,SI),
("benioff-01","benioff","No software, all service.","Niente software, tutto servizio.",C,CI),
("benioff-02","benioff","1-1-1: time, equity, product.","1-1-1: tempo, equity, prodotto.",C,CI),
("benioff-03","benioff","Clouds rain revenue.","Le nuvole piovono ricavi.",C,CI),
("benioff-04","benioff","Dreamforce gathers tribes.","Dreamforce raduna tribù.",S,SI),
("benioff-05","benioff","Hawaii resets servers.","Le Hawaii resettano i server.",A,AI),
("benioff-06","benioff","Ohana means stakeholders.","Ohana significa stakeholder.",C,CI),
("benioff-07","benioff","Protest for equality.","Protesta per l'uguaglianza.",S,SI),
("benioff-08","benioff","Tower over transience.","Torreggia sulla transitorietà.",A,AI),
("benioff-09","benioff","Customers trailblaze.","I clienti aprono piste.",C,CI),
("benioff-10","benioff","San Francisco sails cloud.","San Francisco naviga cloud.",A,AI),
("nadella-01","nadella","Empathy drives innovation.","L'empatia guida l'innovazione.",S,SI),
("nadella-02","nadella","Hit refresh daily.","Premi aggiorna ogni giorno.",S,SI),
("nadella-03","nadella","Learn-it-alls beat know-it-alls.","Chi impara batte chi sa tutto.",S,SI),
("nadella-04","nadella","Cloud first, mobile first.","Prima cloud, prima mobile.",C,CI),
("nadella-05","nadella","Hyderabad humility scales.","L'umiltà di Hyderabad scala.",A,AI),
("nadella-06","nadella","Cricket teaches captaincy.","Il cricket insegna comando.",S,SI),
("nadella-07","nadella","Gaming unites generations.","Il gaming unisce generazioni.",S,SI),
("nadella-08","nadella","AI empowers every person.","L'IA dà potere a ogni persona.",S,SI),
("nadella-09","nadella","Culture eats roadmaps.","La cultura mangia roadmap.",C,CI),
("nadella-10","nadella","Fatherhood focuses purpose.","La paternità focalizza lo scopo.",S,SI),
("cook-01","cook","Privacy is a human right.","La privacy è un diritto umano.",S,SI),
("cook-02","cook","Operations is choreography.","Le operations sono coreografia.",S,SI),
("cook-03","cook","Alabama values, global supply.","Valori dell'Alabama, fornitura globale.",A,AI),
("cook-04","cook","Think different, execute perfectly.","Pensa diverso, esegui perfetto.",C,CI),
("cook-05","cook","Environment needs accountants.","L'ambiente ha bisogno di contabili.",S,SI),
("cook-06","cook","Coming out strengthens teams.","Il coming out fortifica i team.",S,SI),
("cook-07","cook","Watch the wrist, win health.","Guarda il polso, vinci salute.",C,CI),
("cook-08","cook","Auburn engineers ethics.","Auburn ingegnerizza etica.",A,AI),
("cook-09","cook","Recycle rare earths.","Ricicla terre rare.",S,SI),
("cook-10","cook","Steady hands ship billions.","Mani salde spediscono miliardi.",A,AI),
("huang-01","huang","GPUs dream in parallel.","Le GPU sognano in parallelo.",S,SI),
("huang-02","huang","Leather jackets compute.","Le giacche di pelle computano.",A,AI),
("huang-03","huang","Denny's booths birth billions.","I tavoli di Denny's partoriscono miliardi.",S,SI),
("huang-04","huang","CUDA cultivates ecosystems.","CUDA coltiva ecosistemi.",C,CI),
("huang-05","huang","AI factories forge tokens.","Le fabbriche IA forgiano token.",S,SI),
("huang-06","huang","Taiwan roots, global chips.","Radici taiwanesi, chip globali.",A,AI),
("huang-07","huang","Zero-billion markets beckon.","Mercati da zero miliardi chiamano.",S,SI),
("huang-08","huang","Cook in the kitchen of compute.","Cucina nella cucina del calcolo.",A,AI),
("huang-09","huang","Ray tracing reveals reality.","Il ray tracing rivela realtà.",C,CI),
("huang-10","huang","Run, don't walk, toward AI.","Corri, non camminare, verso l'IA.",S,SI),
("lisasu-01","lisasu","High performance, humble leadership.","Alte performance, leadership umile.",S,SI),
("lisasu-02","lisasu","Zen cores, calm comebacks.","Core Zen, ritorni calmi.",C,CI),
("lisasu-03","lisasu","Engineers listen to customers.","Gli ingegneri ascoltano i clienti.",S,SI),
("lisasu-04","lisasu","Bet the company on 7nm.","Scommetti l'azienda sui 7nm.",S,SI),
("lisasu-05","lisasu","Tainan tenacity tapes out.","La tenacia di Tainan va in tape-out.",A,AI),
("lisasu-06","lisasu","Chiplets piece victories.","I chiplet compongono vittorie.",C,CI),
("lisasu-07","lisasu","Mentor every intern.","Fai da mentore a ogni stagista.",S,SI),
("lisasu-08","lisasu","Data centers dream AMD.","I data center sognano AMD.",C,CI),
("lisasu-09","lisasu","Make good products, results follow.","Fai buoni prodotti, i risultati seguono.",S,SI),
("lisasu-10","lisasu","Underdogs out-execute.","Gli sfavoriti eseguono meglio.",A,AI),
("graham-01","graham","Make something people want.","Fai qualcosa che la gente vuole.",S,SI),
("graham-02","graham","Default alive always.","Default vivo sempre.",S,SI),
("graham-03","graham","Hackers paint with code.","Gli hacker dipingono con codice.",S,SI),
("graham-04","graham","Startups compress decades.","Le startup comprimono decenni.",S,SI),
("graham-05","graham","Lisp whispers power.","Lisp sussurra potere.",A,AI),
("graham-06","graham","Ramen profitable beats funded.","Ramen profitable batte finanziato.",S,SI),
("graham-07","graham","Essays debug thinking.","I saggi debuggano il pensiero.",S,SI),
("graham-08","graham","Founders need nerds.","I fondatori hanno bisogno di nerd.",A,AI),
("graham-09","graham","Scale schlep, love boring.","Scala lo schlep, ama il noioso.",S,SI),
("graham-10","graham","Cornell to Cambridge to YC.","Da Cornell a Cambridge a YC.",A,AI),
("collison-01","collison","Increase the GDP of the internet.","Aumenta il PIL di internet.",C,CI),
("collison-02","collison","APIs absorb complexity.","Le API assorbono complessità.",C,CI),
("collison-03","collison","Limerick logic, global payments.","Logica di Limerick, pagamenti globali.",A,AI),
("collison-04","collison","Seven lines change commerce.","Sette righe cambiano il commercio.",C,CI),
("collison-05","collison","Read widely, build narrowly.","Leggi ampio, costruisci stretto.",S,SI),
("collison-06","collison","Progress studies needed.","Servono studi sul progresso.",S,SI),
("collison-07","collison","Brothers code billions.","I fratelli codificano miliardi.",A,AI),
("collison-08","collison","Fast foundations compound.","Fondamenta veloci si accumulano.",C,CI),
("collison-09","collison","Atlas maps startups.","Atlas mappa startup.",C,CI),
("collison-10","collison","Curiosity ships features.","La curiosità spedisce funzionalità.",A,AI),
("altman-01","altman","Scale intelligence responsibly.","Scala l'intelligenza responsabilmente.",S,SI),
("altman-02","altman","AGI benefits all humanity.","L'AGI beneficia tutta l'umanità.",C,CI),
("altman-03","altman","St. Louis to Stanford to worlds.","Da St. Louis a Stanford ai mondi.",A,AI),
("altman-04","altman","Loopt looped lessons.","Loopt girò lezioni.",S,SI),
("altman-05","altman","Moore's law for minds.","Legge di Moore per menti.",S,SI),
("altman-06","altman","Deploy iteratively, listen constantly.","Rilascia iterativo, ascolta costante.",C,CI),
("altman-07","altman","Compute is currency.","Il calcolo è valuta.",S,SI),
("altman-08","altman","Optimism compounds.","L'ottimismo si accumula.",A,AI),
("altman-09","altman","YC bred builders.","YC allevò costruttori.",S,SI),
("altman-10","altman","Abundance needs alignment.","L'abbondanza ha bisogno di allineamento.",S,SI),
("hassabis-01","hassabis","Solve intelligence, then use it.","Risolvi l'intelligenza, poi usala.",S,SI),
("hassabis-02","hassabis","Chess taught machines patience.","Gli scacchi insegnarono pazienza alle macchine.",S,SI),
("hassabis-03","hassabis","Proteins fold, cures unfold.","Le proteine si ripiegano, le cure si spiegano.",S,SI),
("hassabis-04","hassabis","Games are intelligence benchmarks.","I giochi sono benchmark d'intelligenza.",S,SI),
("hassabis-05","hassabis","London labs dream globally.","I lab di Londra sognano globale.",A,AI),
("hassabis-06","hassabis","Go masters bow to Alpha.","I maestri di Go si inchinano ad Alpha.",S,SI),
("hassabis-07","hassabis","Neuroscience guides silicon.","Le neuroscienze guidano il silicio.",S,SI),
("hassabis-08","hassabis","Safety scales with smarts.","La sicurezza scala con l'intelligenza.",C,CI),
("hassabis-09","hassabis","Prodigies persist.","I prodigi persistono.",A,AI),
("hassabis-10","hassabis","Science wins Nobel patience.","La scienza vince Nobel di pazienza.",S,SI),
("wojcicki-01","wojcicki","Garages gestate giants.","I garage gestano giganti.",S,SI),
("wojcicki-02","wojcicki","Video empowers voices.","Il video dà potere alle voci.",C,CI),
("wojcicki-03","wojcicki","Ads fund creativity.","Le pubblicità finanziano creatività.",C,CI),
("wojcicki-04","wojcicki","Parents need parental leave.","I genitori hanno bisogno di congedi.",S,SI),
("wojcicki-05","wojcicki","Creators are economies.","I creator sono economie.",C,CI),
("wojcicki-06","wojcicki","Stanford history, Silicon future.","Storia di Stanford, futuro di Silicon.",A,AI),
("wojcicki-07","wojcicki","Moderate with humanity.","Modera con umanità.",S,SI),
("wojcicki-08","wojcicki","Five kids, billions of views.","Cinque figli, miliardi di views.",A,AI),
("wojcicki-09","wojcicki","Rent rooms, host revolutions.","Affitta stanze, ospita rivoluzioni.",A,AI),
("wojcicki-10","wojcicki","Education streams free.","L'istruzione scorre gratis.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchI added={added} total_en={len(en)} total_it={len(it)}")
