"""Batch D: international entrepreneurs 2 (17 authors x 10 = 170 quotes)."""
import json

CAT = "international_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"roddick": ("Anita Roddick", "Founder · The Body Shop", "Fondatrice · The Body Shop", "1942–2007",
 "British activist-retailer proving business can campaign.",
 "Attivista-commerciante britannica che dimostrò che il business può fare campagne."),
"hershey": ("Milton Hershey", "Founder · Hershey", "Fondatore · Hershey", "1857–1945",
 "Caramel salesman who built a chocolate town in Pennsylvania.",
 "Venditore di caramelle che costruì una città del cioccolato in Pennsylvania."),
"strauss": ("Levi Strauss", "Founder · Levi's", "Fondatore · Levi's", "1829–1902",
 "Bavarian dry-goods man who riveted workwear into denim.",
 "Mercante bavarese che bullonò il workwear nel denim."),
"hilton": ("Conrad Hilton", "Founder · Hilton", "Fondatore · Hilton", "1887–1979",
 "New Mexico innkeeper who standardized the welcome worldwide.",
 "Albergatore del New Mexico che standardizzò l'accoglienza nel mondo."),
"marriott": ("J. Willard Marriott", "Founder · Marriott", "Fondatore · Marriott", "1900–1985",
 "Root-beer stand owner who scaled hospitality with heart.",
 "Proprietario di chiosco che scalò l'ospitalità con il cuore."),
"turner": ("Ted Turner", "Founder · CNN", "Fondatore · CNN", "1938–",
 "Billboard heir who beamed 24-hour news around the planet.",
 "Erede di cartelloni che trasmise news 24 ore in tutto il pianeta."),
"bloomberg": ("Michael Bloomberg", "Founder · Bloomberg", "Fondatore · Bloomberg", "1942–",
 "Terminal builder turned mayor, data-driven to the core.",
 "Costruttore di terminal diventato sindaco, guidato dai dati."),
"huffington": ("Arianna Huffington", "Co-founder · HuffPost", "Co-fondatrice · HuffPost", "1950–",
 "Greek author who blogged news into a movement, then preached sleep.",
 "Autrice greca che bloggò le news in movimento, poi predicò il sonno."),
"hastings": ("Reed Hastings", "Co-founder · Netflix", "Co-fondatore · Netflix", "1960–",
 "DVD-by-mail tinkerer who streamed the world.",
 "Sperimentatore di DVD per posta che trasmise il mondo in streaming."),
"chesky": ("Brian Chesky", "Co-founder · Airbnb", "Co-fondatore · Airbnb", "1981–",
 "Designer who rented air mattresses and redesigned belonging.",
 "Designer che affittò materassini e riprogettò l'appartenenza."),
"ellison": ("Larry Ellison", "Co-founder · Oracle", "Co-fondatore · Oracle", "1944–",
 "Chicago sailor of databases racing yachts and rivals.",
 "Velista chicagoano di database in gara con yacht e rivali."),
"ek": ("Daniel Ek", "Co-founder · Spotify", "Co-fondatore · Spotify", "1983–",
 "Swedish coder who made music access beat piracy.",
 "Programmatore svedese che fece vincere l'accesso alla musica sulla pirateria."),
"lutke": ("Tobias Lütke", "Founder · Shopify", "Fondatore · Shopify", "1981–",
 "Snowboard seller who armed millions of small shops.",
 "Venditore di snowboard che armò milioni di piccoli negozi."),
"perkins": ("Melanie Perkins", "Co-founder · Canva", "Co-fondatrice · Canva", "1987–",
 "Australian teacher who put design in every browser.",
 "Insegnante australiana che mise il design in ogni browser."),
"wolfe": ("Whitney Wolfe Herd", "Founder · Bumble", "Fondatrice · Bumble", "1989–",
 "Dating-app founder who put the first move in women's hands.",
 "Fondatrice di app di incontri che mise la prima mossa nelle mani delle donne."),
"moore": ("Gordon Moore", "Co-founder · Intel", "Co-fondatore · Intel", "1929–2023",
 "Chemist whose law shrank transistors and grew the future.",
 "Chimico la cui legge rimpicciolì i transistor e fece crescere il futuro."),
"morita": ("Akio Morita", "Co-founder · Sony", "Co-fondatore · Sony", "1921–1999",
 "Japanese officer who miniaturized music with the Walkman.",
 "Ufficiale giapponese che miniaturizzò la musica con il Walkman."),
}

Q = [
("roddick-01","roddick","Business can be a campaigning force.","Il business può essere una forza di campagna.",S,SI),
("roddick-02","roddick","If you think you're too small, try sleeping with a mosquito.","Se ti credi troppo piccolo, prova a dormire con una zanzara.",A,AI),
("roddick-03","roddick","Trade fairly, shout loudly.","Commercia equo, grida forte.",C,CI),
("roddick-04","roddick","Beauty without cruelty.","Bellezza senza crudeltà.",C,CI),
("roddick-05","roddick","Activism is good marketing for the soul.","L'attivismo è buon marketing per l'anima.",S,SI),
("roddick-06","roddick","Nobody talks of entrepreneurship as survival.","Nessuno parla d'impresa come sopravvivenza.",S,SI),
("roddick-07","roddick","The money will come if the cause is true.","I soldi verranno se la causa è vera.",A,AI),
("roddick-08","roddick","Question every ingredient.","Metti in dubbio ogni ingrediente.",C,CI),
("roddick-09","roddick","Kindness scales better than ads.","La gentilezza scala meglio delle pubblicità.",A,AI),
("roddick-10","roddick","Rage, beautifully bottled.","Rabbia, imbottigliata con bellezza.",A,AI),
("hershey-01","hershey","Give them quality; it is the best advertising.","Dai loro qualità; è la miglior pubblicità.",A,AI),
("hershey-02","hershey","Build a town around the factory's heart.","Costruisci una città attorno al cuore della fabbrica.",S,SI),
("hershey-03","hershey","Chocolate should delight every child.","Il cioccolato dovrebbe deliziare ogni bambino.",C,CI),
("hershey-04","hershey","Fail in caramel, persist in cocoa.","Fallisci nel caramello, persisti nel cacao.",S,SI),
("hershey-05","hershey","Sweetness shared multiplies.","La dolcezza condivisa si moltiplica.",A,AI),
("hershey-06","hershey","Treat workers as neighbors.","Tratta gli operai come vicini.",S,SI),
("hershey-07","hershey","Schools outlast chocolate bars.","Le scuole durano più delle barrette.",S,SI),
("hershey-08","hershey","Lancaster taught me patience.","Lancaster mi insegnò pazienza.",A,AI),
("hershey-09","hershey","Kisses for the many, not the few.","Baci per i molti, non per i pochi.",A,AI),
("hershey-10","hershey","Give away fortunes, keep the recipe of kindness.","Dona fortune, conserva la ricetta della gentilezza.",S,SI),
("strauss-01","strauss","Rivet the weak points.","Ribatti i punti deboli.",C,CI),
("strauss-02","strauss","Sell shovels of denim in a gold rush.","Vendi pale di denim nella corsa all'oro.",S,SI),
("strauss-03","strauss","Workwear outlasts fashion.","Il workwear dura più della moda.",A,AI),
("strauss-04","strauss","Copper rivets hold dreams.","I rivetti di rame tengono i sogni.",C,CI),
("strauss-05","strauss","Serve miners, dress generations.","Servi i minatori, vesti generazioni.",S,SI),
("strauss-06","strauss","Blue never fades from history.","Il blu non sbiadisce mai dalla storia.",A,AI),
("strauss-07","strauss","Stitch honesty into every seam.","Cuci onestà in ogni cucitura.",C,CI),
("strauss-08","strauss","San Francisco sews forward.","San Francisco cuce in avanti.",A,AI),
("strauss-09","strauss","Durability is democracy.","La durata è democrazia.",A,AI),
("strauss-10","strauss","Patent persistence.","Brevetta la tenacia.",A,AI),
("hilton-01","hilton","Service with a smile worldwide.","Servizio con sorriso in tutto il mondo.",C,CI),
("hilton-02","hilton","Find the lobby's heartbeat.","Trova il battito della hall.",S,SI),
("hilton-03","hilton","Fill empty rooms with care.","Riempi le stanze vuote con cura.",C,CI),
("hilton-04","hilton","Hospitality scales kindness.","L'ospitalità scala la gentilezza.",S,SI),
("hilton-05","hilton","Remember the guest's name.","Ricorda il nome dell'ospite.",C,CI),
("hilton-06","hilton","Clean sheets, clear conscience.","Lenzuola pulite, coscienza pulita.",A,AI),
("hilton-07","hilton","Expand where welcome is scarce.","Espanditi dove l'accoglienza scarseggia.",S,SI),
("hilton-08","hilton","A bellhop's smile opens cities.","Il sorriso del fattorino apre città.",A,AI),
("hilton-09","hilton","Standards travel well.","Gli standard viaggiano bene.",C,CI),
("hilton-10","hilton","Take the elevator, greet everyone.","Prendi l'ascensore, saluta tutti.",A,AI),
("marriott-01","marriott","Take care of people, they take care of guests.","Cura le persone, cureranno gli ospiti.",C,CI),
("marriott-02","marriott","Root beer roots, global branches.","Radici di root beer, rami globali.",S,SI),
("marriott-03","marriott","Doors open for the diligent.","Le porte si aprono ai diligenti.",A,AI),
("marriott-04","marriott","Spotless rooms, spotless reputation.","Stanze impeccabili, reputazione impeccabile.",C,CI),
("marriott-05","marriott","Promote from within.","Promuovi dall'interno.",C,CI),
("marriott-06","marriott","Listen at the front desk.","Ascolta alla reception.",S,SI),
("marriott-07","marriott","Serve hot, smile warm.","Servi caldo, sorridi caldo.",A,AI),
("marriott-08","marriott","Family business, worldwide family.","Azienda familiare, famiglia mondiale.",S,SI),
("marriott-09","marriott","Details check in first.","I dettagli fanno check-in per primi.",C,CI),
("marriott-10","marriott","Hospitality is habit.","L'ospitalità è abitudine.",A,AI),
("turner-01","turner","Lead, follow, or get out of the way.","Guida, segui o togliti di mezzo.",A,AI),
("turner-02","turner","News never sleeps, so we won't.","Le news non dormono, quindi nemmeno noi.",C,CI),
("turner-03","turner","My son, the globe is your billboard.","Figlio mio, il globo è il tuo cartellone.",A,AI),
("turner-04","turner","Bet big on live events.","Scommetti forte sugli eventi live.",S,SI),
("turner-05","turner","Sports unite the planet.","Lo sport unisce il pianeta.",S,SI),
("turner-06","turner","Sail into headwinds.","Naviga controvento.",A,AI),
("turner-07","turner","Give a billion back to Earth.","Restituisci un miliardo alla Terra.",S,SI),
("turner-08","turner","Captain outrageous, crew serious.","Capitano stravagante, equipaggio serio.",A,AI),
("turner-09","turner","Twenty-four hours changes everything.","Ventiquattro ore cambiano tutto.",C,CI),
("turner-10","turner","Save the bison, save the story.","Salva i bisonti, salva la storia.",S,SI),
("bloomberg-01","bloomberg","Data beats drama.","I dati battono il dramma.",S,SI),
("bloomberg-02","bloomberg","Give the terminal, take the noise away.","Dai il terminale, togli il rumore.",C,CI),
("bloomberg-03","bloomberg","Manage numbers, serve people.","Gestisci numeri, servi persone.",S,SI),
("bloomberg-04","bloomberg","Philanthropy needs metrics.","La filantropia ha bisogno di metriche.",S,SI),
("bloomberg-05","bloomberg","Start at 6am, outwork doubt.","Comincia alle 6, supera il dubbio col lavoro.",A,AI),
("bloomberg-06","bloomberg","Cities are solutions.","Le città sono soluzioni.",S,SI),
("bloomberg-07","bloomberg","Ban smoking, fund schools.","Vieta il fumo, finanzia scuole.",S,SI),
("bloomberg-08","bloomberg","Hire hungry minds.","Assumi menti affamate.",A,AI),
("bloomberg-09","bloomberg","Be the nerd in charge.","Sii il nerd al comando.",A,AI),
("bloomberg-10","bloomberg","Give it all away, wisely.","Dona tutto, con saggezza.",S,SI),
("huffington-01","huffington","Sleep your way to the top.","Dormi fino in cima.",S,SI),
("huffington-02","huffington","Burnout is not success.","Il burnout non è successo.",S,SI),
("huffington-03","huffington","Third metric: well-being.","Terza metrica: benessere.",C,CI),
("huffington-04","huffington","Blog the unheard.","Blogga gli inascoltati.",S,SI),
("huffington-05","huffington","Naps are performance tools.","I pisolini sono strumenti di performance.",S,SI),
("huffington-06","huffington","Fearlessness can be learned.","L'impavidità si impara.",A,AI),
("huffington-07","huffington","Disconnect to reconnect.","Disconnettiti per riconnetterti.",S,SI),
("huffington-08","huffington","Greece taught me debate.","La Grecia mi insegnò il dibattito.",S,SI),
("huffington-09","huffington","Thrive, don't just survive.","Prospera, non solo sopravvivi.",C,CI),
("huffington-10","huffington","Redefine success daily.","Ridefinisci il successo ogni giorno.",S,SI),
("hastings-01","hastings","Mail joy, stream dreams.","Spedisci gioia, trasmetti sogni.",S,SI),
("hastings-02","hastings","Culture of freedom with responsibility.","Cultura di libertà con responsabilità.",C,CI),
("hastings-03","hastings","No brilliant jerks.","Niente geni insopportabili.",C,CI),
("hastings-04","hastings","Bet the company on streaming.","Scommetti l'azienda sullo streaming.",S,SI),
("hastings-05","hastings","Late fees were the enemy.","Le more erano il nemico.",S,SI),
("hastings-06","hastings","Data informs taste.","I dati informano il gusto.",C,CI),
("hastings-07","hastings","Hire adults, treat them so.","Assumi adulti, trattali come tali.",C,CI),
("hastings-08","hastings","Fail the DVD to win the future.","Fallisci col DVD per vincere il futuro.",S,SI),
("hastings-09","hastings","Binge kindly.","Fai binge con garbo.",A,AI),
("hastings-10","hastings","Stories travel borderless.","Le storie viaggiano senza confini.",S,SI),
("chesky-01","chesky","Belong anywhere you sleep.","Appartieni ovunque dormi.",C,CI),
("chesky-02","chesky","Sell cereal to fund dreams.","Vendi cereali per finanziare sogni.",S,SI),
("chesky-03","chesky","Design trust into every stay.","Disegna fiducia in ogni soggiorno.",C,CI),
("chesky-04","chesky","Hosts are the product.","Gli host sono il prodotto.",S,SI),
("chesky-05","chesky","Live in your users' homes.","Vivi nelle case dei tuoi utenti.",S,SI),
("chesky-06","chesky","Eleven stars out of five.","Undici stelle su cinque.",A,AI),
("chesky-07","chesky","Belonging beats booking.","L'appartenenza batte la prenotazione.",C,CI),
("chesky-08","chesky","Prototype with air mattresses.","Prototipa con materassini.",S,SI),
("chesky-09","chesky","Travel like a local.","Viaggia come un locale.",C,CI),
("chesky-10","chesky","Community is the moat.","La community è il fossato.",S,SI),
("ellison-01","ellison","Data wants to be queried.","I dati vogliono essere interrogati.",S,SI),
("ellison-02","ellison","Sail faster than doubt.","Naviga più veloce del dubbio.",A,AI),
("ellison-03","ellison","Second place sails nowhere.","Il secondo posto non naviga da nessuna parte.",A,AI),
("ellison-04","ellison","Software eats uncertainty.","Il software mangia l'incertezza.",S,SI),
("ellison-05","ellison","Win the America's Cup of business.","Vinci l'America's Cup del business.",A,AI),
("ellison-06","ellison","Paranoia ships products.","La paranoia spedisce prodotti.",A,AI),
("ellison-07","ellison","Clouds gather profits.","Le nuvole raccolgono profitti.",S,SI),
("ellison-08","ellison","Outspend fear, outsail rivals.","Supera la paura, doppi i rivali.",A,AI),
("ellison-09","ellison","Databases remember everything.","I database ricordano tutto.",S,SI),
("ellison-10","ellison","Live on the edge of the wind.","Vivi sul bordo del vento.",A,AI),
("ek-01","ek","Access beats ownership.","L'accesso batte il possesso.",C,CI),
("ek-02","ek","Piracy is a service problem.","La pirateria è un problema di servizio.",S,SI),
("ek-03","ek","Playlists are the new radio.","Le playlist sono la nuova radio.",C,CI),
("ek-04","ek","Freemium funds freedom.","Il freemium finanzia la libertà.",C,CI),
("ek-05","ek","Artists deserve paydays.","Gli artisti meritano paghe.",S,SI),
("ek-06","ek","Swedish winter codes summer hits.","L'inverno svedese codifica hit estive.",A,AI),
("ek-07","ek","Discover weekly, deliver daily.","Scopri settimanale, consegna quotidiano.",C,CI),
("ek-08","ek","Audio first, everything follows.","Prima l'audio, poi tutto il resto.",S,SI),
("ek-09","ek","Long tail, loud future.","Coda lunga, futuro forte.",A,AI),
("ek-10","ek","Never stop buffering ambition.","Non smettere mai di bufferizzare ambizione.",A,AI),
("lutke-01","lutke","Arm the rebels of retail.","Arma i ribelli del retail.",C,CI),
("lutke-02","lutke","Code the snowboard shop first.","Codifica prima il negozio di snowboard.",S,SI),
("lutke-03","lutke","Small merchants, big software.","Piccoli mercanti, grande software.",C,CI),
("lutke-04","lutke","Trust over control.","Fiducia oltre controllo.",C,CI),
("lutke-05","lutke","Build for the long independent tail.","Costruisci per la lunga coda indipendente.",S,SI),
("lutke-06","lutke","Gaming teaches systems.","Il gaming insegna i sistemi.",S,SI),
("lutke-07","lutke","Ottawa winters, global summers.","Inverni di Ottawa, estati globali.",A,AI),
("lutke-08","lutke","Docs are products too.","Anche la documentazione è prodotto.",C,CI),
("lutke-09","lutke","Hire crafters, not titles.","Assumi artigiani, non titoli.",S,SI),
("lutke-10","lutke","Commerce belongs to everyone.","Il commercio appartiene a tutti.",C,CI),
("perkins-01","perkins","Design belongs in every browser.","Il design appartiene a ogni browser.",C,CI),
("perkins-02","perkins","Teach first, scale second.","Insegna prima, scala dopo.",S,SI),
("perkins-03","perkins","One hundred rejections, one revolution.","Cento rifiuti, una rivoluzione.",S,SI),
("perkins-04","perkins","Templates free creativity.","I modelli liberano la creatività.",C,CI),
("perkins-05","perkins","Perth to planet.","Da Perth al pianeta.",A,AI),
("perkins-06","perkins","Non-designers design most.","I non-designer disegnano di più.",C,CI),
("perkins-07","perkins","Give away value early.","Regala valore presto.",S,SI),
("perkins-08","perkins","Culture draws talent.","La cultura disegna talenti.",C,CI),
("perkins-09","perkins","Drag, drop, democratize.","Trascina, rilascia, democratizza.",C,CI),
("perkins-10","perkins","Yearbooks taught me software.","Gli annuari mi insegnarono il software.",S,SI),
("wolfe-01","wolfe","Women make the first move.","Le donne fanno la prima mossa.",C,CI),
("wolfe-02","wolfe","Kindness is a feature.","La gentilezza è una funzionalità.",C,CI),
("wolfe-03","wolfe","Reinvent romance with respect.","Reinventate il romanticismo con rispetto.",S,SI),
("wolfe-04","wolfe","Block the rude, boost the kind.","Blocca i maleducati, promuovi i gentili.",C,CI),
("wolfe-05","wolfe","Swipe with standards.","Scorri con standard.",A,AI),
("wolfe-06","wolfe","Empowerment downloads daily.","L'empowerment si scarica ogni giorno.",A,AI),
("wolfe-07","wolfe","Texas grit, global app.","Grinta texana, app globale.",A,AI),
("wolfe-08","wolfe","Safety ships first.","La sicurezza si spedisce per prima.",C,CI),
("wolfe-09","wolfe","Feminism funds futures.","Il femminismo finanzia futuri.",A,AI),
("wolfe-10","wolfe","Hive with heart.","Alveare con cuore.",A,AI),
("moore-01","moore","Double transistors, halve doubts.","Raddoppia i transistor, dimezza i dubbi.",S,SI),
("moore-02","moore","Exponential patience wins.","La pazienza esponenziale vince.",A,AI),
("moore-03","moore","Chemistry compounds progress.","La chimica compone il progresso.",S,SI),
("moore-04","moore","Labs outlive laws, except this one.","I lab durano più delle leggi, tranne questa.",A,AI),
("moore-05","moore","Shrink the chip, expand the mind.","Rimpicciolisci il chip, espandi la mente.",C,CI),
("moore-06","moore","Fairchild forged founders.","Fairchild forgiò fondatori.",S,SI),
("moore-07","moore","Philanthropy scales science.","La filantropia scala la scienza.",S,SI),
("moore-08","moore","Bet on silicon, not noise.","Scommetti sul silicio, non sul rumore.",A,AI),
("moore-09","moore","Quiet engineers, loud futures.","Ingegneri silenziosi, futuri rumorosi.",A,AI),
("moore-10","moore","Give oceans their observatory.","Dai agli oceani il loro osservatorio.",S,SI),
("morita-01","morita","Miniaturize joy.","Miniaturizza la gioia.",C,CI),
("morita-02","morita","Walkman: music that walks with you.","Walkman: musica che cammina con te.",S,SI),
("morita-03","morita","Think global, solder local.","Pensa globale, salda locale.",A,AI),
("morita-04","morita","Curiosity fits in a pocket.","La curiosità sta in tasca.",A,AI),
("morita-05","morita","Engineers must dream in stereo.","Gli ingegneri devono sognare in stereo.",S,SI),
("morita-06","morita","Brand the future kindly.","Marchia il futuro con garbo.",C,CI),
("morita-07","morita","Tokyo mornings hum innovation.","Le mattine di Tokyo canticchiano innovazione.",A,AI),
("morita-08","morita","Never copy; create compactly.","Mai copiare; crea compatto.",S,SI),
("morita-09","morita","Management with a human face.","Management dal volto umano.",S,SI),
("morita-10","morita","Schools of music need circuits.","Le scuole di musica hanno bisogno di circuiti.",A,AI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchD added={added} total_en={len(en)} total_it={len(it)}")
