"""Batch A: Italian entrepreneurs 1 (15 authors x 10 = 150 quotes). Appends to assets."""
import json

CAT = "italian_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"agnelli": ("Gianni Agnelli", "Industrialist · Fiat", "Industriale · Fiat", "1921–2003",
 "Fiat president who embodied Italian style and industry for half a century.",
 "Presidente Fiat che incarnò per mezzo secolo stile e industria italiani."),
"barilla": ("Pietro Barilla", "Food entrepreneur · Barilla", "Imprenditore alimentare · Barilla", "1913–1993",
 "Parma pasta maker who turned a bakery into a world pantry staple.",
 "Pastaio parmense che trasformò un forno in un simbolo mondiale della tavola."),
"gferrero": ("Giovanni Ferrero", "Entrepreneur · Ferrero", "Imprenditore · Ferrero", "1964–",
 "Son of Michele who leads Ferrero with discretion and long-term vision.",
 "Figlio di Michele, guida Ferrero con discrezione e visione di lungo periodo."),
"illy": ("Andrea Illy", "Entrepreneur · illycaffè", "Imprenditore · illycaffè", "1964–",
 "Trieste coffee leader blending science, art and sustainability in every cup.",
 "Leader triestino del caffè che unisce scienza, arte e sostenibilità in ogni tazzina."),
"rana": ("Giovanni Rana", "Food entrepreneur · Rana", "Imprenditore alimentare · Rana", "1937–",
 "Verona pasta master who brought fresh tortellini to the world.",
 "Maestro veronese della pasta che portò i tortellini freschi nel mondo."),
"versace": ("Gianni Versace", "Founder · Versace", "Fondatore · Versace", "1946–1997",
 "Calabrian designer who dressed music, myth and fearless glamour.",
 "Stilista calabrese che vestì musica, mito e glamour senza paura."),
"prada": ("Miuccia Prada", "Designer · Prada", "Stilista · Prada", "1949–",
 "Milan intellectual of fashion who made ugly chic and thought wearable.",
 "Intellettuale milanese della moda che rese il brutto chic e il pensiero indossabile."),
"gucci": ("Guccio Gucci", "Founder · Gucci", "Fondatore · Gucci", "1881–1953",
 "Florentine craftsman whose luggage became a legend of leather.",
 "Artigiano fiorentino le cui valigie divennero leggenda della pelle."),
"dolce": ("Domenico Dolce", "Co-founder · Dolce & Gabbana", "Co-fondatore · Dolce & Gabbana", "1958–",
 "Sicilian tailor of dreams celebrating family, craft and the South.",
 "Sarto siciliano dei sogni che celebra famiglia, artigianato e Sud."),
"valentino": ("Valentino Garavani", "Founder · Valentino", "Fondatore · Valentino", "1932–",
 "Roman couturier of red and romance, master of timeless elegance.",
 "Couturier romano del rosso e del romanticismo, maestro di eleganza senza tempo."),
"doris": ("Ennio Doris", "Founder · Mediolanum", "Fondatore · Mediolanum", "1940–2021",
 "Venetian banker who built trust one family at a time.",
 "Banchiere veneto che costruì la fiducia una famiglia alla volta."),
"dellavalle": ("Diego Della Valle", "Entrepreneur · Tod's", "Imprenditore · Tod's", "1953–",
 "Marche shoemaker who made the gommino a global icon of leisure.",
 "Calzolaio marchigiano che fece del gommino un'icona globale del tempo libero."),
"ferragamo": ("Salvatore Ferragamo", "Founder · Ferragamo", "Fondatore · Ferragamo", "1898–1960",
 "Shoemaker to the stars who sculpted shoes like architecture.",
 "Calzolaio delle dive che scolpiva le scarpe come architetture."),
"lavazza": ("Luigi Lavazza", "Founder · Lavazza", "Fondatore · Lavazza", "1859–1949",
 "Turin grocer who invented the art of coffee blending.",
 "Droghiere torinese che inventò l'arte della miscela del caffè."),
"moschino": ("Franco Moschino", "Founder · Moschino", "Fondatore · Moschino", "1950–1994",
 "Irreverent designer who mocked fashion to love it better.",
 "Stilista irriverente che prendeva in giro la moda per amarla di più."),
}

Q = [
# Agnelli x10
("agnelli-01","agnelli","Style is the only thing you cannot buy.","Lo stile è l'unica cosa che non puoi comprare.",A,AI),
("agnelli-02","agnelli","Decide quickly, explain slowly.","Decidi in fretta, spiega con calma.",A,AI),
("agnelli-03","agnelli","A company is people before it is numbers.","Un'azienda è persone prima che numeri.",S,SI),
("agnelli-04","agnelli","Elegance is refusing to show off.","L'eleganza è rifiutare di ostentare.",A,AI),
("agnelli-05","agnelli","The future belongs to those who prepare it.","Il futuro appartiene a chi lo prepara.",S,SI),
("agnelli-06","agnelli","Never confuse movement with progress.","Non confondere mai il movimento con il progresso.",A,AI),
("agnelli-07","agnelli","Risk is the price of every great enterprise.","Il rischio è il prezzo di ogni grande impresa.",S,SI),
("agnelli-08","agnelli","Charm opens doors that power cannot.","Il fascino apre porte che il potere non può.",A,AI),
("agnelli-09","agnelli","Work hard, arrive on time, keep your word.","Lavora sodo, arriva in orario, mantieni la parola.",S,SI),
("agnelli-10","agnelli","Italy wins when beauty meets discipline.","L'Italia vince quando la bellezza incontra la disciplina.",S,SI),
# Barilla x10
("barilla-01","barilla","Quality is never an expense. It is an investment.","La qualità non è mai una spesa. È un investimento.",C,CI),
("barilla-02","barilla","Feed people as you would feed your family.","Nutri le persone come nutriresti la tua famiglia.",C,CI),
("barilla-03","barilla","A simple dish, done perfectly, is luxury.","Un piatto semplice, fatto alla perfezione, è lusso.",S,SI),
("barilla-04","barilla","Tradition is innovation that succeeded.","La tradizione è innovazione che ha avuto successo.",A,AI),
("barilla-05","barilla","Never compromise on what goes to the table.","Non scendere mai a compromessi su ciò che va in tavola.",C,CI),
("barilla-06","barilla","Grow slowly, but grow solid.","Cresci lentamente, ma cresci solido.",S,SI),
("barilla-07","barilla","The customer tastes everything, even our doubts.","Il cliente assaggia tutto, anche i nostri dubbi.",A,AI),
("barilla-08","barilla","Respect wheat, respect work, respect people.","Rispetta il grano, rispetta il lavoro, rispetta le persone.",C,CI),
("barilla-09","barilla","Export the best of Italy, never its shortcuts.","Esporta il meglio dell'Italia, mai le sue scorciatoie.",S,SI),
("barilla-10","barilla","A brand is a promise renewed daily.","Un marchio è una promessa rinnovata ogni giorno.",C,CI),
# G. Ferrero x10
("gferrero-01","gferrero","Think in decades, act every day.","Pensa in decenni, agisci ogni giorno.",S,SI),
("gferrero-02","gferrero","Discretion protects what matters.","La discrezione protegge ciò che conta.",S,SI),
("gferrero-03","gferrero","Innovation must serve joy.","L'innovazione deve servire la gioia.",C,CI),
("gferrero-04","gferrero","A family company thinks like a family.","Un'azienda familiare pensa come una famiglia.",S,SI),
("gferrero-05","gferrero","Quality first, always.","Prima la qualità, sempre.",C,CI),
("gferrero-06","gferrero","Grow where trust can grow.","Cresci dove la fiducia può crescere.",S,SI),
("gferrero-07","gferrero","Listen to consumers, surprise them gently.","Ascolta i consumatori, sorprendili con garbo.",C,CI),
("gferrero-08","gferrero","Patience is a strategy.","La pazienza è una strategia.",S,SI),
("gferrero-09","gferrero","Protect the recipe, share the happiness.","Proteggi la ricetta, condividi la felicità.",C,CI),
("gferrero-10","gferrero","Legacy is built one honest product at a time.","L'eredità si costruisce un prodotto onesto alla volta.",S,SI),
# Illy x10
("illy-01","illy","A cup of coffee can contain the world.","Una tazzina di caffè può contenere il mondo.",S,SI),
("illy-02","illy","Sustainability is quality that lasts.","La sostenibilità è qualità che dura.",C,CI),
("illy-03","illy","Beauty improves taste.","La bellezza migliora il gusto.",S,SI),
("illy-04","illy","Pay farmers fairly and quality follows.","Paga i coltivatori il giusto e la qualità segue.",C,CI),
("illy-05","illy","Science and poetry brew together.","Scienza e poesia si preparano insieme.",S,SI),
("illy-06","illy","Excellence is a daily habit.","L'eccellenza è un'abitudine quotidiana.",C,CI),
("illy-07","illy","Complexity, balance, sweetness: never compromise.","Complessità, equilibrio, dolcezza: mai compromessi.",C,CI),
("illy-08","illy","The best marketing is a perfect cup.","Il miglior marketing è una tazzina perfetta.",S,SI),
("illy-09","illy","Art makes business human.","L'arte rende umano il business.",S,SI),
("illy-10","illy","Small cup, great responsibility.","Tazzina piccola, grande responsabilità.",A,AI),
# Rana x10
("rana-01","rana","Fresh pasta is love you can taste.","La pasta fresca è amore che si assaggia.",C,CI),
("rana-02","rana","I still knead with my heart first.","Impastato ancora prima con il cuore.",S,SI),
("rana-03","rana","Do one thing and do it fresh daily.","Fai una cosa sola e falla fresca ogni giorno.",S,SI),
("rana-04","rana","Tradition must arrive fresh.","La tradizione deve arrivare fresca.",C,CI),
("rana-05","rana","Taste everything yourself, every day.","Assaggia tutto di persona, ogni giorno.",S,SI),
("rana-06","rana","From Verona to the world, one tortellino at a time.","Da Verona al mondo, un tortellino alla volta.",S,SI),
("rana-07","rana","Never freeze your passion.","Non congelare mai la tua passione.",A,AI),
("rana-08","rana","The artisan eye beats the machine clock.","L'occhio dell'artigiano batte l'orologio della macchina.",S,SI),
("rana-09","rana","Family recipes are serious business.","Le ricette di famiglia sono una cosa seria.",C,CI),
("rana-10","rana","Smile while you work; dough feels it.","Sorridi mentre lavori; la sfoglia lo sente.",A,AI),
# Versace x10
("versace-01","versace","Fashion is emotion made visible.","La moda è emozione resa visibile.",S,SI),
("versace-02","versace","Don't be afraid to shine.","Non aver paura di brillare.",A,AI),
("versace-03","versace","Elegance with courage, always.","Eleganza con coraggio, sempre.",S,SI),
("versace-04","versace","The South taught me color and pride.","Il Sud mi ha insegnato colore e orgoglio.",S,SI),
("versace-05","versace","Dress as if the world is watching.","Vestiti come se il mondo guardasse.",A,AI),
("versace-06","versace","Luxury is confidence.","Il lusso è sicurezza di sé.",A,AI),
("versace-07","versace","Mix the classic with the daring.","Mescola il classico con l'audace.",S,SI),
("versace-08","versace","A dress should empower, never hide.","Un abito deve dare forza, mai nascondere.",S,SI),
("versace-09","versace","Glamour is honesty with sparkle.","Il glamour è onestà con scintille.",A,AI),
("versace-10","versace","Create myth, but sew it well.","Crea il mito, ma cucilo bene.",S,SI),
# Prada x10
("prada-01","prada","Fashion is a way of thinking.","La moda è un modo di pensare.",S,SI),
("prada-02","prada","Ugly can be interesting.","Il brutto può essere interessante.",S,SI),
("prada-03","prada","Intellect is the best accessory.","L'intelletto è il miglior accessorio.",A,AI),
("prada-04","prada","Question good taste, keep elegance.","Metti in dubbio il buon gusto, conserva l'eleganza.",S,SI),
("prada-05","prada","Simplicity requires intelligence.","La semplicità richiede intelligenza.",S,SI),
("prada-06","prada","Nylon taught me luxury has no rules.","Il nylon mi ha insegnato che il lusso non ha regole.",S,SI),
("prada-07","prada","Dress the mind first.","Vesti prima la mente.",A,AI),
("prada-08","prada","Contradiction is creative.","La contraddizione è creativa.",S,SI),
("prada-09","prada","Work with artists, think like one.","Lavora con artisti, pensa come uno di loro.",S,SI),
("prada-10","prada","Power can be quiet.","Il potere può essere silenzioso.",A,AI),
# Gucci x10
("gucci-01","gucci","Quality is remembered long after price.","La qualità si ricorda molto dopo il prezzo.",A,AI),
("gucci-02","gucci","Craft every stitch as a signature.","Cura ogni punto come una firma.",C,CI),
("gucci-03","gucci","Leather remembers the hands that shape it.","La pelle ricorda le mani che la plasmano.",A,AI),
("gucci-04","gucci","Florence taught me patience and precision.","Firenze mi ha insegnato pazienza e precisione.",S,SI),
("gucci-05","gucci","A bag carries dreams, not only things.","Una borsa porta sogni, non solo cose.",A,AI),
("gucci-06","gucci","Details are the brand.","I dettagli sono il marchio.",C,CI),
("gucci-07","gucci","Serve travelers with dignity.","Servi i viaggiatori con dignità.",S,SI),
("gucci-08","gucci","Heritage must travel.","L'eredità deve viaggiare.",A,AI),
("gucci-09","gucci","Never rush the artisan.","Non aver fretta con l'artigiano.",C,CI),
("gucci-10","gucci","Timeless beats trendy.","Senza tempo batte di moda.",A,AI),
# Dolce x10
("dolce-01","dolce","Family is our first atelier.","La famiglia è il nostro primo atelier.",S,SI),
("dolce-02","dolce","Sicily is not a place. It is a feeling.","La Sicilia non è un luogo. È un sentimento.",S,SI),
("dolce-03","dolce","Sew with passion, finish with love.","Cuci con passione, rifinisci con amore.",C,CI),
("dolce-04","dolce","Tradition is our avant-garde.","La tradizione è la nostra avanguardia.",S,SI),
("dolce-05","dolce","Black dresses, warm hearts.","Abiti neri, cuori caldi.",A,AI),
("dolce-06","dolce","Craft beats speed, always.","L'artigianato batte la velocità, sempre.",C,CI),
("dolce-07","dolce","Celebrate women, celebrate life.","Celebra le donne, celebra la vita.",S,SI),
("dolce-08","dolce","Two minds, one hand.","Due menti, una sola mano.",S,SI),
("dolce-09","dolce","Details speak Sicilian.","I dettagli parlano siciliano.",A,AI),
("dolce-10","dolce","Love is the best tailor.","L'amore è il miglior sarto.",A,AI),
# Valentino x10
("valentino-01","valentino","Red is the color of love and courage.","Il rosso è il colore dell'amore e del coraggio.",S,SI),
("valentino-02","valentino","Elegance never shouts.","L'eleganza non alza mai la voce.",A,AI),
("valentino-03","valentino","A woman in red is unforgettable.","Una donna in rosso è indimenticabile.",S,SI),
("valentino-04","valentino","Romance requires discipline.","Il romanticismo richiede disciplina.",S,SI),
("valentino-05","valentino","Perfection lives in the hem.","La perfezione vive nell'orlo.",C,CI),
("valentino-06","valentino","Dreams need ateliers.","I sogni hanno bisogno di atelier.",A,AI),
("valentino-07","valentino","Grace is daily practice.","La grazia è pratica quotidiana.",S,SI),
("valentino-08","valentino","Beauty calms the world.","La bellezza calma il mondo.",A,AI),
("valentino-09","valentino","Bow to no trend.","Non inchinarti a nessuna moda.",A,AI),
("valentino-10","valentino","Couture is respect for women.","L'alta moda è rispetto per le donne.",S,SI),
# Doris x10
("doris-01","doris","Trust is earned one family at a time.","La fiducia si guadagna una famiglia alla volta.",S,SI),
("doris-02","doris","Listen before you advise.","Ascolta prima di consigliare.",C,CI),
("doris-03","doris","The client is a person, never a number.","Il cliente è una persona, mai un numero.",C,CI),
("doris-04","doris","Optimism is a working method.","L'ottimismo è un metodo di lavoro.",S,SI),
("doris-05","doris","Promises kept build banks.","Le promesse mantenute costruiscono banche.",C,CI),
("doris-06","doris","Smile; finance needs humanity.","Sorridi; la finanza ha bisogno di umanità.",S,SI),
("doris-07","doris","Grow with those who trust you.","Cresci con chi si fida di te.",C,CI),
("doris-08","doris","Simplicity wins in complex markets.","La semplicità vince nei mercati complessi.",S,SI),
("doris-09","doris","Courage in calm waters, calm in storms.","Coraggio in acque calme, calma nelle tempeste.",A,AI),
("doris-10","doris","A handshake still matters.","Una stretta di mano conta ancora.",S,SI),
# Della Valle x10
("dellavalle-01","dellavalle","Made in Italy is a responsibility.","Il Made in Italy è una responsabilità.",S,SI),
("dellavalle-02","dellavalle","Comfort can be elegant.","La comodità può essere elegante.",C,CI),
("dellavalle-03","dellavalle","Protect artisans, protect the future.","Proteggi gli artigiani, proteggi il futuro.",S,SI),
("dellavalle-04","dellavalle","Invest in beauty that lasts.","Investi in bellezza che dura.",S,SI),
("dellavalle-05","dellavalle","A shoe must feel like freedom.","Una scarpa deve dare sensazione di libertà.",C,CI),
("dellavalle-06","dellavalle","Luxury without arrogance.","Lusso senza arroganza.",A,AI),
("dellavalle-07","dellavalle","The Marche taught me humility and craft.","Le Marche mi hanno insegnato umiltà e mestiere.",S,SI),
("dellavalle-08","dellavalle","Restore what you love.","Restaura ciò che ami.",S,SI),
("dellavalle-09","dellavalle","Quality walks far.","La qualità cammina lontano.",A,AI),
("dellavalle-10","dellavalle","Tradition with a light step.","Tradizione con passo leggero.",C,CI),
# Ferragamo x10
("ferragamo-01","ferragamo","Shoes are architecture for the feet.","Le scarpe sono architettura per i piedi.",S,SI),
("ferragamo-02","ferragamo","Study the foot, serve the walk.","Studia il piede, servi il passo.",C,CI),
("ferragamo-03","ferragamo","Comfort and beauty must agree.","Comodità e bellezza devono andare d'accordo.",S,SI),
("ferragamo-04","ferragamo","Experiment, but respect the foot.","Sperimenta, ma rispetta il piede.",C,CI),
("ferragamo-05","ferragamo","Hollywood taught me dreams have sizes.","Hollywood mi ha insegnato che i sogni hanno misure.",S,SI),
("ferragamo-06","ferragamo","Innovation walks on leather.","L'innovazione cammina sulla pelle.",A,AI),
("ferragamo-07","ferragamo","Patent your imagination.","Brevetta la tua immaginazione.",S,SI),
("ferragamo-08","ferragamo","Elegance starts from the ground.","L'eleganza parte da terra.",A,AI),
("ferragamo-09","ferragamo","Craft is science with soul.","L'artigianato è scienza con l'anima.",C,CI),
("ferragamo-10","ferragamo","Serve stars, stay humble.","Servi le dive, resta umile.",S,SI),
# Lavazza x10
("lavazza-01","lavazza","Blending is an art of balance.","La miscela è un'arte dell'equilibrio.",C,CI),
("lavazza-02","lavazza","Every origin brings a voice.","Ogni origine porta una voce.",C,CI),
("lavazza-03","lavazza","Roast with patience, serve with joy.","Tosta con pazienza, servi con gioia.",C,CI),
("lavazza-04","lavazza","Coffee unites the morning world.","Il caffè unisce il mondo del mattino.",S,SI),
("lavazza-05","lavazza","From Turin grocer to world ritual.","Da droghiere torinese a rito mondiale.",S,SI),
("lavazza-06","lavazza","Taste before you talk.","Assaggia prima di parlare.",A,AI),
("lavazza-07","lavazza","Consistency is the hardest blend.","La costanza è la miscela più difficile.",C,CI),
("lavazza-08","lavazza","Respect the bean, respect the farmer.","Rispetta il chicco, rispetta il coltivatore.",C,CI),
("lavazza-09","lavazza","Aroma is memory.","L'aroma è memoria.",A,AI),
("lavazza-10","lavazza","Good coffee makes good days.","Il buon caffè fa buone giornate.",S,SI),
# Moschino x10
("moschino-01","moschino","Fashion should make you smile.","La moda dovrebbe farti sorridere.",S,SI),
("moschino-02","moschino","Irony is elegance with a wink.","L'ironia è eleganza con un occhiolino.",A,AI),
("moschino-03","moschino","Mock the rules, respect the craft.","Prendi in giro le regole, rispetta il mestiere.",S,SI),
("moschino-04","moschino","Luxury can laugh at itself.","Il lusso può ridere di sé.",A,AI),
("moschino-05","moschino","A joke sewn well lasts.","Una battuta cucita bene dura.",S,SI),
("moschino-06","moschino","Be serious about not being serious.","Sii serio nel non essere serio.",A,AI),
("moschino-07","moschino","Provoke gently, dress kindly.","Provoca con garbo, vesti con gentilezza.",S,SI),
("moschino-08","moschino","Style is play.","Lo stile è gioco.",A,AI),
("moschino-09","moschino","Against snobbery, with scissors.","Contro lo snobismo, con le forbici.",A,AI),
("moschino-10","moschino","Love fashion enough to tease it.","Ama la moda abbastanza da prenderla in giro.",S,SI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchA added={added} total_en={len(en)} total_it={len(it)}")
