"""Batch H: international entrepreneurs 3, historical (17 x 10 = 170)."""
import json

CAT = "international_entrepreneurs"
S, SI = "Interviews", "Interviste"
A, AI = "Attributed", "Attribuita"
C, CI = "Company philosophy", "Filosofia aziendale"

AUTHORS = {
"rockefeller": ("John D. Rockefeller", "Founder · Standard Oil", "Fondatore · Standard Oil", "1839–1937",
 "Cleveland bookkeeper who refined oil and philanthropy alike.",
 "Contabile di Cleveland che raffinò petrolio e filantropia."),
"morgan": ("J.P. Morgan", "Banker · Morgan", "Banchiere · Morgan", "1837–1913",
 "Wall Street consolidator electrifying America.",
 "Consolidatore di Wall Street che elettrificò l'America."),
"kellogg": ("W.K. Kellogg", "Founder · Kellogg's", "Fondatore · Kellogg's", "1860–1951",
 "Corn-flake brother who breakfasted the world.",
 "Fratello dei corn-flake che diede colazione al mondo."),
"gillette": ("King C. Gillette", "Founder · Gillette", "Fondatore · Gillette", "1855–1932",
 "Traveling salesman who made shaving disposable.",
 "Commesso viaggiatore che rese usa e getta la rasatura."),
"eastman": ("George Eastman", "Founder · Kodak", "Fondatore · Kodak", "1854–1932",
 "Rochester banker who put cameras in every pocket.",
 "Banchiere di Rochester che mise fotocamere in ogni tasca."),
"firestone": ("Harvey Firestone", "Founder · Firestone", "Fondatore · Firestone", "1868–1938",
 "Ohio tire man rolling with Ford and Edison.",
 "Uomo di pneumatici dell'Ohio al passo con Ford ed Edison."),
"procter": ("William Procter", "Co-founder · P&G", "Co-fondatore · P&G", "1801–1884",
 "Cincinnati candlemaker soaping the world.",
 "Candelaio di Cincinnati che insaponò il mondo."),
"gamble": ("James Gamble", "Co-founder · P&G", "Co-fondatore · P&G", "1803–1891",
 "Irish soapmaker floating Ivory worldwide.",
 "Saponaro irlandese che fece galleggiare Ivory nel mondo."),
"heinz": ("Henry J. Heinz", "Founder · Heinz", "Fondatore · Heinz", "1844–1919",
 "Horseradish boy bottling 57 varieties.",
 "Ragazzo del rafano che imbottigliò 57 varietà."),
"cadbury": ("John Cadbury", "Founder · Cadbury", "Fondatore · Cadbury", "1801–1889",
 "Birmingham Quaker sweetening tea time.",
 "Quacchero di Birmingham che addolcì l'ora del tè."),
"nestle": ("Henri Nestlé", "Founder · Nestlé", "Fondatore · Nestlé", "1814–1890",
 "Vevey pharmacist nourishing infants globally.",
 "Farmacista di Vevey che nutrì neonati globalmente."),
"michelin": ("Édouard Michelin", "Co-founder · Michelin", "Co-fondatore · Michelin", "1859–1940",
 "Clermont rubber man guiding tires and taste.",
 "Uomo di gomma di Clermont che guidò gomme e gusto."),
"benz": ("Karl Benz", "Founder · Benz", "Fondatore · Benz", "1844–1929",
 "Mannheim engineer patenting the automobile.",
 "Ingegnere di Mannheim che brevettò l'automobile."),
"porsche": ("Ferdinand Porsche", "Founder · Porsche", "Fondatore · Porsche", "1875–1951",
 "Bohemian designer electrifying speed.",
 "Designer boemo che elettrificò la velocità."),
"toyoda": ("Sakichi Toyoda", "Founder · Toyota", "Fondatore · Toyota", "1867–1930",
 "Carpenter's son looming Japan into motion.",
 "Figlio di falegname che tesse il Giappone in movimento."),
"matsushita": ("Kōnosuke Matsushita", "Founder · Panasonic", "Fondatore · Panasonic", "1894–1989",
 "Osaka socket seller lighting postwar homes.",
 "Venditore di prese di Osaka che illuminò case del dopoguerra."),
"ibuka": ("Masaru Ibuka", "Co-founder · Sony", "Co-fondatore · Sony", "1908–1997",
 "Tokyo engineer miniaturizing wonder.",
 "Ingegnere di Tokyo che miniaturizzò la meraviglia."),
}

Q = [
("rockefeller-01","rockefeller","Do you know the only thing that gives me pleasure? Dividends.","Sai l'unica cosa che mi dà piacere? I dividendi.",A,AI),
("rockefeller-02","rockefeller","I always tried to turn every disaster into opportunity.","Ho sempre cercato di trasformare ogni disastro in opportunità.",A,AI),
("rockefeller-03","rockefeller","Don't be afraid to give up the good for the great.","Non aver paura di lasciare il buono per l'ottimo.",A,AI),
("rockefeller-04","rockefeller","Charity must heal, not just help.","La carità deve guarire, non solo aiutare.",S,SI),
("rockefeller-05","rockefeller","Refine oil, refine giving.","Raffina petrolio, raffina il dare.",A,AI),
("rockefeller-06","rockefeller","Cleveland ledgers taught empires.","I registri di Cleveland insegnarono imperi.",A,AI),
("rockefeller-07","rockefeller","Combine competitors, calm markets.","Unisci concorrenti, calma mercati.",S,SI),
("rockefeller-08","rockefeller","Universities outlive derricks.","Le università durano più delle trivelle.",S,SI),
("rockefeller-09","rockefeller","Nickels saved build nations.","I nichelini risparmiati costruiscono nazioni.",A,AI),
("rockefeller-10","rockefeller","Give systematically, live simply.","Dona sistematico, vivi semplice.",S,SI),
("morgan-01","morgan","A man always has two reasons: a good one and the real one.","Un uomo ha sempre due ragioni: una buona e quella vera.",A,AI),
("morgan-02","morgan","Character before collateral.","Il carattere prima delle garanzie.",A,AI),
("morgan-03","morgan","Consolidate chaos into confidence.","Consolida il caos in fiducia.",S,SI),
("morgan-04","morgan","Electrify America, finance genius.","Elettrifica l'America, finanzia il genio.",S,SI),
("morgan-05","morgan","Panics need a steady hand.","I panici hanno bisogno di mano salda.",S,SI),
("morgan-06","morgan","Collect art, corner markets.","Colleziona arte, accaparra mercati.",A,AI),
("morgan-07","morgan","Libraries outlast loans.","Le biblioteche durano più dei prestiti.",A,AI),
("morgan-08","morgan","Trust moves more than money.","La fiducia muove più del denaro.",A,AI),
("morgan-09","morgan","Yachts sail, empires merge.","Gli yacht navigano, gli imperi si fondono.",A,AI),
("morgan-10","morgan","Pierpont decides, Wall Street follows.","Pierpont decide, Wall Street segue.",A,AI),
("kellogg-01","kellogg","Breakfast is the day's foundation.","La colazione è la fondazione del giorno.",C,CI),
("kellogg-02","kellogg","Flake corn, feed millions.","Fiocca mais, nutri milioni.",C,CI),
("kellogg-03","kellogg","Battle Creek crunches worldwide.","Battle Creek crocchia nel mondo.",A,AI),
("kellogg-04","kellogg","Sign every box with care.","Firma ogni scatola con cura.",C,CI),
("kellogg-05","kellogg","Brothers compete, breakfast wins.","I fratelli competono, la colazione vince.",S,SI),
("kellogg-06","kellogg","Snap, crackle, consistency.","Croccantezza, costanza, consistenza.",A,AI),
("kellogg-07","kellogg","Sanitariums inspire cereals.","I sanatori ispirano cereali.",S,SI),
("kellogg-08","kellogg","Roosters crow reliability.","I galli annunciano affidabilità.",A,AI),
("kellogg-09","kellogg","Give children morning joy.","Dai ai bambini gioia mattutina.",C,CI),
("kellogg-10","kellogg","Wax seals keep promises.","I sigilli di cera mantengono promesse.",A,AI),
("gillette-01","gillette","Give razors, sell blades.","Regala rasoi, vendi lamette.",C,CI),
("gillette-02","gillette","Disposable beats durable.","Usa e getta batte durevole.",C,CI),
("gillette-03","gillette","Shave the world smoothly.","Radi il mondo liscio.",A,AI),
("gillette-04","gillette","Travel light, sell everywhere.","Viaggia leggero, vendi ovunque.",S,SI),
("gillette-05","gillette","Bottle caps inspired empires.","I tappi ispirarono imperi.",A,AI),
("gillette-06","gillette","Morning rituals scale.","I riti mattutini scalano.",C,CI),
("gillette-07","gillette","Thin steel, thick profits.","Acciaio sottile, profitti spessi.",A,AI),
("gillette-08","gillette","Patent the edge.","Brevetta il filo.",S,SI),
("gillette-09","gillette","Salesmen dream in millions.","I venditori sognano in milioni.",A,AI),
("gillette-10","gillette","Smooth faces, smooth business.","Visi lisci, affari lisci.",A,AI),
("eastman-01","eastman","You press the button, we do the rest.","Tu premi il pulsante, noi facciamo il resto.",C,CI),
("eastman-02","eastman","Pocket every memory.","Tasca ogni ricordo.",A,AI),
("eastman-03","eastman","Film democratizes moments.","La pellicola democratizza attimi.",S,SI),
("eastman-04","eastman","Rochester develops the world.","Rochester sviluppa il mondo.",A,AI),
("eastman-05","eastman","Kodak moments outlive makers.","I momenti Kodak sopravvivono ai creatori.",A,AI),
("eastman-06","eastman","Dry plates, wet ambitions.","Lastre secche, ambizioni umide.",S,SI),
("eastman-07","eastman","Music endows silence.","La musica dota il silenzio.",S,SI),
("eastman-08","eastman","Dentistry funds dentistry of light.","L'odontoiatria finanzia odontoiatria di luce.",A,AI),
("eastman-09","eastman","Simplify, then sell.","Semplifica, poi vendi.",C,CI),
("eastman-10","eastman","Give Rochester its university.","Dai a Rochester la sua università.",S,SI),
("firestone-01","firestone","Roll with Ford, think with Edison.","Rotola con Ford, pensa con Edison.",S,SI),
("firestone-02","firestone","Tires carry friendships.","Gli pneumatici portano amicizie.",A,AI),
("firestone-03","firestone","Vagabond summers inspire.","Le estati vagabonde ispirano.",S,SI),
("firestone-04","firestone","Ohio rubber grips history.","La gomma dell'Ohio afferra la storia.",A,AI),
("firestone-05","firestone","Camping trips test tires.","I campeggi testano gomme.",S,SI),
("firestone-06","firestone","Memoirs roll smoothly.","Le memorie rotolano lisce.",A,AI),
("firestone-07","firestone","Dealers deserve loyalty.","I rivenditori meritano lealtà.",C,CI),
("firestone-08","firestone","Liberia grows our future.","La Liberia coltiva il nostro futuro.",S,SI),
("firestone-09","firestone","Men, money, memories.","Uomini, denaro, memorie.",A,AI),
("firestone-10","firestone","Keep rolling forward.","Continua a rotolare avanti.",A,AI),
("procter-01","procter","Candles light, soap cleans, trust lasts.","Le candele illuminano, il sapone pulisce, la fiducia dura.",C,CI),
("procter-02","procter","Cincinnati crafts cleanliness.","Cincinnati artigiana pulizia.",A,AI),
("procter-03","procter","Moonlight funds moonshots.","Il chiaro di luna finanzia moonshot.",A,AI),
("procter-04","procter","Partner with a Gamble, win.","Scommetti con un Gamble, vinci.",S,SI),
("procter-05","procter","Brands outlive founders.","I marchi sopravvivono ai fondatori.",C,CI),
("procter-06","procter","Research rinses doubt.","La ricerca risciacqua il dubbio.",C,CI),
("procter-07","procter","Ivory floats on integrity.","Ivory galleggia su integrità.",C,CI),
("procter-08","procter","Sunday rest, Monday hustle.","Domenica riposo, lunedì impegno.",A,AI),
("procter-09","procter","English craft, American scale.","Mestiere inglese, scala americana.",S,SI),
("procter-10","procter","Clean products, clear conscience.","Prodotti puliti, coscienza pulita.",C,CI),
("gamble-01","gamble","Soap the nation kindly.","Insapona la nazione con garbo.",C,CI),
("gamble-02","gamble","Irish hands, American lather.","Mani irlandesi, schiuma americana.",A,AI),
("gamble-03","gamble","Chemistry cleans conscience.","La chimica pulisce coscienza.",C,CI),
("gamble-04","gamble","Profit-share with workers.","Condividi profitti con operai.",S,SI),
("gamble-05","gamble","Ivory: pure and floating.","Ivory: pura e galleggiante.",C,CI),
("gamble-06","gamble","Advertise the sunrise.","Pubblicizza l'alba.",A,AI),
("gamble-07","gamble","Lab coats beat guesswork.","I camici battono le congetture.",C,CI),
("gamble-08","gamble","Wash worries away.","Lava via le preoccupazioni.",A,AI),
("gamble-09","gamble","Tide lifts all brands.","La marea solleva tutti i marchi.",A,AI),
("gamble-10","gamble","Serve Cincinnati, span continents.","Servi Cincinnati, abbraccia continenti.",S,SI),
("heinz-01","heinz","Do a common thing uncommonly well.","Fai una cosa comune in modo non comune.",A,AI),
("heinz-02","heinz","57 varieties, one promise.","57 varietà, una promessa.",C,CI),
("heinz-03","heinz","Pickles teach patience.","I sottaceti insegnano pazienza.",S,SI),
("heinz-04","heinz","Pittsburgh bottles diligence.","Pittsburgh imbottiglia diligenza.",A,AI),
("heinz-05","heinz","Ketchup slowly, success surely.","Ketchup piano, successo sicuro.",A,AI),
("heinz-06","heinz","Horseradish roots run deep.","Le radici di rafano corrono profonde.",S,SI),
("heinz-07","heinz","Glass shows honesty.","Il vetro mostra onestà.",C,CI),
("heinz-08","heinz","Taste tests never lie.","I test di gusto non mentono mai.",C,CI),
("heinz-09","heinz","Grow your own tomatoes.","Coltiva i tuoi pomodori.",S,SI),
("heinz-10","heinz","Anticipate appetites.","Anticipa gli appetiti.",A,AI),
("cadbury-01","cadbury","Cocoa with a conscience.","Cacao con coscienza.",C,CI),
("cadbury-02","cadbury","Bournville houses happiness.","Bournville ospita felicità.",S,SI),
("cadbury-03","cadbury","Quakers sweeten fairly.","I quaccheri addolciscono equo.",S,SI),
("cadbury-04","cadbury","Tea time deserves chocolate.","L'ora del tè merita cioccolato.",A,AI),
("cadbury-05","cadbury","Workers deserve gardens.","Gli operai meritano giardini.",S,SI),
("cadbury-06","cadbury","Birmingham melts kindness.","Birmingham fonde gentilezza.",A,AI),
("cadbury-07","cadbury","Dairy milk, daily care.","Latte fresco, cura quotidiana.",C,CI),
("cadbury-08","cadbury","Temperance pairs with treats.","La temperanza si abbina ai dolci.",S,SI),
("cadbury-09","cadbury","Purple wraps promise.","Il viola avvolge promessa.",A,AI),
("cadbury-10","cadbury","Sweeten without exploiting.","Addolcisci senza sfruttare.",C,CI),
("nestle-01","nestle","Nourish infants, earn trust.","Nutri neonati, guadagna fiducia.",C,CI),
("nestle-02","nestle","Vevey mixes science and milk.","Vevey mescola scienza e latte.",S,SI),
("nestle-03","nestle","Farine lactée feeds futures.","La farina lattea nutre futuri.",C,CI),
("nestle-04","nestle","Swiss precision, global cradles.","Precisione svizzera, culle globali.",A,AI),
("nestle-05","nestle","Pharmacists heal hunger.","I farmacisti guariscono la fame.",S,SI),
("nestle-06","nestle","Condensed care travels.","La cura condensata viaggia.",C,CI),
("nestle-07","nestle","Lake Geneva reflects responsibility.","Il Lemano riflette responsabilità.",A,AI),
("nestle-08","nestle","Quality in every tin.","Qualità in ogni lattina.",C,CI),
("nestle-09","nestle","Feed babies, respect mothers.","Nutri bebè, rispetta madri.",C,CI),
("nestle-10","nestle","Begin with nourishment.","Comincia dal nutrimento.",S,SI),
("michelin-01","michelin","Guides sell tires deliciously.","Le guide vendono gomme deliziosamente.",C,CI),
("michelin-02","michelin","Stars reward the journey.","Le stelle premiano il viaggio.",C,CI),
("michelin-03","michelin","Clermont grips the road.","Clermont afferra la strada.",A,AI),
("michelin-04","michelin","Bibendum smiles mileage.","Bibendum sorride chilometraggio.",A,AI),
("michelin-05","michelin","Maps multiply appetite.","Le mappe moltiplicano appetito.",C,CI),
("michelin-06","michelin","Rubber meets refinement.","La gomma incontra raffinatezza.",A,AI),
("michelin-07","michelin","Three stars, full tanks.","Tre stelle, pieni di benzina.",A,AI),
("michelin-08","michelin","Brothers roll together.","I fratelli rotolano insieme.",S,SI),
("michelin-09","michelin","Taste travels on tires.","Il gusto viaggia su gomme.",C,CI),
("michelin-10","michelin","Green guides, red seals.","Guide verdi, sigilli rossi.",A,AI),
("benz-01","benz","Patent the horseless carriage.","Brevetta la carrozza senza cavalli.",S,SI),
("benz-02","benz","Mannheim engines whisper future.","I motori di Mannheim sussurrano futuro.",A,AI),
("benz-03","benz","Bertha drove belief.","Bertha guidò la fede.",S,SI),
("benz-04","benz","Three wheels beat four horses.","Tre ruote battono quattro cavalli.",A,AI),
("benz-05","benz","Inventors need brave wives.","Gli inventori hanno bisogno di mogli coraggiose.",A,AI),
("benz-06","benz","Precision ignites progress.","La precisione accende progresso.",C,CI),
("benz-07","benz","The best or nothing begins here.","Il meglio o niente comincia qui.",A,AI),
("benz-08","benz","Workshops birth worlds.","Le officine partoriscono mondi.",S,SI),
("benz-09","benz","Gasoline dreams, steel realities.","Sogni di benzina, realtà d'acciaio.",A,AI),
("benz-10","benz","1886 changed every road.","Il 1886 cambiò ogni strada.",S,SI),
("porsche-01","porsche","Electrify speed early.","Elettrifica presto la velocità.",S,SI),
("porsche-02","porsche","Stuttgart shapes curves.","Stoccarda plasma curve.",A,AI),
("porsche-03","porsche","Rear engines, front visions.","Motori posteriori, visioni anteriori.",C,CI),
("porsche-04","porsche","Hybrids haunted my youth.","Gli ibridi ossessionarono la mia giovinezza.",S,SI),
("porsche-05","porsche","Design the Beetle, dream the 911.","Disegna il Maggiolino, sogna la 911.",A,AI),
("porsche-06","porsche","Racing proves engineering.","Le corse dimostrano ingegneria.",C,CI),
("porsche-07","porsche","Bohemian sparks, German steel.","Scintille boeme, acciaio tedesco.",A,AI),
("porsche-08","porsche","Sons continue the line.","I figli continuano la linea.",S,SI),
("porsche-09","porsche","Form follows velocity.","La forma segue la velocità.",A,AI),
("porsche-10","porsche","No substitute for soul.","Nessun sostituto per l'anima.",A,AI),
("toyoda-01","toyoda","Looms wove our discipline.","I telai tessero la nostra disciplina.",S,SI),
("toyoda-02","toyoda","Automatic stops prevent defects.","Fermate automatiche prevengono difetti.",C,CI),
("toyoda-03","toyoda","Study American cars, surpass them.","Studia le auto americane, superale.",S,SI),
("toyoda-04","toyoda","Carpentry crafts patience.","La falegnameria artigiana pazienza.",A,AI),
("toyoda-05","toyoda","Invention funds industry.","L'invenzione finanzia industria.",S,SI),
("toyoda-06","toyoda","Sons industrialize dreams.","I figli industrializzano sogni.",A,AI),
("toyoda-07","toyoda","Quality threads everything.","La qualità fila tutto.",C,CI),
("toyoda-08","toyoda","Nagoya hammers forward.","Nagoya martella in avanti.",A,AI),
("toyoda-09","toyoda","Jidoka guards the line.","Jidoka custodisce la linea.",C,CI),
("toyoda-10","toyoda","Weave motion into Japan.","Tessi movimento nel Giappone.",S,SI),
("matsushita-01","matsushita","Sockets light the nation.","Le prese illuminano la nazione.",S,SI),
("matsushita-02","matsushita","Water philosophy: abundance for all.","Filosofia dell'acqua: abbondanza per tutti.",S,SI),
("matsushita-03","matsushita","Osaka apprenticeships forge founders.","Gli apprendistati di Osaka forgiano fondatori.",S,SI),
("matsushita-04","matsushita","Profits serve society.","I profitti servono la società.",C,CI),
("matsushita-05","matsushita","Tap water pricing enlightens.","I prezzi da acqua di rubinetto illuminano.",A,AI),
("matsushita-06","matsushita","Seven principles guide.","Sette principi guidano.",C,CI),
("matsushita-07","matsushita","National products, human prices.","Prodotti nazionali, prezzi umani.",C,CI),
("matsushita-08","matsushita","Collect wisdom widely.","Raccogli saggezza ampiamente.",S,SI),
("matsushita-09","matsushita","PHP: peace through prosperity.","PHP: pace attraverso prosperità.",S,SI),
("matsushita-10","matsushita","Grow people before products.","Fai crescere persone prima che prodotti.",C,CI),
("ibuka-01","ibuka","Miniaturize wonder daily.","Miniaturizza meraviglia ogni giorno.",C,CI),
("ibuka-02","ibuka","Rice cookers teach humility.","Le cuociriso insegnano umiltà.",S,SI),
("ibuka-03","ibuka","Engineers dream in transistors.","Gli ingegneri sognano in transistor.",S,SI),
("ibuka-04","ibuka","Tokyo rebuilds with circuits.","Tokyo ricostruisce con circuiti.",S,SI),
("ibuka-05","ibuka","Purpose guides research.","Lo scopo guida la ricerca.",C,CI),
("ibuka-06","ibuka","Tape records resilience.","Il nastro registra resilienza.",A,AI),
("ibuka-07","ibuka","Kindergartens need engineering.","Gli asili hanno bisogno di ingegneria.",S,SI),
("ibuka-08","ibuka","Morita markets, Ibuka invents.","Morita commercializza, Ibuka inventa.",S,SI),
("ibuka-09","ibuka","Curiosity solders success.","La curiosità salda successo.",A,AI),
("ibuka-10","ibuka","Never copy; originate compactly.","Mai copiare; origina compatto.",C,CI),
]

import os
base = os.path.join(os.path.dirname(__file__), "..", "assets")
en = json.load(open(os.path.join(base, "quotes.json"), encoding="utf-8"))
it = json.load(open(os.path.join(base, "quotes_it.json"), encoding="utf-8"))
have = {e["id"] for e in en}
added = 0
for qid, ak, ten, tit, se, si in Q:
    assert qid not in have, qid
    n, re, ri, y, be, bi = AUTHORS[ak]
    en.append({"id": qid, "text": ten, "author": n, "category": CAT,
               "role": re, "years": y, "bio": be, "source": se})
    it.append({"id": qid, "text": tit, "role": ri, "bio": bi, "source": si})
    have.add(qid); added += 1
json.dump(en, open(os.path.join(base, "quotes.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
json.dump(it, open(os.path.join(base, "quotes_it.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print(f"batchH added={added} total_en={len(en)} total_it={len(it)}")
